"""
Audit — Tenant Isolation Handlers (Task #673, ADR-018).

Lists every public function defined under ``app/domains/*/tools/`` and classifies
it as one of:

* ``decorator``      — uses ``@tool_handler`` (canonical, fail-closed on company_id)
* ``manual``         — file is annotated ``# tenant-isolation: manual`` and the
                       function consumes ``_context``/``company_id`` directly
* ``register_helper`` — a ``register_*_tools()`` aggregator, which only wires
                       handlers and does not read tenant data itself
* ``private``         — name starts with ``_``; not a tool entry-point
* ``UNPROTECTED``     — none of the above; LGPD risk, fix required

Run::

    python3 scripts/audit_tenant_isolation_handlers.py
    python3 scripts/audit_tenant_isolation_handlers.py --markdown > docs/audits/...

Exit code is always 0 — this is reporting only. The blocking check lives in
``scripts/check_tool_tenant_isolation.py``.
"""
from __future__ import annotations

import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TOOLS_GLOB = "app/domains/*/tools/**/*.py"

MODULE_ANNOTATION = "tenant-isolation: manual"


def _classify(path: Path) -> list[tuple[str, str]]:
    """Return list of ``(function_name, classification)`` for ``path``."""
    try:
        source = path.read_text(encoding="utf-8")
    except Exception:
        return []
    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []

    module_manual = MODULE_ANNOTATION in source[:2000]

    out: list[tuple[str, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.AsyncFunctionDef, ast.FunctionDef)):
            continue
        name = node.name
        decorators = []
        for d in node.decorator_list:
            try:
                decorators.append(ast.unparse(d))
            except Exception:
                decorators.append("")
        if any("tool_handler" in d for d in decorators):
            out.append((name, "decorator"))
        elif name.startswith("_"):
            out.append((name, "private"))
        elif name.startswith("register_") and name.endswith("_tools"):
            out.append((name, "register_helper"))
        elif name.startswith("get_") and name.endswith("_tools"):
            out.append((name, "register_helper"))
        elif module_manual:
            out.append((name, "manual"))
        else:
            out.append((name, "UNPROTECTED"))
    return out


def collect() -> list[tuple[Path, str, str]]:
    rows: list[tuple[Path, str, str]] = []
    for py in sorted(ROOT.glob(TOOLS_GLOB)):
        if py.name == "__init__.py":
            continue
        for func, kind in _classify(py):
            rows.append((py.relative_to(ROOT), func, kind))
    return rows


def render_markdown(rows: list[tuple[Path, str, str]]) -> str:
    counts: dict[str, int] = {}
    for _, _, kind in rows:
        counts[kind] = counts.get(kind, 0) + 1

    lines = [
        "# Tenant Isolation — Handler Audit",
        "",
        "_Generated by `scripts/audit_tenant_isolation_handlers.py` (Task #673, ADR-018)._",
        "",
        "## Summary",
        "",
        f"- Total functions scanned: **{len(rows)}**",
    ]
    for kind in ("decorator", "manual", "register_helper", "private", "UNPROTECTED"):
        lines.append(f"- `{kind}`: **{counts.get(kind, 0)}**")
    lines += [
        "",
        "## Classification rules",
        "",
        "| Class | Meaning |",
        "|---|---|",
        "| `decorator` | Uses `@tool_handler` (canonical, fail-closed on `company_id`). |",
        "| `manual` | File is annotated `# tenant-isolation: manual …` and the handler reads `company_id`/`_context` itself. Legacy path; new code MUST use `decorator`. |",
        "| `register_helper` | `register_*_tools` / `get_*_tools` aggregator — registers other handlers, does not read tenant data. |",
        "| `private` | Name starts with `_`; not a tool entry-point. |",
        "| `UNPROTECTED` | None of the above. **LGPD risk — fix before merge.** |",
        "",
        "## Per-function detail",
        "",
        "| File | Function | Class |",
        "|---|---|---|",
    ]
    for path, func, kind in rows:
        lines.append(f"| `{path}` | `{func}` | `{kind}` |")
    return "\n".join(lines) + "\n"


def main() -> int:
    rows = collect()
    if "--markdown" in sys.argv:
        print(render_markdown(rows), end="")
        return 0

    counts: dict[str, int] = {}
    for _, _, kind in rows:
        counts[kind] = counts.get(kind, 0) + 1
    print(f"[#673] Total functions in app/domains/*/tools/: {len(rows)}")
    for kind, n in sorted(counts.items()):
        print(f"  {kind:20s} {n}")
    unprotected = [(p, f) for p, f, k in rows if k == "UNPROTECTED"]
    if unprotected:
        print("\n[#673] UNPROTECTED handlers:")
        for path, func in unprotected:
            print(f"  {path}::{func}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
