#!/usr/bin/env python3
"""
generate_tool_catalog.py — gera docs/TOOL_CATALOG.md a partir dos registries de tools.

Uso: python3 scripts/generate_tool_catalog.py
Output: docs/TOOL_CATALOG.md (sobrescreve)
"""
from pathlib import Path
import re, sys
from datetime import datetime

BASE = Path(__file__).parent.parent
DOMAINS = BASE / "app/domains"
OUTPUT = BASE / "docs/TOOL_CATALOG.md"

def find_tool_names(src: str) -> list[str]:
    """Extract tool names from a registry file."""
    names = []
    # ToolDefinition(name="foo", ...)
    for m in re.finditer(r'ToolDefinition\s*\(\s*\n?\s*name\s*=\s*["\']([^"\']+)["\']', src):
        names.append(m.group(1))
    # ToolDefinition("foo", ...)
    for m in re.finditer(r'ToolDefinition\s*\(\s*["\']([^"\']+)["\']', src):
        if m.group(1) not in names:
            names.append(m.group(1))
    # name="foo" inside StructuredTool.from_function
    if "StructuredTool" in src:
        for m in re.finditer(r'name\s*=\s*["\']([^"\']+)["\']', src):
            candidate = m.group(1)
            if candidate not in names and not candidate.startswith("_"):
                names.append(candidate)
    return names

def find_description(src: str, tool_name: str) -> str:
    """Try to extract description for a tool name."""
    pattern = re.compile(
        r'name\s*=\s*["\']' + re.escape(tool_name) + r'["\'].*?description\s*=\s*["\']([^"\']{10,120})',
        re.DOTALL
    )
    m = pattern.search(src)
    if m:
        return m.group(1).strip().rstrip(".,")
    return ""

# Collect data
catalog = {}  # domain -> list of (registry_file, tool_name, description)
registry_files = sorted(DOMAINS.rglob("*tool_registry*.py")) + sorted(
    f for f in DOMAINS.rglob("registry.py") if "agent" in str(f) or "tool" in str(f)
)

for reg in registry_files:
    domain = reg.relative_to(DOMAINS).parts[0]
    if domain.startswith("_"):
        continue
    src = reg.read_text()
    names = find_tool_names(src)
    if not names:
        continue
    reg_label = str(reg.relative_to(DOMAINS / domain))
    for name in names:
        desc = find_description(src, name)
        catalog.setdefault(domain, []).append((reg_label, name, desc))

# Write output
lines = []
lines.append("# Tool Catalog — lia-agent-system")
lines.append("")
lines.append(f"> Auto-generated by `scripts/generate_tool_catalog.py` on {datetime.now().strftime('%Y-%m-%d')}.  ")
lines.append("> Do NOT edit manually — re-run the script to refresh.")
lines.append("")

total = sum(len(v) for v in catalog.values())
lines.append(f"**Total tools: {total}** across {len(catalog)} domains")
lines.append("")
lines.append("---")
lines.append("")

# TOC
lines.append("## Table of Contents")
lines.append("")
for domain in sorted(catalog):
    count = len(catalog[domain])
    anchor = domain.replace("_", "-")
    lines.append(f"- [{domain}](#{anchor}) — {count} tools")
lines.append("")
lines.append("---")
lines.append("")

# Per-domain sections
for domain in sorted(catalog):
    tools = catalog[domain]
    lines.append(f"## {domain}")
    lines.append("")
    lines.append(f"**{len(tools)} tools**")
    lines.append("")
    lines.append("| Tool | Registry file | Description |")
    lines.append("|---|---|---|")
    for reg_label, name, desc in sorted(tools, key=lambda x: x[1]):
        desc_cell = desc[:80] + "…" if len(desc) > 80 else desc
        lines.append(f"| `{name}` | `{reg_label}` | {desc_cell} |")
    lines.append("")

OUTPUT.parent.mkdir(parents=True, exist_ok=True)
OUTPUT.write_text("\n".join(lines) + "\n")
print("Written: " + str(OUTPUT))
print("Total tools: " + str(total))
print("Domains covered: " + str(len(catalog)))
