require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # In the development environment your application's code is reloaded any time
  # it changes. This slows down response time but is perfect for development
  # since you don't have to restart the web server when you make code changes.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable caching. By default caching is disabled.
  # Run rails dev:cache to toggle caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true

    config.cache_store = :redis_cache_store, { url: ENV.fetch("REDIS_URL", "redis://localhost:6379/1"), expires_in: 1.hour }
    config.public_file_server.headers = { "Cache-Control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false

    config.cache_store = :null_store
  end

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Disable caching for Action Mailer templates even if Action Controller
  # caching is enabled.
  config.action_mailer.perform_caching = false

  config.active_storage.resolve_model_to_route = :rails_storage_proxy

  config.active_storage.default_url_options = {
    host: "http://localhost:8080"
  }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise exceptions for disallowed deprecations.
  config.active_support.disallowed_deprecation = :raise

  # Tell Active Support which deprecation messages to disallow.
  config.active_support.disallowed_deprecation_warnings = []

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Disable origin check for cross-origin API requests
  config.action_controller.forgery_protection_origin_check = false

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
  config.active_job.queue_adapter = :sidekiq
  # config.active_job.queue_name_prefix = "ats_#{Rails.env}"
  config.action_cable.allowed_request_origins = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173"
  ]

  # Mailpit em development: captura todos os e-mails sem enviar para o mundo real.
  # Web UI: http://localhost:8025 | SMTP: localhost:1025 (ou mailpit:1025 no Docker)
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address: ENV.fetch("SMTP_HOST", "localhost"),
    port: ENV.fetch("SMTP_PORT", "1025").to_i,
    domain: "localhost",
    # Mailpit não requer autenticação - nil evita tentativa de AUTH
    authentication: nil,
    enable_starttls_auto: false,
    open_timeout: 5,
    read_timeout: 5
  }

  config.action_mailer.default_url_options = { host: "localhost:8080", protocol: "http" }

  config.action_cable.disable_request_forgery_protection = true

  # config.action_cable.url = "ws://localhost:8080/cable"
  config.action_cable.url = ENV.fetch("REDIS_URL", "redis://localhost:6379/1")
  config.hosts << "web:3000"
  config.hosts << "host.docker.internal"
  config.hosts << "ats_api-web-1"
  config.hosts << "ats_api-web-1:3000"
  config.hosts << "staging2.wedotalent.cc"
  config.hosts << "staging2-api.wedotalent.cc"
  config.hosts << "ai.wedotalent.cc"

  # Aceitar qualquer domínio ngrok em desenvolvimento
  config.hosts << /.*\.ngrok-free\.app/
  config.hosts << /.*\.ngrok\.io/
  config.hosts << /.*\.ngrok\.app/
  config.hosts << /.*\.trycloudflare\.com/

  ENV.fetch("RAILS_ADDITIONAL_HOSTS", "").split(",").map(&:strip).reject(&:empty?).each do |host|
    config.hosts << host
  end

  config.web_console.permissions = [ "127.0.0.1", "::1", "172.16.0.0/12", "192.168.0.0/16", "10.0.0.0/8" ] if defined?(WebConsole)
end
