"""Tool: get_wsi_feedback — reads deterministic WSI scorer output, applies FairnessGuard.

The feedback is NOT generated by the LLM. It is the pre-computed output of
_score_response_deterministic() (Bloom taxonomy + Dreyfus model + 5 dimensions).
FairnessGuard runs before returning to the agent to block biased language.
LGPD Art. 20 disclosure is appended by the agent, not this tool.
"""
import logging
from typing import Any

from lia_agents_core.tool_adapter import ToolDefinition
from app.shared.compliance.fairness_guard import FairnessGuard
from app.shared.tool_handler import tool_handler

logger = logging.getLogger(__name__)

_fairness_guard = FairnessGuard()

# Fields NEVER returned to candidate — internal scoring only
_FORBIDDEN_FIELDS = frozenset([
    "wsi_final_score", "score", "bloom_level", "dreyfus_level",
    "red_flags", "justification", "classification", "approved",
])


@tool_handler("candidate_self_service", require_company=True)
async def _get_wsi_feedback(**kwargs: Any) -> dict[str, Any]:
    candidate_id: str = kwargs.get("candidate_id", "")
    vacancy_id: str = kwargs.get("vacancy_id", "")
    company_id: str = kwargs.get("company_id", "")

    if not candidate_id or not vacancy_id:
        return {"success": False, "message": "candidate_id e vacancy_id são obrigatórios."}

    try:
        from app.shared.rails_client import rails_get

        # Check tenant policy: is feedback enabled for this company?
        policy = await rails_get(
            "/v1/candidate-portal/policy",
            params={"company_id": company_id},
            company_id=company_id,
        )
        if not policy.get("show_feedback", False):
            return {
                "success": True,
                "data": {"feedback_available": False},
                "message": "Esta empresa optou por não disponibilizar feedback detalhado.",
            }

        data = await rails_get(
            "/v1/candidate-portal/wsi-feedback",
            params={"candidate_id": candidate_id, "vacancy_id": vacancy_id},
            company_id=company_id,
        )

        # Strip forbidden fields (scores, classifications)
        safe_data = {k: v for k, v in data.items() if k not in _FORBIDDEN_FIELDS}

        # FairnessGuard: run on all text fields before returning to agent
        for key in ("clareza_comunicacao", "conhecimento_tecnico", "raciocinio",
                    "competencias_comportamentais", "alinhamento_posicao"):
            text = safe_data.get(key, "")
            if text:
                guard_result = await _fairness_guard.check(text)
                if guard_result.get("blocked"):
                    safe_data[key] = "Informação não disponível para esta dimensão."
                    logger.warning(
                        "[CSS Tool] FairnessGuard blocked field=%s candidate_id=%s",
                        key, candidate_id,
                    )
                    safe_data["_fairness_triggered"] = True

        # Add LGPD disclosure info from policy
        safe_data["revisao_humana_disponivel"] = True
        safe_data["contato_revisao"] = policy.get("feedback_contact", "o recrutador responsável")

        logger.info(
            "[CSS Tool] get_wsi_feedback candidate_id=%s fairness_triggered=%s",
            candidate_id, safe_data.get("_fairness_triggered", False),
        )
        return {"success": True, "data": safe_data}

    except Exception as exc:
        logger.error("[CSS Tool] get_wsi_feedback error: %s", exc)
        return {"success": False, "message": "Feedback não disponível no momento."}


get_wsi_feedback = ToolDefinition(
    name="get_wsi_feedback",
    description=(
        "Retorna o feedback estruturado da triagem WSI (5 dimensões em linguagem natural). "
        "Disponível apenas se a empresa habilitou esta funcionalidade. "
        "Use quando o candidato pedir feedback, resultado ou avaliação. "
        "Nunca inclui scores, classificações ou red_flags."
    ),
    parameters={
        "type": "object",
        "properties": {
            "candidate_id": {"type": "string", "description": "ID do candidato (do token JWT)"},
            "vacancy_id": {"type": "string", "description": "ID da vaga (do token JWT)"},
        },
        "required": ["candidate_id", "vacancy_id"],
    },
    function=_get_wsi_feedback,
)
