"""Recruiter Assistant Domain - Action definitions."""
from app.domains.base import DomainAction

RECRUITER_ASSISTANT_ACTIONS = [
    DomainAction(
        action_id="daily_briefing",
        name="Briefing Diário",
        description="Gerar briefing diário para o recrutador",
        requires_confirmation=False,
        tags=["briefing", "daily", "delegate_to_agent"],
    ),
    DomainAction(
        action_id="end_of_day_summary",
        name="Resumo do Dia",
        description="Gerar resumo de fim de dia",
        requires_confirmation=False,
        tags=["summary", "daily", "delegate_to_agent"],
    ),
    DomainAction(
        action_id="quick_question",
        name="Pergunta Rápida",
        description="Responder pergunta rápida do recrutador",
        requires_confirmation=False,
        tags=["question", "quick", "delegate_to_agent"],
    ),
    DomainAction(
        action_id="plan_day",
        name="Planejar Dia",
        description="Ajudar o recrutador a planejar o dia",
        requires_confirmation=False,
        tags=["planning", "productivity", "delegate_to_agent"],
    ),
    DomainAction(
        action_id="pipeline_health",
        name="Saúde do Pipeline",
        description="Analisar a saúde do pipeline de recrutamento",
        requires_confirmation=False,
        tags=["pipeline", "health", "analysis"],
    ),
    DomainAction(
        action_id="stale_candidates",
        name="Candidatos Parados",
        description="Identificar candidatos inativos/parados no pipeline",
        requires_confirmation=False,
        tags=["candidates", "stale", "pipeline"],
    ),
    DomainAction(
        action_id="move_candidate",
        name="Mover Candidato",
        description="Mover candidato para uma etapa diferente do pipeline",
        requires_confirmation=True,
        tags=["candidate", "move", "stage"],
    ),
    DomainAction(
        action_id="suggest_action",
        name="Sugerir Ação",
        description="Sugerir a próxima melhor ação para um candidato via IA",
        requires_confirmation=False,
        tags=["suggestion", "action", "ai", "delegate_to_agent"],
    ),
    DomainAction(
        action_id="search_context",
        name="Buscar Contexto",
        description="Buscar no histórico de conversas por contexto relevante",
        requires_confirmation=False,
        tags=["search", "context", "history"],
    ),
    DomainAction(
        action_id="save_memory",
        name="Salvar Memória",
        description="Salvar informação importante na memória persistente",
        requires_confirmation=False,
        tags=["memory", "save", "persistent"],
    ),
    DomainAction(
        action_id="recall_memory",
        name="Recuperar Memória",
        description="Recuperar informação da memória persistente",
        requires_confirmation=False,
        tags=["memory", "recall", "search"],
    ),
    DomainAction(
        action_id="conversation_summary",
        name="Resumo da Conversa",
        description="Gerar resumo da conversa atual",
        requires_confirmation=False,
        tags=["conversation", "summary"],
    ),
    DomainAction(
        action_id="kanban_analysis",
        name="Análise do Kanban",
        description="Análise por IA do quadro Kanban de recrutamento",
        requires_confirmation=False,
        tags=["kanban", "analysis", "ai"],
    ),
    DomainAction(
        action_id="calibrate_profile",
        name="Calibrar Perfil",
        description="Calibrar o perfil ideal de candidato com feedback",
        requires_confirmation=False,
        tags=["calibration", "profile", "delegate_to_agent"],
    ),
    DomainAction(
        action_id="send_notification",
        name="Enviar Notificação",
        description="Enviar notificação proativa para o recrutador",
        requires_confirmation=False,
        tags=["notification", "proactive"],
    ),
    DomainAction(
        action_id="track_goals",
        name="Acompanhar Metas",
        description="Acompanhar progresso das metas de recrutamento",
        requires_confirmation=False,
        tags=["goals", "tracking", "metrics"],
    ),
    DomainAction(
        action_id="generate_insights",
        name="Gerar Insights",
        description="Gerar insights proativos de busca e recrutamento",
        requires_confirmation=False,
        tags=["insights", "proactive", "delegate_to_agent"],
    ),
    DomainAction(
        action_id="compare_candidates",
        name="Comparar Candidatos",
        description="Comparação rápida entre candidatos",
        requires_confirmation=False,
        tags=["candidates", "comparison", "delegate_to_agent"],
    ),
    DomainAction(
        action_id="stage_recommendation",
        name="Recomendar Etapa",
        description="Recomendar próxima etapa para candidato",
        requires_confirmation=False,
        tags=["stage", "recommendation", "delegate_to_agent"],
    ),
    DomainAction(
        action_id="proactive_alerts",
        name="Alertas Proativos",
        description="Ver alertas proativos do pipeline (SLA, candidatos parados, gargalos)",
        requires_confirmation=False,
        tags=["alerts", "proactive", "monitoring"],
    ),
    DomainAction(
        action_id="stakeholder_notify",
        name="Notificar Stakeholders",
        description="Detectar decisões pendentes e notificar hiring managers com escalação",
        requires_confirmation=False,
        tags=["stakeholder", "notification", "escalation", "hiring_manager"],
    ),
    DomainAction(
        action_id="learning_insights",
        name="Insights de Aprendizado",
        description="Ver o que a LIA aprendeu com contratações anteriores",
        requires_confirmation=False,
        tags=["learning", "insights", "outcomes", "feedback"],
    ),
    DomainAction(
        action_id="help_command",
        name="Ajuda",
        description="Mostrar comandos e funcionalidades disponíveis",
        requires_confirmation=False,
        tags=["help", "commands"],
    ),
]
