"""Analytics & Reporting Domain - Action definitions."""
from app.domains.base import DomainAction

ANALYTICS_ACTIONS = [
    DomainAction(
        action_id="generate_kpi_report",
        name="Gerar Relatório de KPIs",
        description="Gerar relatórios de KPIs para métricas de recrutamento",
        required_params=["job_id"],
        optional_params=["period", "format"],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="analyze_funnel",
        name="Analisar Funil de Conversão",
        description="Analisar métricas do funil de conversão de recrutamento",
        required_params=["job_id"],
        optional_params=["period", "stages"],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="job_health_check",
        name="Verificar Saúde da Vaga",
        description="Verificar indicadores de saúde da vaga de emprego",
        required_params=["job_id"],
        optional_params=[],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="detect_anomalies",
        name="Detectar Anomalias",
        description="Detectar anomalias nos dados de recrutamento",
        required_params=[],
        optional_params=["job_id", "metric", "threshold"],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="compare_periods",
        name="Comparar Períodos",
        description="Comparar métricas entre períodos de tempo diferentes",
        required_params=["period_a", "period_b"],
        optional_params=["job_id", "metrics"],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="forecast",
        name="Previsão de Métricas",
        description="Prever métricas e tendências de recrutamento",
        required_params=[],
        optional_params=["job_id", "metric", "horizon_days"],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="suggest_strategy",
        name="Sugerir Estratégia",
        description="Sugestões de estratégia baseadas em dados com IA",
        required_params=["job_id"],
        optional_params=["context", "goals"],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="answer_data_question",
        name="Responder Pergunta sobre Dados",
        description="Responder perguntas sobre dados e analytics",
        required_params=["question"],
        optional_params=["job_id", "context"],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="get_job_insights",
        name="Obter Insights da Vaga",
        description="Obter benchmarks salariais, competências e vagas similares",
        required_params=["job_id"],
        optional_params=["include_salary", "include_skills", "include_similar"],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="generate_job_report",
        name="Gerar Relatório da Vaga",
        description="Gerar relatório da vaga em PDF/Excel",
        required_params=["job_id"],
        optional_params=["format", "sections"],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="generate_candidate_report",
        name="Gerar Relatório de Candidato",
        description="Gerar relatório comparativo de candidatos",
        required_params=["candidate_ids"],
        optional_params=["job_id", "format", "criteria"],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="get_search_analytics",
        name="Analytics de Busca",
        description="Analytics de desempenho de busca de candidatos",
        required_params=[],
        optional_params=["period", "search_type"],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="get_wizard_analytics",
        name="Analytics do Wizard",
        description="Analytics de uso do wizard de criação de vagas",
        required_params=[],
        optional_params=["period"],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="predict_hiring_probability",
        name="Prever Probabilidade de Contratação",
        description="Previsão com IA para probabilidade de sucesso na contratação",
        required_params=["job_id"],
        optional_params=["candidate_id"],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="predict_time_to_fill",
        name="Prever Tempo de Preenchimento",
        description="Estimar tempo para preencher uma posição",
        required_params=["job_id"],
        optional_params=[],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="predict_dropout_risk",
        name="Prever Risco de Desistência",
        description="Prever risco de desistência do candidato",
        required_params=["candidate_id"],
        optional_params=["job_id"],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="get_dashboard_data",
        name="Dados do Dashboard",
        description="Obter indicadores estratégicos e dados do dashboard",
        required_params=[],
        optional_params=["period", "metrics"],
        requires_confirmation=False,
    ),
    DomainAction(
        action_id="get_agent_monitoring",
        name="Monitoramento de Agentes",
        description="Monitorar desempenho dos agentes de IA",
        required_params=[],
        optional_params=["agent_type", "period"],
        requires_confirmation=False,
    ),
]
