// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/animacoes-lia/BuscaAtual.tsx": () => import("../components/mockups/animacoes-lia/BuscaAtual.tsx"),
  "./components/mockups/animacoes-lia/BuscaEnhanced.tsx": () => import("../components/mockups/animacoes-lia/BuscaEnhanced.tsx"),
  "./components/mockups/animacoes-lia/FrasesAtual.tsx": () => import("../components/mockups/animacoes-lia/FrasesAtual.tsx"),
  "./components/mockups/animacoes-lia/FrasesTyping.tsx": () => import("../components/mockups/animacoes-lia/FrasesTyping.tsx"),
  "./components/mockups/chat-usability/AccessibleReadable.tsx": () => import("../components/mockups/chat-usability/AccessibleReadable.tsx"),
  "./components/mockups/chat-usability/ClearHierarchy.tsx": () => import("../components/mockups/chat-usability/ClearHierarchy.tsx"),
  "./components/mockups/chat-usability/StrongAffordance.tsx": () => import("../components/mockups/chat-usability/StrongAffordance.tsx"),
  "./components/mockups/chat-welcome-polish/ElevatedCards.tsx": () => import("../components/mockups/chat-welcome-polish/ElevatedCards.tsx"),
  "./components/mockups/chat-welcome-polish/TighterRhythm.tsx": () => import("../components/mockups/chat-welcome-polish/TighterRhythm.tsx"),
  "./components/mockups/funil-elevenlabs/FunilElevenLabs.tsx": () => import("../components/mockups/funil-elevenlabs/FunilElevenLabs.tsx"),
  "./components/mockups/jd-scores/JDScoresComparison.tsx": () => import("../components/mockups/jd-scores/JDScoresComparison.tsx"),
  "./components/mockups/funil-busca/FunilBusca.tsx": () => import("../components/mockups/funil-busca/FunilBusca.tsx"),
  "./components/mockups/triagem-flow/ChatScreen.tsx": () => import("../components/mockups/triagem-flow/ChatScreen.tsx"),
  "./components/mockups/triagem-flow/CompletionScreen.tsx": () => import("../components/mockups/triagem-flow/CompletionScreen.tsx"),
  "./components/mockups/triagem-flow/ConfirmationScreen.tsx": () => import("../components/mockups/triagem-flow/ConfirmationScreen.tsx"),
  "./components/mockups/triagem-flow/WelcomeScreen.tsx": () => import("../components/mockups/triagem-flow/WelcomeScreen.tsx"),
  "./components/mockups/triagem-modal/TriagemModalWithEligibility.tsx": () => import("../components/mockups/triagem-modal/TriagemModalWithEligibility.tsx"),
  "./components/mockups/weekly-digest/BellNotification.tsx": () => import("../components/mockups/weekly-digest/BellNotification.tsx"),
  "./components/mockups/weekly-digest/ChatFlutuante.tsx": () => import("../components/mockups/weekly-digest/ChatFlutuante.tsx"),
  "./components/mockups/weekly-digest/TeamsAdaptiveCard.tsx": () => import("../components/mockups/weekly-digest/TeamsAdaptiveCard.tsx"),
  "./components/mockups/wsi-report/Tab1Respostas.tsx": () => import("../components/mockups/wsi-report/Tab1Respostas.tsx"),
  "./components/mockups/wsi-report/Tab2Aprovado.tsx": () => import("../components/mockups/wsi-report/Tab2Aprovado.tsx"),
  "./components/mockups/wsi-report/Tab2Pendente.tsx": () => import("../components/mockups/wsi-report/Tab2Pendente.tsx")
};
