"""
Offer Portal — public endpoints for candidate-facing offer acceptance/decline.

NO JWT authentication — authenticated solely via unique candidate_token.
Token is generated by offer_service.mark_sent and stored in offer_proposals.

Security:
  - Token is UUID4 (cryptographically random, 128-bit entropy)
  - Partial token exposure via unique index (no brute-force surface at scale)
  - Rate limiting via CANDIDATE_PORTAL_RATE_LIMIT (default: 10 req/min/IP)
  - No PII in response that isn't already known to the token holder

Endpoints:
  GET  /portal/proposta/{token}              — view offer details
  POST /portal/proposta/{token}/responder    — accept or decline
  POST /portal/proposta/{token}/visualizado  — mark as viewed (pixel/load event)
"""
from __future__ import annotations

import logging
from datetime import datetime
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import Field
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database import get_db
from app.shared.types import WeDoBaseModel

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/portal/proposta", tags=["Offer Portal"])

_MAX_RESPONSE_NOTES_LEN = 2000


# ── Request/Response schemas ──────────────────────────────────────────────────

class OfferPortalView(WeDoBaseModel):
    offer_id: str
    candidate_name: str
    job_title: str
    department: str
    company_name: str
    salary_formatted: str
    currency: str
    start_date: str | None
    response_deadline: str | None
    benefits: list[dict]
    letter_html: str | None
    status: str
    current_round: int
    # Portal meta
    offer_link: str | None = None
    viewed_at: str | None = None


class OfferRespostaRequest(WeDoBaseModel):
    acao: str = Field(
        ...,
        description="'aceitar', 'recusar' ou 'contraproposta' (N3 — requer negotiation_enabled)",
        pattern="^(aceitar|recusar|contraproposta)$",
    )
    notas: str | None = Field(
        None,
        max_length=_MAX_RESPONSE_NOTES_LEN,
        description="Observações livres do candidato (opcional)",
    )
    counter_salary: float | None = Field(
        None,
        gt=0,
        le=9_999_999,
        description="Valor salarial proposto pelo candidato (obrigatório quando acao='contraproposta')",
    )

    @classmethod
    def model_post_init(cls, __context) -> None:
        pass  # WeDoBaseModel compat

    def validate_counter(self) -> None:
        if self.acao == "contraproposta" and self.counter_salary is None:
            raise ValueError("counter_salary é obrigatório quando acao='contraproposta'")


class OfferRespostaResponse(WeDoBaseModel):
    status: str
    mensagem: str
    next_steps: str | None = None


# ── Helpers ───────────────────────────────────────────────────────────────────

async def _get_offer_by_token(token: str, db: AsyncSession):
    """Lookup OfferProposal by candidate_token. Raises 404 if not found."""
    from uuid import UUID as _UUID
    try:
        token_uuid = _UUID(token)
    except ValueError:
        raise HTTPException(status_code=404, detail="Link de proposta inválido.")

    from app.domains.offer.repositories.offer_repository import OfferRepository
    offer = await OfferRepository(db).get_by_candidate_token(token_uuid)
    if not offer:
        raise HTTPException(status_code=404, detail="Proposta não encontrada ou link expirado.")
    return offer


def _format_salary(salary, currency: str = "BRL") -> str:
    if salary is None:
        return "A combinar"
    try:
        value = float(salary)
        if currency == "BRL":
            return f"R$ {value:,.2f}".replace(",", "X").replace(".", ",").replace("X", ".")
        return f"{currency} {value:,.2f}"
    except (TypeError, ValueError):
        return str(salary)


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.get("/{token}", response_model=OfferPortalView, summary="Visualizar proposta (público)")
async def view_offer(
    token: str,
    db: AsyncSession = Depends(get_db),
):
    """Candidato abre o link recebido por email — retorna detalhes da proposta.

    Não requer autenticação. Token único por proposta (candidate_token).
    """
    offer = await _get_offer_by_token(token, db)

    # Block viewing proposals that weren't sent yet
    if offer.status == "draft":
        raise HTTPException(status_code=403, detail="Esta proposta ainda não foi enviada.")

    job = offer.job_data_snapshot or {}
    candidate = offer.candidate_data_snapshot or {}

    return OfferPortalView(
        offer_id=str(offer.id),
        candidate_name=candidate.get("name") or offer.candidate_name or "",
        job_title=job.get("title") or offer.job_title or "",
        department=job.get("department", ""),
        company_name=job.get("company_name", "WeDOTalent"),
        salary_formatted=_format_salary(offer.salary, offer.currency or "BRL"),
        currency=offer.currency or "BRL",
        start_date=offer.start_date.strftime("%d/%m/%Y") if offer.start_date else None,
        response_deadline=offer.response_deadline.strftime("%d/%m/%Y %H:%M")
        if offer.response_deadline
        else None,
        benefits=list(offer.benefits or []),
        letter_html=offer.letter_html,
        status=offer.status,
        current_round=int(offer.current_round or 0),
        offer_link=offer.acceptance_url,
        viewed_at=offer.candidate_viewed_at.isoformat() if offer.candidate_viewed_at else None,
    )


@router.post(
    "/{token}/visualizado",
    status_code=204,
    summary="Marcar proposta como visualizada (público)",
)
async def mark_viewed(
    token: str,
    db: AsyncSession = Depends(get_db),
):
    """Chamado pelo FE quando o candidato carrega a página do portal.

    Idempotente — não sobrescreve candidate_viewed_at se já preenchido.
    """
    offer = await _get_offer_by_token(token, db)

    if offer.status == "draft":
        return  # silently ignore — not yet sent

    if offer.candidate_viewed_at is None:
        from app.domains.offer.repositories.offer_repository import OfferRepository
        from app.domains.offer.repositories.offer_negotiation_event_repository import (
            OfferNegotiationEventRepository,
        )
        offer.candidate_viewed_at = datetime.utcnow()
        await OfferRepository(db).update(offer)
        await OfferNegotiationEventRepository(db).create(
            offer_id=offer.id,
            company_id=offer.company_id,
            event_type="viewed",
            actor="candidate",
            round_number=int(offer.current_round or 0),
            notes="Candidato visualizou a proposta pelo portal",
            fairness_snapshot={"check": "portal_view"},
        )
        await db.flush()

        # Notify recruiter via Teams (fail-soft)
        try:
            from app.domains.communication.services.teams_service import TeamsService
            await TeamsService().on_offer_viewed(
                offer_id=str(offer.id),
                company_id=offer.company_id,
                candidate_name=offer.candidate_name,
            )
        except Exception as _e:
            logger.debug("[offer_portal] Teams view notification skipped: %s", _e)


@router.post(
    "/{token}/responder",
    response_model=OfferRespostaResponse,
    summary="Candidato aceita ou recusa proposta (público)",
)
async def responder_proposta(
    token: str,
    body: OfferRespostaRequest,
    db: AsyncSession = Depends(get_db),
):
    """Candidato submete decisão pelo portal.

    Aceitar → status = accepted.
    Recusar → status = declined.
    Ambos registram evento de negociação + notificam recrutador via Teams.
    LGPD: notas do candidato gravadas em candidate_response_notes (dados voluntários).
    """
    offer = await _get_offer_by_token(token, db)

    # Gate: só permite resposta a propostas enviadas e ainda pendentes
    if offer.status not in ("sent", "viewed"):
        raise HTTPException(
            status_code=409,
            detail=f"Esta proposta não está mais aguardando resposta (status: {offer.status}).",
        )

    from app.domains.offer.repositories.offer_repository import OfferRepository
    from app.domains.offer.repositories.offer_negotiation_event_repository import (
        OfferNegotiationEventRepository,
    )
    from app.shared.services.audit_service import audit_service

    now = datetime.utcnow()

    if body.acao == "aceitar":
        offer.status = "accepted"
        offer.accepted_at = now
        offer.candidate_responded_at = now
        if body.notas:
            offer.candidate_response_notes = body.notas[:_MAX_RESPONSE_NOTES_LEN]
        event_type = "accepted"
        mensagem = "Proposta aceita com sucesso! O recrutador será notificado."
        next_steps = "Você receberá mais instruções sobre o processo de admissão em breve."
    elif body.acao == "contraproposta":
        # N3 — Agente Negociador: valida negotiation_enabled + rounds limit
        body.validate_counter()
        from app.domains.repositories.hiring_policy_repository import HiringPolicyRepository
        policy = await HiringPolicyRepository(db).get_by_company(offer.company_id)
        offer_rules = (policy.offer_rules if policy else None) or {}
        if not offer_rules.get("negotiation_enabled", False):
            raise HTTPException(
                status_code=403,
                detail="Negociação autônoma não está habilitada para esta proposta. Entre em contato com o recrutador.",
            )
        max_rounds = int(offer_rules.get("counter_proposal_max_rounds", 2))
        current_round = int(offer.current_round or 0)
        if current_round >= max_rounds:
            # Encerramento automático após limite de rodadas
            offer.status = "declined"
            offer.declined_at = now
            offer.candidate_responded_at = now
            offer.decline_reason = f"Limite de {max_rounds} rodada(s) de negociação atingido."
            event_type = "declined"
            mensagem = (
                f"Infelizmente atingimos o limite de {max_rounds} rodada(s) de negociação. "
                "O recrutador será notificado e entrará em contato."
            )
            next_steps = None
        else:
            offer.status = "counter_proposed"
            offer.current_round = current_round + 1
            import json as _json
            rounds = list(offer.rounds or [])
            rounds.append({
                "round": current_round + 1,
                "actor": "candidate",
                "salary_counter": body.counter_salary,
                "notes": body.notas,
                "at": now.isoformat(),
            })
            offer.rounds = rounds
            event_type = "counter_proposed"
            # HITL threshold check — 3.6
            original_salary = float(offer.salary or 0)
            threshold_pct = float(offer_rules.get("negotiation_hitl_threshold_pct", 10.0))
            if original_salary > 0:
                delta_pct = abs(body.counter_salary - original_salary) / original_salary * 100
                within_threshold = delta_pct <= threshold_pct
            else:
                within_threshold = False  # fail-closed sem salário base
            mensagem = (
                "Sua contraproposta foi registrada! O recrutador ou a IA de negociação "
                "irá analisar e retornar em breve."
            )
            next_steps = "Aguarde o contato do recrutador ou da LIA com a resposta."
            # Notificar via Teams para HITL (fail-soft)
            try:
                from app.domains.communication.services.teams_service import TeamsService
                await TeamsService().on_offer_escalation_tool(
                    offer_id=str(offer.id),
                    pending_id=None,
                    reason=(
                        f"Contraproposta recebida (rodada {current_round + 1}/{max_rounds}). "
                        f"Salário proposto: R$ {body.counter_salary:,.2f}. "
                        f"{'Auto-aprovável (dentro de {:.0f}%)'.format(threshold_pct) if within_threshold else 'Requer aprovação HITL (acima do threshold de {:.0f}%)'.format(threshold_pct)}"
                    ),
                    company_id=offer.company_id,
                    counter_salary=body.counter_salary,
                )
            except Exception as _e:
                logger.debug("[offer_portal] Teams counter-proposal notify skipped: %s", _e)
    else:
        offer.status = "declined"
        offer.declined_at = now
        offer.candidate_responded_at = now
        if body.notas:
            offer.candidate_response_notes = body.notas[:_MAX_RESPONSE_NOTES_LEN]
            offer.decline_reason = body.notas[:500]
        event_type = "declined"
        mensagem = "Resposta registrada. O recrutador foi notificado."
        next_steps = None

    await OfferRepository(db).update(offer)
    await OfferNegotiationEventRepository(db).create(
        offer_id=offer.id,
        company_id=offer.company_id,
        event_type=event_type,
        actor="candidate",
        round_number=int(offer.current_round or 0),
        notes=body.notas,
        salary_counter=getattr(body, "counter_salary", None),
        salary_proposed=float(offer.salary or 0) if offer.salary else None,
        fairness_snapshot={"check": "portal_response", "acao": body.acao},
    )
    await db.flush()

    # Audit LGPD (Art. 7 II — legítimo interesse processual)
    try:
        await audit_service.log_decision(
            company_id=offer.company_id,
            agent="offer_portal",
            action=f"candidate_{event_type}",
            input_summary=f"candidate_token={token[:8]}...",
            output_summary=f"offer={offer.id} acao={body.acao}",
            metadata={"offer_id": str(offer.id), "round": int(offer.current_round or 0)},
            reasoning=[f"candidate submitted {body.acao} via portal"],
        )
    except Exception as _audit_e:
        logger.warning("[offer_portal] audit log failed: %s", _audit_e)

    # Notify recruiter via Teams (fail-soft)
    try:
        from app.domains.communication.services.teams_service import TeamsService
        await TeamsService().on_offer_responded(
            offer_id=str(offer.id),
            company_id=offer.company_id,
            candidate_name=offer.candidate_name,
            acao=body.acao,
            notas=body.notas,
        )
    except Exception as _e:
        logger.debug("[offer_portal] Teams response notification skipped: %s", _e)

    return OfferRespostaResponse(
        status=offer.status,
        mensagem=mensagem,
        next_steps=next_steps,
    )
