"""Automation & Tasks Domain - Action definitions."""
from app.domains.base import DomainAction

AUTOMATION_ACTIONS = [
    DomainAction(
        action_id="create_task",
        name="Criar Tarefa",
        description="Cria nova tarefa planejada no sistema de automação com título, descrição, agente responsável e prazo. Aciona quando recruiter ou orquestrador precisa registrar uma atividade para execução futura ou delegação.",
        requires_confirmation=False,
        examples=('cria tarefa para o time', 'adiciona lembrete de follow-up'),
    ),
    DomainAction(
        action_id="list_tasks",
        name="Listar Tarefas",
        description="Lista tarefas ativas e seus status (pendente, em execução, concluída, bloqueada) para o objetivo atual. Aciona quando recruiter quer ver o progresso do pipeline de automação ou tarefas pendentes.",
        requires_confirmation=False,
        examples=('lista minhas tarefas pendentes', 'mostra tasks do dia'),
    ),
    DomainAction(
        action_id="complete_task",
        name="Concluir Tarefa",
        description="Marca tarefa como concluída registrando o resultado e liberando tarefas dependentes bloqueadas. Requer confirmação. Aciona ao finalizar execução de uma subtarefa no fluxo de automação.",
        requires_confirmation=True,
        examples=('concluir tarefa', 'quero concluir tarefa'),
    ),
    DomainAction(
        action_id="cancel_task",
        name="Cancelar Tarefa",
        description="Cancela tarefa pendente com motivo, liberando recursos alocados e notificando tarefas dependentes. Requer confirmação. Aciona quando tarefa não é mais necessária ou contexto mudou.",
        requires_confirmation=True,
        examples=('cancela tarefa', 'desiste de tarefa'),
    ),
    DomainAction(
        action_id="decompose_task",
        name="Decompor Tarefa",
        description="Decompõe tarefa complexa em subtarefas menores via IA, atribuindo agente responsável, prioridade e dependências para cada uma. Aciona ao receber objetivo de alto nível que requer orquestração multi-agente.",
        requires_confirmation=False,
        examples=('decompor tarefa', 'quero decompor tarefa'),
    ),
    DomainAction(
        action_id="plan_execution",
        name="Planejar Execução",
        description="Cria plano de execução validado com níveis paralelos e mapa de dependências para um conjunto de tarefas. Aciona após decomposição para preparar pipeline de execução autônoma.",
        requires_confirmation=False,
        examples=('planejar execução', 'quero planejar execução'),
    ),
    DomainAction(
        action_id="get_next_tasks",
        name="Próximas Tarefas",
        description="Obtém próximas tarefas prontas para execução (todas as dependências concluídas) filtradas por agente e objetivo. Aciona no loop de execução autônoma para buscar trabalho disponível.",
        requires_confirmation=False,
        examples=('mostra tarefa', 'quero ver tarefa'),
    ),
    DomainAction(
        action_id="create_automation",
        name="Criar Automação",
        description="Cria nova regra de automação que dispara ações automaticamente baseado em eventos do pipeline (mudança de etapa, SLA vencido, etc.). Requer confirmação. Aciona quando recruiter quer automatizar tarefa recorrente.",
        requires_confirmation=True,
        examples=('cria automação', 'quero um automação'),
    ),
    DomainAction(
        action_id="list_automations",
        name="Listar Automações",
        description="Lista regras de automação configuradas pela empresa com status ativo/inativo e métricas de execução. Aciona para gestão das automações existentes ou verificar o que está rodando.",
        requires_confirmation=False,
        examples=('lista automação', 'mostra automação ativas'),
    ),
    DomainAction(
        action_id="enable_automation",
        name="Ativar Automação",
        description="Ativa regra de automação previamente criada para que comece a disparar ações automaticamente. Requer confirmação. Aciona quando automação está pronta para produção.",
        requires_confirmation=True,
        examples=('ativar automação', 'quero ativar automação'),
    ),
    DomainAction(
        action_id="disable_automation",
        name="Desativar Automação",
        description="Desativa regra de automação parando execuções automáticas sem excluí-la. Requer confirmação. Aciona para pausar automação temporariamente ou quando está causando comportamento indesejado.",
        requires_confirmation=True,
        examples=('desativar automação', 'quero desativar automação'),
    ),
    DomainAction(
        action_id="trigger_automation",
        name="Disparar Automação",
        description="Dispara manualmente uma automação configurada para execução imediata fora do gatilho automático. Requer confirmação. Aciona para teste de automação ou execução manual pontual.",
        requires_confirmation=True,
        examples=('dispara automação', 'ativa automação'),
    ),
    DomainAction(
        action_id="view_automation_log",
        name="Ver Log de Automação",
        description="Visualiza histórico de execuções de automações com timestamps, resultados e erros. Aciona para auditoria, debug de automações falhas ou compliance.",
        requires_confirmation=False,
        examples=('ver automação', 'mostra automação'),
    ),
    DomainAction(
        action_id="configure_stage_automation",
        name="Configurar Automação de Etapa",
        description="Configura automação de transição de etapa do pipeline (ex: ao aprovado em triagem → enviar convite de entrevista). Requer confirmação. Aciona na configuração de fluxos automáticos de pipeline.",
        requires_confirmation=True,
        examples=('configura automação', 'define automação'),
    ),
    DomainAction(
        action_id="predict_substatus",
        name="Prever Sub-status",
        description="Prevê via IA o próximo sub-status mais provável para um candidato baseado no histórico e comportamento. Aciona para sugestões proativas de próxima ação ou alertas de risco de perda.",
        requires_confirmation=False,
        examples=('prever sub-status', 'quero prever sub-status'),
    ),
    DomainAction(
        action_id="check_proactive_alerts",
        name="Verificar Alertas Proativos",
        description="Verifica alertas proativos ativos para o recrutador: SLAs vencidos, candidatos parados, vagas sem movimento. Aciona no briefing diário ou quando recruiter pede 'o que precisa de atenção?'.",
        requires_confirmation=False,
        examples=('vê alertas proativos', 'tem novos alertas?'),
    ),
    DomainAction(
        action_id="configure_alert",
        name="Configurar Alerta",
        description="Configura regras de alertas proativos com threshold, canal de notificação e frequência. Requer confirmação. Aciona quando recruiter quer personalizar quais alertas receber.",
        requires_confirmation=True,
        examples=('configura novo alerta', 'cria alerta pra vaga parada'),
    ),
    DomainAction(
        action_id="schedule_recurring",
        name="Agendar Tarefa Recorrente",
        description="Agenda tarefa recorrente de automação com frequência (diária, semanal, mensal). Requer confirmação. Aciona para criar relatórios automáticos ou verificações periódicas.",
        requires_confirmation=True,
        examples=('agenda task recorrente', 'marca lembrete semanal'),
    ),
    DomainAction(
        action_id="view_task_dependencies",
        name="Ver Dependências",
        description="Visualiza o grafo de dependências das tarefas planejadas mostrando ordem de execução e bloqueios. Aciona para debug de pipeline travado ou para entender sequência de automação.",
        requires_confirmation=False,
        examples=('ver tarefa', 'mostra tarefa'),
    ),
    DomainAction(
        action_id="run_autonomous_check",
        name="Executar Verificação Autônoma",
        description="Executa verificação autônoma de background check de candidato via agente de IA. Requer confirmação. Aciona para validação de informações de candidatos finalistas.",
        requires_confirmation=True,
        examples=('roda agente', 'executa agente'),
    ),
]
