"""Communication Domain - Action definitions."""
from app.domains.base import DomainAction

COMMUNICATION_ACTIONS = [
    DomainAction(
        action_id="send_email",
        name="Enviar Email",
        description="Envia email individual personalizado para candidato ou stakeholder usando templates ou texto livre. Requer confirmação. Aciona quando recruiter pede para enviar email, comunicar resultado ou fazer follow-up.",
        requires_confirmation=True,
        examples=('envia email pra Maria confirmando entrevista', 'manda um feedback pro candidato'),
    ),
    DomainAction(
        action_id="send_bulk_email",
        name="Enviar Email em Massa",
        description="Envia email em massa para múltiplos destinatários simultaneamente usando template selecionado com personalização por candidato. Requer confirmação. Aciona para comunicações em lote como rejeições ou avanços de processo.",
        requires_confirmation=True,
        examples=('envia email pra todos os reprovados', 'manda comunicação em massa'),
    ),
    DomainAction(
        action_id="send_candidate_report",
        name="Enviar Parecer ao Gestor",
        description="Envia relatório ou parecer completo do candidato para o gestor contratante com score WSI, pontos fortes e recomendação. Requer confirmação. Aciona ao avançar candidato para entrevista com hiring manager.",
        requires_confirmation=True,
        examples=('envia candidato', 'manda candidato'),
    ),
    DomainAction(
        action_id="send_progress_report",
        name="Relatório de Progresso",
        description="Envia relatório de andamento da vaga para stakeholders com métricas atuais, pipeline e próximos passos. Aciona para comunicação proativa com clientes ou quando gestor pede atualização de status.",
        requires_confirmation=False,
        examples=('envia relatório', 'manda relatório'),
    ),
    DomainAction(
        action_id="send_kpi_report",
        name="Relatório de KPIs",
        description="Envia relatório consolidado de KPIs de recrutamento para liderança ou cliente. Requer confirmação. Aciona em ciclos semanais/mensais de reporting ou quando solicitado por stakeholder.",
        requires_confirmation=True,
        examples=('envia KPIs', 'manda KPIs'),
    ),
    DomainAction(
        action_id="send_feedback",
        name="Enviar Feedback",
        description="Envia feedback personalizado ao candidato sobre o resultado do processo seletivo, respeitando LGPD. Requer confirmação. Aciona quando candidato é rejeitado e recruiter quer dar devolutiva de qualidade.",
        requires_confirmation=True,
        examples=('envia isso', 'manda isso'),
    ),
    DomainAction(
        action_id="create_template",
        name="Criar Template",
        description="Cria novo template de email reutilizável para comunicações padronizadas (convite, rejeição, oferta, etc.). Aciona quando recruiter precisa de novo template para situação não coberta pelos existentes.",
        requires_confirmation=False,
        examples=('cria template', 'quero um template'),
    ),
    DomainAction(
        action_id="edit_template",
        name="Editar Template",
        description="Edita template de email existente com novo conteúdo, assunto ou personalização. Aciona para atualizar comunicações desatualizadas ou personalizar templates padrão da empresa.",
        requires_confirmation=False,
        examples=('edita template', 'altera template'),
    ),
    DomainAction(
        action_id="list_templates",
        name="Listar Templates",
        description="Lista templates de email disponíveis filtrados por tipo (candidato, gestor, sistema) e status. Aciona quando recruiter quer escolher template para comunicação ou gerenciar biblioteca.",
        requires_confirmation=False,
        examples=('lista template', 'mostra template ativas'),
    ),
    DomainAction(
        action_id="preview_template",
        name="Visualizar Template",
        description="Pré-visualiza template de email com dados reais do candidato antes de enviar. Aciona antes de envio para verificar personalização e conteúdo estão corretos.",
        requires_confirmation=False,
        examples=('visualizar template', 'quero visualizar template'),
    ),
    DomainAction(
        action_id="notify_stakeholders",
        name="Notificar Stakeholders",
        description="Envia notificação para stakeholders (hiring manager, HRBP, cliente) sobre eventos críticos do processo seletivo. Requer confirmação. Aciona em marcos importantes: candidato aprovado, vaga fechada, oferta aceita.",
        requires_confirmation=True,
        examples=('notifica sobre isso', 'avisa sobre isso'),
    ),
    DomainAction(
        action_id="send_whatsapp",
        name="Enviar WhatsApp",
        description="Envia mensagem via WhatsApp para candidato usando template aprovado ou mensagem personalizada. Requer confirmação. Aciona quando candidato prefere WhatsApp ou resposta rápida é necessária.",
        requires_confirmation=True,
        examples=('manda whatsapp pro candidato confirmar horário',),
    ),
    DomainAction(
        action_id="send_teams_message",
        name="Enviar Mensagem Teams",
        description="Envia mensagem via Microsoft Teams para recruiter ou stakeholder interno. Requer confirmação. Aciona para notificações urgentes de equipe interna ou comunicações com hiring manager via Teams.",
        requires_confirmation=True,
        examples=('envia mensagem', 'manda mensagem'),
    ),
    DomainAction(
        action_id="send_sms",
        name="Enviar SMS",
        description="Envia SMS para candidato para lembretes ou confirmações urgentes. Requer confirmação. Aciona quando tempo de resposta é crítico ou candidato não respondeu ao email.",
        requires_confirmation=True,
        examples=('envia isso', 'manda isso'),
    ),
    DomainAction(
        action_id="get_communication_history",
        name="Histórico de Comunicação",
        description="Obtém histórico completo de comunicações com um candidato (emails, WhatsApp, SMS) com timestamps e status de entrega. Aciona para contexto antes de nova comunicação ou auditoria de interações.",
        requires_confirmation=False,
        examples=('mostra email', 'quero ver email'),
    ),
    DomainAction(
        action_id="send_screening_invite",
        name="Convite de Triagem",
        description="Envia convite para triagem WSI ao candidato com link e instruções. Requer confirmação. Aciona após aprovação de candidato na primeira etapa de análise de currículo.",
        requires_confirmation=True,
        examples=('envia WSI', 'manda WSI'),
    ),
    DomainAction(
        action_id="send_interview_invite",
        name="Convite de Entrevista",
        description="Envia convite de entrevista ao candidato com data, horário, formato e informações do entrevistador. Requer confirmação. Aciona após scheduling confirmar horário disponível.",
        requires_confirmation=True,
        examples=('envia entrevista', 'manda entrevista'),
    ),
    DomainAction(
        action_id="update_preferences",
        name="Preferências de Comunicação",
        description="Atualiza preferências de comunicação do candidato: canal preferido (email/WhatsApp/SMS) e horários. Aciona quando candidato solicita mudança de canal ou previamente à primeira comunicação.",
        requires_confirmation=False,
        examples=('atualiza email', 'muda email'),
    ),
    DomainAction(
        action_id="manage_webhook",
        name="Gerenciar Webhook",
        description="Configura e gerencia webhooks de comunicação para integração com ferramentas externas (Zapier, n8n, ATS). Aciona na configuração de integrações de comunicação automática.",
        requires_confirmation=False,
        examples=('gerenciar webhook', 'quero gerenciar webhook'),
    ),
    DomainAction(
        action_id="handle_data_request",
        name="Solicitação de Dados",
        description="Processa solicitação de dados pessoais ou exclusão (LGPD/GDPR) do candidato, registrando no audit trail. Requer confirmação. Aciona quando candidato exerce direito de acesso ou exclusão de dados.",
        requires_confirmation=True,
        examples=('solicitação de dados', 'quero solicitação de dados'),
    ),
]
