"use client"

import { useWizardPublishHandlers } from './useWizardPublishHandlers'
import { useWSIAndCalibrationHandlers } from './useWSIAndCalibrationHandlers'
import { useSendMessageHandlers } from './useSendMessageHandlers'
import { useStageValidationAndNavigation } from './useStageValidationAndNavigation'
import { useItemAndFileHandlers } from './useItemAndFileHandlers'

export function useExpandedChatSubHooks(ctx: Record<string, unknown>) {
  const {
    activeToolConfirmationMessageId, analytics, applyPendingDraft, approvedCandidates, awaitingCalibrationChoice,
    awaitingDraftChoice, awaitingFastTrackSelection, awaitingSensitiveFieldsConfirmation, awaitingStageAdvanceConfirmation, awaitingWSIRegenerationConfirmation,
    basicInfoFields, behavioralCompetencies, calibrationCandidates, calibrationComment, calibrationComplete,
    calibrationCriteria, calibrationSessionId, callEvaluationStep, clearWizardDraft, companyConfig,
    companyDefaultQuestions, companyMembersMap, compensationAnalysis, contextSwitching, conversationId,
    conversationMemory, currentCalibrationIndex, currentStage, currentStageConfig, currentStageIndex,
    customQuestionRequired, customQuestionText, customQuestionType, detectedCriteria, fastTrack,
    fastTrackAdjustments, fastTrackAppliedData, fastTrackSearchCriteria, fastTrackSearchResults, fastTrackSelectedVacancy,
    fastTrackState, fastTrackSuggestionsShownTracked, fetchDeduplicatedSkills, generateLLMContext, generatedJobDescription,
    hasAttemptedCalibrationGeneration, highlightField, inputEvaluationStageCompletionShown,
    inputRef, inputValue, interviewStages, isFullscreen, isGeneratingWSI,
    isInJobCreationMode, isJobCreationMode, isLoading, isLoadingCalibration, isOpen,
    isSearchingVacancies, isTypingEffect, jobConfig, learning,
    localCandidateCount, messages, newBenefitName,
    newBenefitValue, newCompetencyJustification, newCompetencyName, newSkillCategory, onClose,
    onJobCreated, pendingDraftData, postCalibrationComplete, preferredCandidateCount, publishedJobId,
    publishingPlatforms, rejectedCandidates, salaryInfo,
    saveWizardDraft, selectedSuggestedBehavioral, selectedSuggestedTechnical, setActiveToolConfirmationMessageId,
    setApprovedCandidates, setAwaitingCalibrationChoice, setAwaitingDraftChoice, setAwaitingFastTrackSelection, setAwaitingSensitiveFieldsConfirmation,
    setAwaitingStageAdvanceConfirmation, setAwaitingWSIRegenerationConfirmation, setBasicInfoFields, setBehavioralCompetencies, setCalibrationCandidates,
    setCalibrationComment, setCalibrationComplete, setCalibrationCriteria, setCalibrationSessionId, setCompensationAnalysis,
    setCompetencySuggestions, setConversationId, setCurrentCalibrationIndex, setCurrentStage, setCustomQuestionRequired,
    setCustomQuestionText, setCustomQuestionType, setDetectedCriteria, setDisplayedText, setDynamicInitialMessage,
    setEnrichedJDData, setFastTrackAdjustments, setFastTrackAppliedData, setFastTrackMessageSent, setFastTrackOriginalCompetencies,
    setFastTrackSearchCriteria, setFastTrackSearchResults, setFastTrackSelectedVacancy, setFastTrackState, setFileAnalysisResult,
    setFileAnalysisType, setGeneratedJobDescription, setGlobalCandidateCount, setHasAppliedRestoredDraft, setHasAttemptedCalibrationGeneration,
    setInputValue, setInternalJobCreationMode, setIsGeneratingDescription, setIsGeneratingWSI, setIsLoading,
    setIsLoadingCalibration, setIsLoadingEnrichment, setIsPanelOpen, setIsSearchingVacancies, setJobConfig,
    setJobDescription, setLocalCandidateCount, setMessages, setNewBenefitName, setNewBenefitValue,
    setNewCompetencyJustification, setNewCompetencyName, setNewSkillName, setPendingDraftData, setPostCalibrationComplete,
    setPublishedJobId, setRejectedCandidates, setSalaryInfo, setSearchPhase, setShowAddBenefitModal,
    setShowAddCompetencyModal, setShowAddSkillModal, setShowCalibrationModal, setShowClearDraftConfirm, setShowCompetenciesSuggestionsModal,
    setShowCustomQuestionForm, setShowUploadModal, setStageTransition, setTechnicalSkills, setUploadedFile,
    setWizardFastTrackSourceJobId, setWizardMode, setWsiCandidates, setWsiGenerationBatch, setWsiHasGenerated,
    setWsiQuestions, setWsiRegenerationPrompted, showCalibrationModal,
    technicalSkills, toolCalling, trackFieldChange, typeText, user, resolvedCompanyId,
    wizardFastTrackSourceJobId, wizardMode, wsiCandidates, wsiGenerationBatch, wsiHasGenerated,
    wsiQualityGates, wsiQuestions,
    inline, onOrchestratedMessage, onMessagesUpdate, extractCriteriaFromText,
    proceedToNextStage,
  } = ctx as any

  const {
    generateCriteriaResponse,
    generateParecerData,
    generateCompetencyAnalysisMessage,
    generateWSIExplanationMessage,
    handleAcceptSuggestions,
    handleSkipSuggestions,
    handleClearDraftAndReset,
    handlePublishJob,
    buildCandidateSearchQuery,
    generateJobDescription,
    startLocalSearch,
    startGlobalSearch,
  } = useWizardPublishHandlers({
    detectedCriteria,
    setDetectedCriteria,
    basicInfoFields,
    setBasicInfoFields,
    technicalSkills,
    setTechnicalSkills,
    behavioralCompetencies,
    setBehavioralCompetencies,
    salaryInfo,
    setSalaryInfo,
    messages,
    setMessages,
    currentStage,
    setCurrentStage,
    publishingPlatforms,
    jobConfig,
    setJobDescription,
    setIsGeneratingDescription,
    setPublishedJobId,
    setAwaitingCalibrationChoice,
    setSearchPhase,
    setLocalCandidateCount,
    setGlobalCandidateCount,
    preferredCandidateCount,
    selectedSuggestedTechnical,
    selectedSuggestedBehavioral,
    setShowCompetenciesSuggestionsModal,
    clearWizardDraft,
    setHasAppliedRestoredDraft,
    setShowClearDraftConfirm,
    setWsiCandidates,
    setGeneratedJobDescription,
    companyConfig,
    interviewStages,
    companyMembersMap,
    companyDefaultQuestions,
    wsiCandidates,
    user,
    resolvedCompanyId,
    wizardFastTrackSourceJobId,
    setWizardFastTrackSourceJobId,
    conversationId,
    learning,
    setIsLoading,
    proceedToNextStage,
  })

  const {
    validationError, setValidationError,
    goToNextStage, goToPreviousStage, canAdvanceToNextStage,
  } = useStageValidationAndNavigation({
    currentStage,
    currentStageIndex,
    salaryInfo,
    messages,
    detectedCriteria,
    technicalSkills,
    behavioralCompetencies,
    wsiQualityGates,
    wsiCandidates,
    companyDefaultQuestions,
    calibrationComplete,
    approvedCandidates,
    publishedJobId,
    basicInfoFields,
    setStageTransition,
    setMessages,
    setDisplayedText,
    setCurrentStage,
    fetchDeduplicatedSkills,
    typeText,
    proceedToNextStage,
    generateCompetencyAnalysisMessage,
    generateWSIExplanationMessage,
  })

  const {
    generateWSIQuestions, toggleWSIQuestionSelection, updateWSIQuestionExpectedAnswer,
    updateWSIQuestionCorrectOption, deleteWSIQuestion, addCustomQuestion,
    initializeCalibrationCriteria, generateCalibrationCandidates,
    handleApproveCandidate, handleRejectCandidate, moveToNextCandidate,
    generateMoreCalibrationCandidates, addCalibrationCriterion, removeCalibrationCriterion,
    reorderCalibrationCriteria, handleFastTrackVacancySelect, handleFastTrackSearch,
    handleFastTrackPublish, parseFastTrackAdjustment, buildCollectedData,
    processOrchestratorResponse, detectFastTrackIntent,
  } = useWSIAndCalibrationHandlers({
    basicInfoFields, setBasicInfoFields, detectedCriteria, setDetectedCriteria,
    technicalSkills, setTechnicalSkills, behavioralCompetencies, setBehavioralCompetencies,
    salaryInfo, setSalaryInfo, messages, setMessages, currentStage, setCurrentStage,
    wsiCandidates, setWsiCandidates, wsiGenerationBatch, setWsiGenerationBatch,
    isGeneratingWSI, setIsGeneratingWSI, wsiHasGenerated, setWsiHasGenerated, setWsiQuestions,
    customQuestionText, customQuestionType, customQuestionRequired,
    setShowCustomQuestionForm, setCustomQuestionText, setCustomQuestionType, setCustomQuestionRequired,
    calibrationCandidates, setCalibrationCandidates, currentCalibrationIndex, setCurrentCalibrationIndex,
    approvedCandidates, setApprovedCandidates, rejectedCandidates, setRejectedCandidates,
    calibrationComplete, setCalibrationComplete, isLoadingCalibration, setIsLoadingCalibration,
    showCalibrationModal, setShowCalibrationModal, calibrationSessionId, setCalibrationSessionId,
    calibrationComment, setCalibrationComment, publishedJobId, setPublishedJobId,
    calibrationCriteria, setCalibrationCriteria, postCalibrationComplete, setPostCalibrationComplete,
    hasAttemptedCalibrationGeneration, setHasAttemptedCalibrationGeneration,
    setSearchPhase, setLocalCandidateCount, setGlobalCandidateCount, preferredCandidateCount,
    awaitingCalibrationChoice, setAwaitingCalibrationChoice,
    fastTrackState, setFastTrackState, fastTrackSelectedVacancy, setFastTrackSelectedVacancy,
    fastTrackAdjustments, setFastTrackAdjustments, fastTrackSearchResults, setFastTrackSearchResults,
    isSearchingVacancies, setIsSearchingVacancies, wizardFastTrackSourceJobId, setWizardFastTrackSourceJobId,
    setWizardMode, isLoading, setIsLoading, setJobConfig, setEnrichedJDData,
    setIsLoadingEnrichment, setCompensationAnalysis, setDisplayedText,
    user, resolvedCompanyId, conversationMemory, highlightField, typeText,
    inputEvaluationStageCompletionShown, awaitingStageAdvanceConfirmation, setAwaitingStageAdvanceConfirmation,
    onJobCreated,
  })

  const {
    addNewSkill, addNewBenefit, addNewCompetency,
    handleFileSelect, handleFileAnalysisComplete, handleFileAnalysisError,
    handleVoiceResponse,
    criteriaItems, containerClasses, contentClasses,
  } = useItemAndFileHandlers({
    newSkillCategory,
    newBenefitName,
    newBenefitValue,
    newCompetencyName,
    newCompetencyJustification,
    detectedCriteria,
    isFullscreen,
    inline,
    setTechnicalSkills,
    setBehavioralCompetencies,
    setSalaryInfo,
    setMessages,
    setShowAddSkillModal,
    setNewSkillName,
    setShowAddBenefitModal,
    setNewBenefitName,
    setNewBenefitValue,
    setShowAddCompetencyModal,
    setNewCompetencyName,
    setNewCompetencyJustification,
    setUploadedFile,
    setShowUploadModal,
    setFileAnalysisResult,
    setFileAnalysisType,
  })

  const { handleSendMessage, handleKeyDown, handleQuickSuggestion } = useSendMessageHandlers({
    isOpen, onClose, isJobCreationMode, inline, onJobCreated, onOrchestratedMessage, onMessagesUpdate,
    inputValue, inputRef, setInputValue, messages, setMessages, isLoading, setIsLoading,
    isTypingEffect, conversationId, setConversationId, user, resolvedCompanyId, currentStage, setCurrentStage,
    wizardMode, setWizardMode, isInJobCreationMode,
    awaitingStageAdvanceConfirmation, setAwaitingStageAdvanceConfirmation,
    awaitingDraftChoice, setAwaitingDraftChoice, awaitingCalibrationChoice, setAwaitingCalibrationChoice,
    activeToolConfirmationMessageId, setActiveToolConfirmationMessageId,
    awaitingWSIRegenerationConfirmation, setAwaitingWSIRegenerationConfirmation,
    awaitingSensitiveFieldsConfirmation, setAwaitingSensitiveFieldsConfirmation,
    pendingDraftData, setPendingDraftData, setHasAppliedRestoredDraft, applyPendingDraft, clearWizardDraft,
    calibrationComplete, setCalibrationComplete, approvedCandidates, rejectedCandidates,
    setIsPanelOpen, localCandidateCount, setShowCalibrationModal,
    fastTrack, fastTrackState, setFastTrackState, fastTrackSearchResults, setFastTrackSearchResults,
    fastTrackSelectedVacancy, setFastTrackSelectedVacancy, fastTrackAdjustments, setFastTrackAdjustments,
    fastTrackSearchCriteria, setFastTrackSearchCriteria, isSearchingVacancies, setIsSearchingVacancies,
    setWizardFastTrackSourceJobId, wizardFastTrackSourceJobId, fastTrackSuggestionsShownTracked,
    setAwaitingFastTrackSelection, awaitingFastTrackSelection,
    fastTrackAppliedData, setFastTrackAppliedData, setFastTrackOriginalCompetencies,
    setWsiRegenerationPrompted, setFastTrackMessageSent,
    basicInfoFields, setBasicInfoFields, detectedCriteria, setDetectedCriteria,
    technicalSkills, setTechnicalSkills, behavioralCompetencies, setBehavioralCompetencies,
    salaryInfo, setSalaryInfo, wsiQuestions, setWsiQuestions, wsiCandidates, setWsiCandidates,
    setCompetencySuggestions, generatedJobDescription, setGeneratedJobDescription,
    compensationAnalysis, setCompensationAnalysis, setIsLoadingEnrichment, setJobConfig,
    setInternalJobCreationMode, setDynamicInitialMessage, setDisplayedText,
    buildCollectedData, processOrchestratorResponse, generateParecerData, extractCriteriaFromText,
    typeText, generateLLMContext, goToNextStage,
    handleFastTrackVacancySelect, handleFastTrackSearch, handleFastTrackPublish,
    parseFastTrackAdjustment, detectFastTrackIntent, generateCriteriaResponse,
    callEvaluationStep, trackFieldChange, contextSwitching, conversationMemory,
    analytics, toolCalling, learning,
  })

  return {
    addCalibrationCriterion, addCustomQuestion, addNewBenefit, addNewCompetency, addNewSkill,
    buildCandidateSearchQuery, buildCollectedData, canAdvanceToNextStage, containerClasses, contentClasses,
    criteriaItems, deleteWSIQuestion, detectFastTrackIntent, generateCalibrationCandidates, generateCompetencyAnalysisMessage,
    generateCriteriaResponse, generateJobDescription, generateMoreCalibrationCandidates, generateParecerData,
    generateWSIExplanationMessage, generateWSIQuestions, goToNextStage, goToPreviousStage,
    handleAcceptSuggestions, handleApproveCandidate, handleClearDraftAndReset,
    handleFastTrackPublish, handleFastTrackSearch, handleFastTrackVacancySelect,
    handleFileAnalysisComplete, handleFileAnalysisError, handleFileSelect,
    handleKeyDown, handlePublishJob, handleQuickSuggestion, handleRejectCandidate,
    handleSendMessage, handleSkipSuggestions, handleVoiceResponse,
    initializeCalibrationCriteria, moveToNextCandidate, parseFastTrackAdjustment,
    proceedToNextStage, processOrchestratorResponse, removeCalibrationCriterion,
    reorderCalibrationCriteria, setValidationError, startGlobalSearch, startLocalSearch,
    toggleWSIQuestionSelection, updateWSIQuestionCorrectOption, updateWSIQuestionExpectedAnswer,
    validationError,
  }
}
