"use client"

import { useEffect } from "react"
import { useExtractCriteria } from "./useExpandedChatCallbacks"
import { useExpandedChatEffects } from "./useExpandedChatEffects"
import { useExpandedChatSubHooks } from "./useExpandedChatSubHooks"
import { useProceedToNextStage } from './useProceedToNextStage'
import type { useExpandedChatCoreState } from './useExpandedChatCoreState'
import type { useExpandedChatCoreHooks } from './useExpandedChatCoreHooks'

type CoreState = ReturnType<typeof useExpandedChatCoreState>
type CoreHooks = ReturnType<typeof useExpandedChatCoreHooks>

interface WiringParams {
  state: CoreState
  hooks: CoreHooks
  isOpen: boolean
  initialMessage?: string
  initialMessages?: Array<{ id: string; role: 'user' | 'assistant'; content: string; timestamp: Date }>
  mode: string
  onClose: () => void
  onJobCreated?: (jobId: string) => void
  inline: boolean
  onOrchestratedMessage?: (message: string) => void
  onMessagesUpdate?: (messages: Array<{ id: string; role: 'user' | 'assistant'; content: string; timestamp: Date }>) => void
}

export function useExpandedChatWiring({
  state, hooks, isOpen, initialMessage, initialMessages, mode,
  onClose, onJobCreated, inline, onOrchestratedMessage, onMessagesUpdate,
}: WiringParams) {
  const effectsResult = useExpandedChatEffects({
    INITIAL_STAGES: state.INITIAL_STAGES, PROACTIVE_MESSAGE_DELAY: state.PROACTIVE_MESSAGE_DELAY,
    analytics: hooks.analytics, approvedCandidates: state.approvedCandidates,
    awaitingWSIRegenerationConfirmation: state.awaitingWSIRegenerationConfirmation,
    basicInfoFields: state.basicInfoFields, behavioralCompetencies: state.behavioralCompetencies,
    calibrationComplete: state.calibrationComplete, calibrationProactiveTimerRef: state.calibrationProactiveTimerRef,
    calibrationStageCompletionShown: state.calibrationStageCompletionShown,
    checkForExistingDraftSync: state.checkForExistingDraftSync, companyConfig: state.companyConfig,
    companyDefaultQuestions: state.companyDefaultQuestions,
    competenciesProactiveTimerRef: state.competenciesProactiveTimerRef,
    competenciesStageCompletionShown: state.competenciesStageCompletionShown,
    configLoaded: state.configLoaded, currentStage: state.currentStage,
    detectedCriteria: state.detectedCriteria, displayedText: state.displayedText,
    fastTrack: hooks.fastTrack, fastTrackOriginalCompetencies: state.fastTrackOriginalCompetencies,
    generatedJobDescription: state.generatedJobDescription, initialLiaMessage: state.initialLiaMessage,
    initialMessages, inputEvaluationProactiveTimerRef: state.inputEvaluationProactiveTimerRef,
    inputEvaluationStageCompletionShown: state.inputEvaluationStageCompletionShown,
    inputRef: state.inputRef, internalJobCreationMode: state.internalJobCreationMode,
    isJobCreationMode: state.isJobCreationMode, isOpen, isResizing: state.isResizing,
    isTypingEffect: state.isTypingEffect, jobConfig: state.jobConfig,
    jobDescription: state.jobDescription, learning: hooks.learning,
    messages: state.messages, messagesEndRef: state.messagesEndRef,
    mode, proactiveActionIds: state.proactiveActionIds,
    rejectedCandidates: state.rejectedCandidates,
    resizeRef: state.resizeRef, salaryBenchmark: state.salaryBenchmark,
    salaryInfo: state.salaryInfo, salaryProactiveTimerRef: state.salaryProactiveTimerRef,
    salaryStageCompletionShown: state.salaryStageCompletionShown,
    setAwaitingStageAdvanceConfirmation: state.setAwaitingStageAdvanceConfirmation,
    setAwaitingWSIRegenerationConfirmation: state.setAwaitingWSIRegenerationConfirmation,
    setBasicInfoFields: state.setBasicInfoFields, setBehavioralCompetencies: state.setBehavioralCompetencies,
    setCalibrationStageCompletionShown: state.setCalibrationStageCompletionShown,
    setCompanyConfig: state.setCompanyConfig, setCompanyDefaultQuestions: state.setCompanyDefaultQuestions,
    setCompetenciesPanelExpanded: state.setCompetenciesPanelExpanded,
    setCompetenciesStageCompletionShown: state.setCompetenciesStageCompletionShown,
    setConfigLoaded: state.setConfigLoaded, setCurrentStage: state.setCurrentStage,
    setDetectedCriteria: state.setDetectedCriteria, setDisplayedText: state.setDisplayedText,
    setFastTrackMessageSent: state.setFastTrackMessageSent,
    setFieldOrigins: state.setFieldOrigins, setFieldsFromConfig: state.setFieldsFromConfig,
    setGeneratedJobDescription: state.setGeneratedJobDescription,
    setInputEvaluationStageCompletionShown: state.setInputEvaluationStageCompletionShown,
    setInputValue: state.setInputValue,
    setIsLoadingBenchmark: state.setIsLoadingBenchmark, setIsResizing: state.setIsResizing,
    setIsTypingEffect: state.setIsTypingEffect, setJobConfig: state.setJobConfig,
    setMessages: state.setMessages,
    setPanelWidth: state.setPanelWidth, setProactiveActionIds: state.setProactiveActionIds,
    setSalaryBenchmark: state.setSalaryBenchmark, setSalaryInfo: state.setSalaryInfo,
    setSalaryPanelExpanded: state.setSalaryPanelExpanded,
    setSalaryStageCompletionShown: state.setSalaryStageCompletionShown,
    setShowAutoFilledNotification: state.setShowAutoFilledNotification,
    setTechnicalSkills: state.setTechnicalSkills, setWizardGreeting: state.setWizardGreeting,
    setWizardGreetingLoaded: state.setWizardGreetingLoaded,
    setWsiCandidates: state.setWsiCandidates,
    setWsiQuestionsStageCompletionShown: state.setWsiQuestionsStageCompletionShown,
    setWsiRegenerationPrompted: state.setWsiRegenerationPrompted, sla: state.sla,
    technicalSkills: state.technicalSkills, typingTimeoutRef: state.typingTimeoutRef,
    user: state.user,
    wizardGreeting: state.wizardGreeting, wsiCandidates: state.wsiCandidates,
    wsiQuestionsProactiveTimerRef: state.wsiQuestionsProactiveTimerRef,
    wsiQuestionsStageCompletionShown: state.wsiQuestionsStageCompletionShown,
    wsiRegenerationPrompted: state.wsiRegenerationPrompted,
    publishingState: state.publishingState, publishingActions: state.publishingActions,
    wizardDraftId: state.wizardDraftId, STAGE_DISPLAY_NAMES: state.STAGE_DISPLAY_NAMES,
    onMessagesUpdate,
    isLoadingEligibilityQuestions: state.isLoadingEligibilityQuestions,
    companyEligibilityQuestions: state.companyEligibilityQuestions,
    isLoadingStages: state.isLoadingStages,
  })

  const {
    typeText, isFieldRequiredForWizard, hasConfigData, isInJobCreationMode,
    wsiQualityGates, applyPendingDraft,
    companyMembersMap, languagesUserEdited, setCompanyMembersMap, setLanguagesUserEdited,
    hasAppliedRestoredDraft, setHasAppliedRestoredDraft,
    awaitingDraftChoice, setAwaitingDraftChoice,
    pendingDraftData, setPendingDraftData,
    saveWizardDraft, clearWizardDraft, loadedDraft, hasRestoredDraft,
    hasAttemptedRestore, isAutoSaving, autoSaveLastSaved, hasPendingChanges, getLastSavedText,
    hasMinimumCompetencies,
  } = effectsResult

  const { extractCriteriaFromText } = useExtractCriteria({
    detectedCriteria: state.detectedCriteria,
    setDetectedCriteria: state.setDetectedCriteria,
  })

  const { proceedToNextStage } = useProceedToNextStage({
    currentStageIndex: state.currentStageIndex,
    detectedCriteria: state.detectedCriteria,
    setMessages: state.setMessages,
    typeText,
    setCurrentStage: state.setCurrentStage,
    saveWizardDraft,
    setDisplayedText: state.setDisplayedText,
  })

  const subHooksResult = useExpandedChatSubHooks({
    activeToolConfirmationMessageId: state.activeToolConfirmationMessageId,
    analytics: hooks.analytics, applyPendingDraft, approvedCandidates: state.approvedCandidates,
    awaitingCalibrationChoice: state.awaitingCalibrationChoice,
    awaitingDraftChoice, awaitingFastTrackSelection: state.awaitingFastTrackSelection,
    awaitingSensitiveFieldsConfirmation: state.awaitingSensitiveFieldsConfirmation,
    awaitingStageAdvanceConfirmation: state.awaitingStageAdvanceConfirmation,
    awaitingWSIRegenerationConfirmation: state.awaitingWSIRegenerationConfirmation,
    basicInfoFields: state.basicInfoFields, behavioralCompetencies: state.behavioralCompetencies,
    calibrationCandidates: state.calibrationCandidates, calibrationComment: state.calibrationComment,
    calibrationComplete: state.calibrationComplete,
    calibrationCriteria: state.calibrationCriteria, calibrationSessionId: state.calibrationSessionId,
    callEvaluationStep: hooks.callEvaluationStep, clearWizardDraft,
    companyConfig: state.companyConfig,
    companyDefaultQuestions: state.companyDefaultQuestions, companyMembersMap,
    compensationAnalysis: state.compensationAnalysis, contextSwitching: hooks.contextSwitching,
    conversationId: state.conversationId,
    conversationMemory: hooks.conversationMemory, currentCalibrationIndex: state.currentCalibrationIndex,
    currentStage: state.currentStage, currentStageConfig: state.currentStageConfig,
    currentStageIndex: state.currentStageIndex,
    customQuestionRequired: state.customQuestionRequired, customQuestionText: state.customQuestionText,
    customQuestionType: state.customQuestionType, detectedCriteria: state.detectedCriteria,
    extractCriteriaFromText,
    fastTrack: hooks.fastTrack, fastTrackAdjustments: state.fastTrackAdjustments,
    fastTrackAppliedData: state.fastTrackAppliedData,
    fastTrackSearchCriteria: state.fastTrackSearchCriteria,
    fastTrackSearchResults: state.fastTrackSearchResults,
    fastTrackSelectedVacancy: state.fastTrackSelectedVacancy, fastTrackState: state.fastTrackState,
    fastTrackSuggestionsShownTracked: state.fastTrackSuggestionsShownTracked,
    fetchDeduplicatedSkills: hooks.fetchDeduplicatedSkills,
    generateLLMContext: hooks.generateLLMContext,
    generatedJobDescription: state.generatedJobDescription,
    hasAttemptedCalibrationGeneration: state.hasAttemptedCalibrationGeneration,
    highlightField: hooks.highlightField,
    inputEvaluationStageCompletionShown: state.inputEvaluationStageCompletionShown,
    inputRef: state.inputRef,
    inputValue: state.inputValue, interviewStages: state.interviewStages,
    isFullscreen: state.isFullscreen,
    isGeneratingWSI: state.isGeneratingWSI, isInJobCreationMode,
    isJobCreationMode: state.isJobCreationMode, isLoading: state.isLoading,
    isLoadingCalibration: state.isLoadingCalibration, isOpen,
    isSearchingVacancies: state.isSearchingVacancies,
    isTypingEffect: state.isTypingEffect, jobConfig: state.jobConfig,
    learning: hooks.learning, localCandidateCount: state.localCandidateCount,
    messages: state.messages, newBenefitName: state.newBenefitName,
    newBenefitValue: state.newBenefitValue,
    newCompetencyJustification: state.newCompetencyJustification,
    newCompetencyName: state.newCompetencyName,
    newSkillCategory: state.newSkillCategory, onClose, onJobCreated, pendingDraftData,
    postCalibrationComplete: state.postCalibrationComplete,
    preferredCandidateCount: state.preferredCandidateCount, proceedToNextStage,
    publishedJobId: state.publishedJobId, publishingPlatforms: state.publishingPlatforms,
    rejectedCandidates: state.rejectedCandidates, salaryInfo: state.salaryInfo,
    saveWizardDraft, selectedSuggestedBehavioral: state.selectedSuggestedBehavioral,
    selectedSuggestedTechnical: state.selectedSuggestedTechnical,
    setActiveToolConfirmationMessageId: state.setActiveToolConfirmationMessageId,
    setApprovedCandidates: state.setApprovedCandidates,
    setAwaitingCalibrationChoice: state.setAwaitingCalibrationChoice,
    setAwaitingFastTrackSelection: state.setAwaitingFastTrackSelection,
    setAwaitingSensitiveFieldsConfirmation: state.setAwaitingSensitiveFieldsConfirmation,
    setAwaitingStageAdvanceConfirmation: state.setAwaitingStageAdvanceConfirmation,
    setAwaitingWSIRegenerationConfirmation: state.setAwaitingWSIRegenerationConfirmation,
    setBasicInfoFields: state.setBasicInfoFields, setBehavioralCompetencies: state.setBehavioralCompetencies,
    setCalibrationCandidates: state.setCalibrationCandidates,
    setCalibrationComment: state.setCalibrationComment,
    setCalibrationComplete: state.setCalibrationComplete,
    setCalibrationCriteria: state.setCalibrationCriteria,
    setCalibrationSessionId: state.setCalibrationSessionId,
    setCompensationAnalysis: state.setCompensationAnalysis,
    setCompetencySuggestions: state.setCompetencySuggestions,
    setConversationId: state.setConversationId,
    setCurrentCalibrationIndex: state.setCurrentCalibrationIndex,
    setCurrentStage: state.setCurrentStage,
    setCustomQuestionRequired: state.setCustomQuestionRequired,
    setCustomQuestionText: state.setCustomQuestionText,
    setCustomQuestionType: state.setCustomQuestionType,
    setDetectedCriteria: state.setDetectedCriteria, setDisplayedText: state.setDisplayedText,
    setDynamicInitialMessage: state.setDynamicInitialMessage,
    setEnrichedJDData: state.setEnrichedJDData,
    setFastTrackAdjustments: state.setFastTrackAdjustments,
    setFastTrackAppliedData: state.setFastTrackAppliedData,
    setFastTrackMessageSent: state.setFastTrackMessageSent,
    setFastTrackOriginalCompetencies: state.setFastTrackOriginalCompetencies,
    setFastTrackSearchCriteria: state.setFastTrackSearchCriteria,
    setFastTrackSearchResults: state.setFastTrackSearchResults,
    setFastTrackSelectedVacancy: state.setFastTrackSelectedVacancy,
    setFastTrackState: state.setFastTrackState,
    setFileAnalysisResult: state.setFileAnalysisResult,
    setFileAnalysisType: state.setFileAnalysisType,
    setGeneratedJobDescription: state.setGeneratedJobDescription,
    setGlobalCandidateCount: state.setGlobalCandidateCount,
    setHasAttemptedCalibrationGeneration: state.setHasAttemptedCalibrationGeneration,
    setInputValue: state.setInputValue, setInternalJobCreationMode: state.setInternalJobCreationMode,
    setIsGeneratingDescription: state.setIsGeneratingDescription,
    setIsGeneratingWSI: state.setIsGeneratingWSI, setIsLoading: state.setIsLoading,
    setIsLoadingCalibration: state.setIsLoadingCalibration,
    setIsLoadingEnrichment: state.setIsLoadingEnrichment,
    setIsPanelOpen: state.setIsPanelOpen,
    setIsSearchingVacancies: state.setIsSearchingVacancies, setJobConfig: state.setJobConfig,
    setJobDescription: state.setJobDescription,
    setLocalCandidateCount: state.setLocalCandidateCount, setMessages: state.setMessages,
    setNewBenefitName: state.setNewBenefitName, setNewBenefitValue: state.setNewBenefitValue,
    setNewCompetencyJustification: state.setNewCompetencyJustification,
    setNewCompetencyName: state.setNewCompetencyName,
    setNewSkillName: state.setNewSkillName,
    setPostCalibrationComplete: state.setPostCalibrationComplete,
    setPublishedJobId: state.setPublishedJobId,
    setRejectedCandidates: state.setRejectedCandidates, setSalaryInfo: state.setSalaryInfo,
    setSearchPhase: state.setSearchPhase,
    setShowAddBenefitModal: state.setShowAddBenefitModal,
    setShowAddCompetencyModal: state.setShowAddCompetencyModal,
    setShowAddSkillModal: state.setShowAddSkillModal,
    setShowCalibrationModal: state.setShowCalibrationModal,
    setShowClearDraftConfirm: state.setShowClearDraftConfirm,
    setShowCompetenciesSuggestionsModal: state.setShowCompetenciesSuggestionsModal,
    setShowCustomQuestionForm: state.setShowCustomQuestionForm,
    setShowUploadModal: state.setShowUploadModal,
    setStageTransition: state.setStageTransition, setTechnicalSkills: state.setTechnicalSkills,
    setUploadedFile: state.setUploadedFile,
    setWizardFastTrackSourceJobId: state.setWizardFastTrackSourceJobId,
    setWizardMode: state.setWizardMode, setWsiCandidates: state.setWsiCandidates,
    setWsiGenerationBatch: state.setWsiGenerationBatch, setWsiHasGenerated: state.setWsiHasGenerated,
    setWsiQuestions: state.setWsiQuestions,
    setWsiRegenerationPrompted: state.setWsiRegenerationPrompted,
    showCalibrationModal: state.showCalibrationModal,
    technicalSkills: state.technicalSkills, toolCalling: hooks.toolCalling,
    trackFieldChange: hooks.trackFieldChange, typeText, user: state.user, resolvedCompanyId: state.resolvedCompanyId,
    wizardFastTrackSourceJobId: state.wizardFastTrackSourceJobId,
    wizardMode: state.wizardMode, wsiCandidates: state.wsiCandidates,
    wsiGenerationBatch: state.wsiGenerationBatch,
    wsiHasGenerated: state.wsiHasGenerated, wsiQualityGates, wsiQuestions: state.wsiQuestions,
    inline, onOrchestratedMessage, onMessagesUpdate,
  })

  const {
    addCalibrationCriterion, addCustomQuestion, addNewBenefit, addNewCompetency, addNewSkill,
    buildCandidateSearchQuery, buildCollectedData, canAdvanceToNextStage, containerClasses, contentClasses,
    criteriaItems, deleteWSIQuestion, detectFastTrackIntent, generateCalibrationCandidates, generateCompetencyAnalysisMessage,
    generateCriteriaResponse, generateJobDescription, generateMoreCalibrationCandidates, generateParecerData,
    generateWSIExplanationMessage, generateWSIQuestions, goToNextStage, goToPreviousStage,
    handleAcceptSuggestions, handleApproveCandidate, handleClearDraftAndReset,
    handleFastTrackPublish, handleFastTrackSearch, handleFastTrackVacancySelect,
    handleFileAnalysisComplete, handleFileAnalysisError, handleFileSelect,
    handleKeyDown, handlePublishJob, handleQuickSuggestion, handleRejectCandidate,
    handleSendMessage, handleSkipSuggestions, handleVoiceResponse,
    initializeCalibrationCriteria, moveToNextCandidate, parseFastTrackAdjustment,
    processOrchestratorResponse, removeCalibrationCriterion,
    reorderCalibrationCriteria, startGlobalSearch, startLocalSearch,
    toggleWSIQuestionSelection, updateWSIQuestionCorrectOption, updateWSIQuestionExpectedAnswer,
  } = subHooksResult

  useEffect(() => {
    if (state.currentStage === 'review-publish' && !state.jobDescription) {
      generateJobDescription()
    }
  }, [state.currentStage, generateJobDescription, state.jobDescription])

  useEffect(() => {
    if (isOpen && initialMessage && state.messages.length === 1 && !state.isTypingEffect) {
      setTimeout(() => {
        handleSendMessage(initialMessage)
        state.setInputValue("")
      }, 500)
    }
  }, [isOpen, initialMessage, state.messages.length, state.isTypingEffect, handleSendMessage, state])

  return {
    activeInputTab: state.activeInputTab,
    addCalibrationCriterion, addCustomQuestion, addNewBenefit, addNewCompetency, addNewSkill,
    analytics: hooks.analytics,
    approvedCandidates: state.approvedCandidates,
    autoSaveLastSaved,
    basicInfoFields: state.basicInfoFields,
    behavioralCompetencies: state.behavioralCompetencies,
    calibrationCandidates: state.calibrationCandidates,
    calibrationComment: state.calibrationComment,
    calibrationComplete: state.calibrationComplete,
    calibrationCriteria: state.calibrationCriteria,
    canAdvanceToNextStage,
    candidateProfileTab: state.candidateProfileTab,
    checkForExistingDraftSync: state.checkForExistingDraftSync,
    companyConfig: state.companyConfig,
    companyDefaultQuestions: state.companyDefaultQuestions,
    competenciesPanelExpanded: state.competenciesPanelExpanded,
    configLoaded: state.configLoaded,
    containerClasses, contentClasses,
    conversationId: state.conversationId,
    criteriaItems,
    currentCalibrationIndex: state.currentCalibrationIndex,
    currentStage: state.currentStage,
    currentStageConfig: state.currentStageConfig,
    currentStageIndex: state.currentStageIndex,
    customQuestionRequired: state.customQuestionRequired,
    customQuestionText: state.customQuestionText,
    customQuestionType: state.customQuestionType,
    deleteWSIQuestion,
    detectedCriteria: state.detectedCriteria,
    displayedText: state.displayedText,
    enrichedJDData: state.enrichedJDData,
    extractCriteriaDebounceRef: state.extractCriteriaDebounceRef,
    extractCriteriaFromText,
    fastTrack: hooks.fastTrack,
    fastTrackSuggestionsShownTracked: state.fastTrackSuggestionsShownTracked,
    fileInputRef: state.fileInputRef,
    generateCalibrationCandidates,
    generateJobDescription,
    generateWSIQuestions,
    getBehavioralCompetencies: state.getBehavioralCompetencies,
    getLastSavedText,
    globalCandidateCount: state.globalCandidateCount,
    globalSearchAuthorized: state.globalSearchAuthorized,
    goToNextStage, goToPreviousStage,
    handleApproveCandidate,
    handleClearDraftAndReset,
    handleFastTrackVacancySelect,
    handleFileAnalysisComplete, handleFileAnalysisError, handleFileSelect,
    handleKeyDown,
    handleProactiveAccept: hooks.handleProactiveAccept,
    handleProactiveReject: hooks.handleProactiveReject,
    handlePublishJob,
    handleRejectCandidate,
    handleSendMessage,
    handleVoiceResponse,
    hasAttemptedCalibrationGeneration: state.hasAttemptedCalibrationGeneration,
    hasConfigData,
    hasPendingChanges,
    hasRestoredDraft,
    highlightedFields: hooks.highlightedFields,
    inputRef: state.inputRef,
    inputValue: state.inputValue,
    isAutoSaving,
    isFieldRequiredForWizard,
    isFullscreen: state.isFullscreen,
    isGeneratingDescription: state.isGeneratingDescription,
    isGeneratingWSI: state.isGeneratingWSI,
    isHighlighted: hooks.isHighlighted,
    isInJobCreationMode,
    isJobCreationMode: state.isJobCreationMode,
    isLoading: state.isLoading,
    isLoadingBenchmark: state.isLoadingBenchmark,
    isLoadingCalibration: state.isLoadingCalibration,
    isLoadingEnrichment: state.isLoadingEnrichment,
    isPanelOpen: state.isPanelOpen,
    isSearchingVacancies: state.isSearchingVacancies,
    isTypingEffect: state.isTypingEffect,
    jobConfig: state.jobConfig,
    jobDescription: state.jobDescription,
    localCandidateCount: state.localCandidateCount,
    messages: state.messages,
    messagesEndRef: state.messagesEndRef,
    newBenefitName: state.newBenefitName,
    newBenefitValue: state.newBenefitValue,
    newCompetencyJustification: state.newCompetencyJustification,
    newCompetencyName: state.newCompetencyName,
    newSkillCategory: state.newSkillCategory,
    newSkillName: state.newSkillName,
    panelWidth: state.panelWidth,
    preferredCandidateCount: state.preferredCandidateCount,
    publishedJobId: state.publishedJobId,
    publishingPlatforms: state.publishingPlatforms,
    removeCalibrationCriterion,
    resizeRef: state.resizeRef,
    salaryBenchmark: state.salaryBenchmark,
    salaryInfo: state.salaryInfo,
    salaryPanelExpanded: state.salaryPanelExpanded,
    searchPhase: state.searchPhase,
    setActiveInputTab: state.setActiveInputTab,
    setActiveToolConfirmationMessageId: state.setActiveToolConfirmationMessageId,
    setAwaitingDraftChoice,
    setAwaitingFastTrackSelection: state.setAwaitingFastTrackSelection,
    setBehavioralCompetencies: state.setBehavioralCompetencies,
    setCalibrationComment: state.setCalibrationComment,
    setCalibrationComplete: state.setCalibrationComplete,
    setCandidateProfileTab: state.setCandidateProfileTab,
    setCompanyDefaultQuestions: state.setCompanyDefaultQuestions,
    setCompetenciesPanelExpanded: state.setCompetenciesPanelExpanded,
    setCompetenciesTab: state.setCompetenciesTab,
    setCompetencySuggestions: state.setCompetencySuggestions,
    setCurrentCalibrationIndex: state.setCurrentCalibrationIndex,
    setCurrentStage: state.setCurrentStage,
    setCustomQuestionRequired: state.setCustomQuestionRequired,
    setCustomQuestionText: state.setCustomQuestionText,
    setCustomQuestionType: state.setCustomQuestionType,
    setDetectedCriteria: state.setDetectedCriteria,
    setDisplayedText: state.setDisplayedText,
    setDynamicInitialMessage: state.setDynamicInitialMessage,
    setEditingCompetency: state.setEditingCompetency,
    setEnrichedJDData: state.setEnrichedJDData,
    setFastTrackState: state.setFastTrackState,
    setGlobalSearchAuthorized: state.setGlobalSearchAuthorized,
    setHasAttemptedCalibrationGeneration: state.setHasAttemptedCalibrationGeneration,
    setInputValue: state.setInputValue,
    setInternalJobCreationMode: state.setInternalJobCreationMode,
    setIsFullscreen: state.setIsFullscreen,
    setIsLoading: state.setIsLoading,
    setIsPanelOpen: state.setIsPanelOpen,
    setIsResizing: state.setIsResizing,
    setJobConfig: state.setJobConfig,
    setMessages: state.setMessages,
    setNewBenefitName: state.setNewBenefitName,
    setNewBenefitValue: state.setNewBenefitValue,
    setNewCompetencyJustification: state.setNewCompetencyJustification,
    setNewCompetencyName: state.setNewCompetencyName,
    setNewSkillCategory: state.setNewSkillCategory,
    setNewSkillName: state.setNewSkillName,
    setPendingDraftData,
    setPreferredCandidateCount: state.setPreferredCandidateCount,
    setPublishingPlatforms: state.setPublishingPlatforms,
    setSalaryInfo: state.setSalaryInfo,
    setSalaryPanelExpanded: state.setSalaryPanelExpanded,
    setSearchPhase: state.setSearchPhase,
    setShowAddBenefitModal: state.setShowAddBenefitModal,
    setShowAddCompetencyModal: state.setShowAddCompetencyModal,
    setShowAddSkillModal: state.setShowAddSkillModal,
    setShowCalibrationModal: state.setShowCalibrationModal,
    setShowClearDraftConfirm: state.setShowClearDraftConfirm,
    setShowCustomQuestionForm: state.setShowCustomQuestionForm,
    setShowEditCriteriaModal: state.setShowEditCriteriaModal,
    setShowMoreIdeas: state.setShowMoreIdeas,
    setShowSkipCompetenciesWarning: state.setShowSkipCompetenciesWarning,
    setShowUploadModal: state.setShowUploadModal,
    setTechnicalSkills: state.setTechnicalSkills,
    setUploadedFile: state.setUploadedFile,
    showAddBenefitModal: state.showAddBenefitModal,
    showAddCompetencyModal: state.showAddCompetencyModal,
    showAddSkillModal: state.showAddSkillModal,
    showCalibrationModal: state.showCalibrationModal,
    showClearDraftConfirm: state.showClearDraftConfirm,
    showCustomQuestionForm: state.showCustomQuestionForm,
    showEditCriteriaModal: state.showEditCriteriaModal,
    showMoreIdeas: state.showMoreIdeas,
    showSkipCompetenciesWarning: state.showSkipCompetenciesWarning,
    showUploadModal: state.showUploadModal,
    stageTransition: state.stageTransition,
    startGlobalSearch,
    technicalSkills: state.technicalSkills,
    toggleWSIQuestionSelection,
    toolCalling: hooks.toolCalling,
    trackFieldChange: hooks.trackFieldChange,
    typeText,
    updateLanguages: state.updateLanguages,
    updateWSIQuestionCorrectOption, updateWSIQuestionExpectedAnswer,
    wizardGreeting: state.wizardGreeting,
    wizardMode: state.wizardMode,
    wsiCandidates: state.wsiCandidates,
    wsiQualityGates,
    wsiQuestions: state.wsiQuestions,
    isOpen,
  }
}
