"use client"

import type { CandidatesPageModalsProps } from "./CandidatesPageModals.types"
import { CandidatesContactModals } from "./CandidatesContactModals"
import { CandidatesCoreModals } from "./CandidatesCoreModals"
import { CandidatesSearchModals } from "./CandidatesSearchModals"

export function CandidatesPageModals(props: CandidatesPageModalsProps) {
  return (
    <>
      <CandidatesContactModals
        selectedCandidateForAction={props.selectedCandidateForAction}
        contactModalCandidate={props.contactModalCandidate}
        showContactModal={props.showContactModal}
        contactModalAction={props.contactModalAction}
        setShowContactModal={props.setShowContactModal}
        setSelectedCandidateForAction={props.setSelectedCandidateForAction}
        setContactModalCandidate={props.setContactModalCandidate}
        setContactModalAction={props.setContactModalAction}
        handleSendMessage={props.handleSendMessage}
        showScheduleModal={props.showScheduleModal}
        setShowScheduleModal={props.setShowScheduleModal}
        handleScheduleComplete={props.handleScheduleComplete}
        unifiedModalOpen={props.unifiedModalOpen}
        unifiedModalCandidate={props.unifiedModalCandidate}
        unifiedModalSelectedCandidates={props.unifiedModalSelectedCandidates}
        unifiedModalType={props.unifiedModalType}
        lastSearchQuery={props.lastSearchQuery}
        handleUnifiedModalClose={props.handleUnifiedModalClose}
        handleUnifiedModalSend={props.handleUnifiedModalSend}
        showSendEmailModal={props.showSendEmailModal}
        setShowSendEmailModal={props.setShowSendEmailModal}
        emailCandidateSelected={props.emailCandidateSelected}
        setEmailCandidateSelected={props.setEmailCandidateSelected}
      />

      <CandidatesCoreModals
        showComparisonModal={props.showComparisonModal}
        setShowComparisonModal={props.setShowComparisonModal}
        selectedCandidatesForBatch={props.selectedCandidatesForBatch}
        sortedCandidates={props.sortedCandidates}
        candidates={props.candidates}
        handleNavigateToFullProfile={props.handleNavigateToFullProfile}
        handleScheduleInterview={props.handleScheduleInterview}
        handleContactCandidate={props.handleContactCandidate}
        showCandidatePage={props.showCandidatePage}
        selectedCandidate={props.selectedCandidate}
        handleCloseCandidatePage={props.handleCloseCandidatePage}
        showAddCandidateModal={props.showAddCandidateModal}
        setShowAddCandidateModal={props.setShowAddCandidateModal}
        preSelectedListForModal={props.preSelectedListForModal}
        setPreSelectedListForModal={props.setPreSelectedListForModal}
        handleAddCandidate={props.handleAddCandidate}
        setCandidateListsForModal={props.setCandidateListsForModal}
        bulkJobVacancies={props.bulkJobVacancies}
        candidateListsForModal={props.candidateListsForModal}
        handleCandidatePageOpen={props.handleCandidatePageOpen}
        showBatchApproval={props.showBatchApproval}
        setShowBatchApproval={props.setShowBatchApproval}
        convertCandidatesForBatch={props.convertCandidatesForBatch}
        handleBatchApprovalComplete={props.handleBatchApprovalComplete}
        wsiCandidateForScreening={props.wsiCandidateForScreening}
        setWsiCandidateForScreening={props.setWsiCandidateForScreening}
        showWSITextModal={props.showWSITextModal}
        setShowWSITextModal={props.setShowWSITextModal}
        showWSIVoiceModal={props.showWSIVoiceModal}
        setShowWSIVoiceModal={props.setShowWSIVoiceModal}
        handleWSIScreeningComplete={props.handleWSIScreeningComplete}
        showWSIInviteModal={props.showWSIInviteModal}
        setShowWSIInviteModal={props.setShowWSIInviteModal}
        wsiInviteCandidate={props.wsiInviteCandidate}
        setWsiInviteCandidate={props.setWsiInviteCandidate}
        showRubricModal={props.showRubricModal}
        setShowRubricModal={props.setShowRubricModal}
        rubricCandidate={props.rubricCandidate}
        setRubricCandidate={props.setRubricCandidate}
        rubricEvaluationData={props.rubricEvaluationData}
        setRubricEvaluationData={props.setRubricEvaluationData}
        showRevealModal={props.showRevealModal}
        setShowRevealModal={props.setShowRevealModal}
        revealCandidate={props.revealCandidate}
        setRevealCandidate={props.setRevealCandidate}
        handleRevealContact={props.handleRevealContact}
        revealType={props.revealType}
        showCVPreviewModal={props.showCVPreviewModal}
        setShowCVPreviewModal={props.setShowCVPreviewModal}
        parsedCVData={props.parsedCVData}
        setParsedCVData={props.setParsedCVData}
        handleCVConfirmed={props.handleCVConfirmed}
      />

      <CandidatesSearchModals
        showCreditConfirmation={props.showCreditConfirmation}
        setShowCreditConfirmation={props.setShowCreditConfirmation}
        creditEstimate={props.creditEstimate}
        pearchSearchOptions={props.pearchSearchOptions}
        setPearchSearchOptions={props.setPearchSearchOptions}
        setPendingSearchRequest={props.setPendingSearchRequest}
        handleConfirmPearchSearch={props.handleConfirmPearchSearch}
        showGlobalExpansionConfirm={props.showGlobalExpansionConfirm}
        setShowGlobalExpansionConfirm={props.setShowGlobalExpansionConfirm}
        lastSuccessfulQuery={props.lastSuccessfulQuery}
        lastSearchQuery={props.lastSearchQuery}
        localResultsCount={props.localResultsCount}
        isExpandingToGlobal={props.isExpandingToGlobal}
        handleExpandToGlobal={props.handleExpandToGlobal}
        showSourceChangeModal={props.showSourceChangeModal}
        setShowSourceChangeModal={props.setShowSourceChangeModal}
        pendingSourceChange={props.pendingSourceChange}
        setPendingSourceChange={props.setPendingSourceChange}
        confirmSourceChange={props.confirmSourceChange}
        showContactFilterModal={props.showContactFilterModal}
        setShowContactFilterModal={props.setShowContactFilterModal}
        pendingContactFilter={props.pendingContactFilter}
        setPendingContactFilter={props.setPendingContactFilter}
        confirmContactFilterChange={props.confirmContactFilterChange}
        showSaveAsArchetypeModal={props.showSaveAsArchetypeModal}
        setShowSaveAsArchetypeModal={props.setShowSaveAsArchetypeModal}
        searchResults={props.searchResults}
        isCreatingArchetype={props.isCreatingArchetype}
        setIsCreatingArchetype={props.setIsCreatingArchetype}
        archetypeCreationStep={props.archetypeCreationStep}
        setArchetypeCreationStep={props.setArchetypeCreationStep}
        newArchetypeData={props.newArchetypeData}
        setNewArchetypeData={props.setNewArchetypeData}
        setUserArchetypes={props.setUserArchetypes}
        setChatMessages={props.setChatMessages}
        showAdvancedSearch={props.showAdvancedSearch}
        setShowAdvancedSearch={props.setShowAdvancedSearch}
        activeSearchFilters={props.activeSearchFilters}
        setActiveSearchFilters={props.setActiveSearchFilters}
        hideViewedCandidates={props.hideViewedCandidates}
        showAddToListModal={props.showAddToListModal}
        setShowAddToListModal={props.setShowAddToListModal}
        addToListCandidateIds={props.addToListCandidateIds}
        setAddToListCandidateIds={props.setAddToListCandidateIds}
        addToListCandidateNames={props.addToListCandidateNames}
        setAddToListCandidateNames={props.setAddToListCandidateNames}
        showShareSearchModal={props.showShareSearchModal}
        setShowShareSearchModal={props.setShowShareSearchModal}
        shareSearchTitle={props.shareSearchTitle}
        setShareSearchTitle={props.setShareSearchTitle}
        shareSearchCandidates={props.shareSearchCandidates}
        setShareSearchCandidates={props.setShareSearchCandidates}
        showAddListToVacanciesModal={props.showAddListToVacanciesModal}
        setShowAddListToVacanciesModal={props.setShowAddListToVacanciesModal}
        selectedListForVacancies={props.selectedListForVacancies}
        setSelectedListForVacancies={props.setSelectedListForVacancies}
        showAddToVacancyModal={props.showAddToVacancyModal}
        setShowAddToVacancyModal={props.setShowAddToVacancyModal}
        selectedCandidatesForBatch={props.selectedCandidatesForBatch}
        setSelectedCandidatesForBatch={props.setSelectedCandidatesForBatch}
        candidates={props.candidates}
        user={props.user}
        showUnsavedWarningModal={props.showUnsavedWarningModal}
        setShowUnsavedWarningModal={props.setShowUnsavedWarningModal}
        setPendingTabChange={props.setPendingTabChange}
        handleSaveAllAndExit={props.handleSaveAllAndExit}
        handleExitWithoutSaving={props.handleExitWithoutSaving}
        unsavedPearchCandidates={props.unsavedPearchCandidates}
        isSavingToBase={props.isSavingToBase}
        showEditQueryModal={props.showEditQueryModal}
        setShowEditQueryModal={props.setShowEditQueryModal}
        editQueryValue={props.editQueryValue}
        getActiveSearchFiltersCount={props.getActiveSearchFiltersCount}
        searchSource={props.searchSource}
        setSearchSource={props.setSearchSource}
        setSearchTerm={props.setSearchTerm}
        setLastSearchQuery={props.setLastSearchQuery}
        setLastSearchMode={props.setLastSearchMode}
        setLastSearchEntities={props.setLastSearchEntities}
        setLastSearchMetadata={props.setLastSearchMetadata}
        executeSearch={props.executeSearch}
        previewSuggestion={props.previewSuggestion}
        setPreviewSuggestion={props.setPreviewSuggestion}
        previewingUserArchetype={props.previewingUserArchetype}
        setPreviewingUserArchetype={props.setPreviewingUserArchetype}
        buildFiltersFromTags={props.buildFiltersFromTags}
        setLiaPromptValue={props.setLiaPromptValue}
        setActiveSearchTab={props.setActiveSearchTab}
        archetypeToDelete={props.archetypeToDelete}
        setArchetypeToDelete={props.setArchetypeToDelete}
      />
    </>
  )
}
