"""
Pydantic schemas for the Job Creation wizard.

Aligns with WSI methodology F1-F6 outputs.
EnrichedJobDescription matches the output schema from WSI_FLOW_PONTA_A_PONTA.md F1.C.
"""

from typing import Dict, List, Literal, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# F1: JD Enrichment output
# ---------------------------------------------------------------------------

class TechnicalSkill(BaseModel):
    skill: str
    contexto: str = ""
    proficiency_level: Optional[str] = None
    market_demand_trend: Literal["rising", "stable", "declining"] = "stable"


class BehavioralCompetency(BaseModel):
    competencia: str
    contexto: str = ""
    trait_big_five: Literal[
        "openness", "conscientiousness", "extraversion",
        "agreeableness", "stability"
    ] = "conscientiousness"
    assessment_methods: List[str] = Field(default_factory=list)


class ContextSignals(BaseModel):
    nivel_autonomia: Literal["baixo", "medio", "alto"] = "medio"
    nivel_inovacao: Literal["baixo", "medio", "alto"] = "medio"
    nivel_pressao: Literal["baixo", "medio", "alto"] = "medio"
    nivel_colaboracao: Literal["baixo", "medio", "alto"] = "medio"


# DUPLICATE_OF_INTENT: app/schemas/jd_enrichment.py:130 — PT-BR job_creation extractor variant with field names in Portuguese (titulo_padronizado/senioridade_confirmada/responsabilidades); intentional split, canonical is English JD enrichment
class EnrichedJobDescription(BaseModel):
    """Output of F1.C — LLM JD enrichment.

    Matches the schema from WSI_FLOW_PONTA_A_PONTA.md.
    """
    titulo_padronizado: str = ""
    senioridade_confirmada: str = ""
    about_role: str = ""
    about_company: str = ""  # B5b: seção "Sobre a empresa" (grounded em company context)
    responsabilidades: List[str] = Field(default_factory=list)
    skills_obrigatorias: List[TechnicalSkill] = Field(default_factory=list)
    skills_desejaveis: List[str] = Field(default_factory=list)
    competencias_comportamentais: List[BehavioralCompetency] = Field(default_factory=list)
    context_signals: ContextSignals = Field(default_factory=ContextSignals)
    alteracoes_realizadas: List[str] = Field(default_factory=list)
    fairness_corrections: List[str] = Field(default_factory=list)
    wsi_quality_score: float = 0.0
    wsi_quality_warnings: List[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Pre-F1: Intake structured extraction
# ---------------------------------------------------------------------------

class IntakeExtraction(BaseModel):
    """Structured output from intake LLM call."""
    titulo: str = ""
    departamento: str = ""
    senioridade: str = ""
    localizacao: str = ""
    modelo_trabalho: Literal["remoto", "hibrido", "presencial", ""] = ""
    descricao_bruta: str = ""
    confidence: float = 0.0


# ---------------------------------------------------------------------------
# F2: Big Five extraction
# ---------------------------------------------------------------------------

class BigFiveExtraction(BaseModel):
    """Output of F2 — Big Five profile extracted from enriched JD."""
    openness: float = Field(default=0.5, ge=0.0, le=1.0)
    conscientiousness: float = Field(default=0.5, ge=0.0, le=1.0)
    extraversion: float = Field(default=0.5, ge=0.0, le=1.0)
    agreeableness: float = Field(default=0.5, ge=0.0, le=1.0)
    stability: float = Field(default=0.5, ge=0.0, le=1.0)
    evidences: Dict[str, List[str]] = Field(default_factory=dict)


# ---------------------------------------------------------------------------
# F4: Seniority resolution
# ---------------------------------------------------------------------------

class SeniorityResult(BaseModel):
    """Output of F4 — resolved seniority with confidence."""
    final_level: str = "pleno"
    confidence: float = 0.0
    signals_used: List[Dict] = Field(default_factory=list)
    display_name: str = "Pleno"


# ---------------------------------------------------------------------------
# F6: Question generation output (single question)
# ---------------------------------------------------------------------------

class GeneratedQuestion(BaseModel):
    """Single question generated by F6 LLM."""
    question: str
    ideal_answer: str
    scoring_rubric: Dict[str, str] = Field(default_factory=dict)
    framework: Literal["CBI", "Bloom", "Dreyfus", "BigFive"] = "CBI"
    block: Literal["technical", "behavioral"] = "technical"
    competency: Literal["technical", "behavioral", "logistical"] = "technical"
    skill: str = ""
    trait_ocean: Optional[str] = None
    bloom_level: Optional[int] = None
    dreyfus_level: Optional[int] = None
    weight: float = 1.0

    # Sprint B Phase 3 — WSI Skill Probed (taxonomia hierarquica)
    skill_probed: Optional[str] = None
    skill_parent: Optional[str] = None
    skill_classification_source: Optional[str] = None  # "llm" | "heuristic" | "default"
