"""Talent Pool Domain - Action definitions."""
from app.domains.base import DomainAction

TALENT_POOL_ACTIONS = [
    DomainAction(action_id="create_talent_pool", name="Criar Banco de Talentos", description="Cria novo banco de talentos vivo com nome, arquétipo de candidato ideal e critérios de triagem. Aciona quando empresa quer manter pool de candidatos para posições recorrentes.", required_params=["name"], optional_params=["archetype_id", "description"], requires_confirmation=False, examples=('cria pool de talentos', 'monta banco de talentos de devs')),
    DomainAction(action_id="list_talent_pools", name="Listar Bancos de Talentos", description="Lista bancos de talentos ativos com nome, arquétipo, contagem de candidatos e última atualização. Aciona quando recruiter quer gerenciar pools ou selecionar pool para ação.", required_params=[], optional_params=["status"], requires_confirmation=False, examples=('lista pools de talentos', 'mostra meus pools')),
    DomainAction(action_id="add_to_pool", name="Adicionar ao Pool", description="Adiciona candidatos ao banco de talentos com origem registrada para rastreamento. Aciona após processo seletivo para manter candidatos aprovados não contratados ou ao receber indicações.", required_params=["pool_id", "candidate_ids"], optional_params=["origin"], requires_confirmation=False, examples=('adiciona candidato ao pool', 'guarda este perfil no banco de talentos')),
    DomainAction(action_id="move_pool_to_job", name="Mover para Vaga", description="Migra candidatos do pool para uma vaga específica na etapa selecionada, iniciando processo seletivo. Requer confirmação. Aciona quando vaga abre e candidatos do pool são elegíveis.", required_params=["pool_id", "job_id", "candidate_ids", "target_stage"], optional_params=[], requires_confirmation=True, examples=('move pool pra uma vaga', 'aproveita este pool na vaga 45')),
    DomainAction(action_id="get_pool_candidates", name="Ver Candidatos do Pool", description="Lista candidatos de um banco de talentos com estágios, scores e disponibilidade para análise e ação. Aciona quando recruiter quer ver quem está no pool ou selecionar candidatos para vaga.", required_params=["pool_id"], optional_params=["stage", "limit"], requires_confirmation=False, examples=('mostra candidatos do pool', 'quem tem neste banco de talentos?')),
    DomainAction(action_id="create_job_from_pool", name="Criar Vaga do Pool", description="Cria nova vaga a partir de um banco de talentos herdando arquétipo, critérios e configurações do pool. Requer confirmação. Aciona quando nova posição tem perfil igual ao pool existente.", required_params=["pool_id"], optional_params=[], requires_confirmation=True, examples=('cria vaga usando candidatos do pool', 'abre posição pra este pool')),
]
