"""Canonical compliance tests for OfferConciergeAgent.

Generated by skill create-canonical-agent.
Cobre as 4 dimensões cross-cutting (G7 sensor) + HITL invariante offer.
Todos os testes são RED (falharão até a implementação estar completa).
"""
import inspect
import pytest


class TestOfferConciergeCanonicalAnatomy:
    """G7 — Verifica anatomia canônica do OfferConciergeAgent."""

    def test_inherits_canonical_bases(self):
        from app.domains.offer.agents.offer_concierge_agent import OfferConciergeAgent
        from lia_agents_core.langgraph_react_base import LangGraphReActBase
        from lia_agents_core.enhanced_agent_mixin import EnhancedAgentMixin

        assert issubclass(OfferConciergeAgent, LangGraphReActBase), (
            "OfferConciergeAgent deve herdar LangGraphReActBase"
        )
        assert issubclass(OfferConciergeAgent, EnhancedAgentMixin), (
            "OfferConciergeAgent deve herdar EnhancedAgentMixin"
        )

    def test_registered_with_canonical_aliases(self):
        from app.shared.agents.agent_registry import get_agent_registry
        registry = get_agent_registry()

        assert "offer_concierge" in registry, (
            "offer_concierge deve estar registrado via @register_agent"
        )
        aliases = registry.get("offer_concierge", {}).get("aliases", [])
        expected = {"offer", "proposta", "carta_oferta", "negociacao_oferta"}
        assert expected.issubset(set(aliases)), (
            f"Aliases canônicos ausentes. Esperados: {expected}, encontrados: {aliases}"
        )

    def test_invokes_fairness_guard(self):
        from app.domains.offer.agents.offer_concierge_agent import OfferConciergeAgent
        src = inspect.getsource(OfferConciergeAgent.process)
        assert "FairnessGuard" in src, (
            "process() deve invocar FairnessGuard (FAR-2). "
            "Adicionar bloco FAR-2 canonical antes de qualquer call LLM."
        )

    def test_strips_pii_before_llm(self):
        from app.domains.offer.agents.offer_concierge_agent import OfferConciergeAgent
        src = inspect.getsource(OfferConciergeAgent.process)
        assert "strip_pii_for_llm_prompt" in src, (
            "process() deve chamar strip_pii_for_llm_prompt antes de _process_langgraph. "
            "Padrão: safe_message = strip_pii_for_llm_prompt(input.message)"
        )

    def test_logs_decision_via_audit_service(self):
        from app.domains.offer.agents.offer_concierge_agent import OfferConciergeAgent
        src = inspect.getsource(OfferConciergeAgent.process)
        assert "audit_service" in src or "log_decision" in src, (
            "process() deve chamar audit_service.log_decision (ACH-026). "
            "Obrigatório pós-processamento para LGPD/EU AI Act compliance."
        )

    def test_hitl_message_types_defined(self):
        from app.domains.offer.agents.offer_concierge_agent import OfferConciergeAgent
        hitl_types = OfferConciergeAgent._HITL_MESSAGE_TYPES

        assert isinstance(hitl_types, frozenset), (
            "_HITL_MESSAGE_TYPES deve ser frozenset para imutabilidade"
        )
        required = {"send_counter_proposal", "accept_negotiation_round", "extend_deadline", "confirm_hire"}
        assert required.issubset(hitl_types), (
            f"_HITL_MESSAGE_TYPES incompleto. Esperado: {required}, encontrado: {hitl_types}"
        )

    def test_uses_input_company_id_not_payload(self):
        from app.domains.offer.agents.offer_concierge_agent import OfferConciergeAgent
        process_src = inspect.getsource(OfferConciergeAgent.process)

        assert "input.company_id" in process_src, (
            "process() deve usar input.company_id (do JWT via AgentInput), "
            "NUNCA aceitar company_id do payload LLM. Multi-tenancy invariante."
        )


class TestOfferConciergeTools:
    """Valida que as tools do agente seguem os padrões canônicos."""

    def test_tools_list_not_empty(self):
        from app.domains.offer.agents.offer_tool_registry import get_offer_concierge_tools
        tools = get_offer_concierge_tools()
        assert len(tools) >= 5, (
            "get_offer_concierge_tools() deve retornar pelo menos 5 tools: "
            "get_offer_status, get_negotiation_context, suggest_next_start_date, "
            "escalate_to_recruiter, log_negotiation_event."
        )

    def test_tools_have_when_to_use(self):
        from app.domains.offer.agents.offer_tool_registry import get_offer_concierge_tools
        tools = get_offer_concierge_tools()
        for tool in tools:
            assert "when_to_use" in (tool.description or ""), (
                f"Tool '{tool.name}' sem 'when_to_use' na description. "
                "Canonical pattern exige when_to_use + when_not_to_use para precision routing."
            )

    def test_escalate_to_recruiter_exists(self):
        from app.domains.offer.agents.offer_tool_registry import get_offer_concierge_tools
        tools = get_offer_concierge_tools()
        names = [t.name for t in tools]
        assert "escalate_to_recruiter" in names, (
            "escalate_to_recruiter deve existir nas tools. "
            "HITL invariante: toda ação sensível passa por esta tool."
        )


class TestOfferYAML:
    """Valida que o YAML do domínio offer cobre N2+N3."""

    def test_offer_yaml_exists(self):
        import os
        base = "/home/runner/workspace/lia-agent-system"
        path = os.path.join(base, "app/prompts/domains/offer.yaml")
        assert os.path.exists(path), (
            f"offer.yaml não encontrado em {path}. "
            "Criar via create-canonical-agent skill passo 5."
        )

    def test_offer_yaml_has_concierge_scope(self):
        import yaml
        import os
        base = "/home/runner/workspace/lia-agent-system"
        with open(os.path.join(base, "app/prompts/domains/offer.yaml")) as f:
            data = yaml.safe_load(f)
        assert "concierge_scope_in" in data, (
            "offer.yaml deve ter seção concierge_scope_in cobrindo N2."
        )

    def test_offer_yaml_has_negotiation_policy(self):
        import yaml
        import os
        base = "/home/runner/workspace/lia-agent-system"
        with open(os.path.join(base, "app/prompts/domains/offer.yaml")) as f:
            data = yaml.safe_load(f)
        assert "negotiation_policy" in data, (
            "offer.yaml deve ter seção negotiation_policy cobrindo N3 gating."
        )
