"""
Wizard Smart Orchestrator API - LLM-powered Job Wizard Graph Execution.

This endpoint executes the JobWizardGraph with LLM processing,
enabling intelligent intent classification, field extraction,
tool routing, and response generation.
"""
import logging
from typing import Any

from fastapi import APIRouter, Depends
from lia_agents_core.state_machine import WizardStage
from pydantic import BaseModel, Field

from app.auth.dependencies import get_current_user_or_demo, get_user_company_id
from app.auth.models import User
from app.core.database import AsyncSessionLocal
from app.domains.job_management.tools.job_wizard_tools import generate_enriched_jd  # noqa: F401
from app.domains.job_management.services.job_vacancy_service import job_vacancy_service
from app.shared.tenant_session import create_session_id
from app.domains.cv_screening.services.screening_question_set_service import (
    get_screening_question_set_service,
    ScreeningQuestionSetService,
)

router = APIRouter()
logger = logging.getLogger(__name__)



FRONTEND_TO_BACKEND_STAGE: dict[str, str] = {
    "input-evaluation": WizardStage.TITLE_DEPARTMENT.value,
    "title-department": WizardStage.TITLE_DEPARTMENT.value,
    "job-summary": WizardStage.JOB_SUMMARY.value,
    "jd-enrichment": WizardStage.JOB_SUMMARY.value,
    "job_summary": WizardStage.JOB_SUMMARY.value,
    "salary": WizardStage.SALARY.value,
    "competencies": WizardStage.COMPETENCIES.value,
    "wsi-questions": WizardStage.SCREENING.value,
    "screening": WizardStage.SCREENING.value,
    "review-publish": WizardStage.REVIEW.value,
    "review": WizardStage.REVIEW.value,
    "complete": WizardStage.COMPLETE.value,
    "initial": WizardStage.INITIAL.value,
}

BACKEND_TO_FRONTEND_STAGE: dict[str, str] = {
    WizardStage.INITIAL.value: "input-evaluation",
    WizardStage.TITLE_DEPARTMENT.value: "input-evaluation",
    WizardStage.JOB_SUMMARY.value: "jd-enrichment",
    WizardStage.SALARY.value: "salary",
    WizardStage.COMPETENCIES.value: "competencies",
    WizardStage.SCREENING.value: "wsi-questions",
    WizardStage.REVIEW.value: "review-publish",
    WizardStage.COMPLETE.value: "complete",
}


class SmartOrchestrateRequest(BaseModel):
    """Request for smart orchestration using LLM-powered graph."""
    message: str = Field(..., description="User message to process")
    current_stage: str = Field(
        default="input-evaluation",
        description="Current wizard stage (frontend format)"
    )
    collected_data: dict[str, Any] = Field(
        default_factory=dict,
        description="Data already collected in the wizard"
    )
    conversation_history: list[dict[str, str]] = Field(
        default_factory=list,
        description="Previous conversation messages"
    )
    conversation_id: str | None = Field(
        None,
        description="Conversation ID for context continuity"
    )
    company_id: str | None = Field(None, description="Company ID override")
    user_id: str | None = Field(None, description="User ID override")


class SmartOrchestrateResponse(BaseModel):
    """Response from smart orchestration."""
    success: bool = Field(..., description="Whether processing succeeded")
    lia_message: str = Field(
        default="",
        description="LIA's response generated by LLM"
    )
    detected_criteria: dict[str, Any] = Field(
        default_factory=dict,
        description="Extracted fields from user message"
    )
    next_stage: str | None = Field(
        None,
        description="Next stage if transition occurred (frontend format)"
    )
    auto_transition: bool = Field(
        default=False,
        description="Whether to auto-transition to next stage"
    )
    tool_results: list[dict[str, Any]] = Field(
        default_factory=list,
        description="Results from executed tools"
    )
    confidence: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Overall confidence of the response"
    )
    reasoning_steps: list[str] = Field(
        default_factory=list,
        description="Reasoning steps for debugging"
    )
    intent: str | None = Field(
        None,
        description="Detected user intent"
    )
    error: str | None = Field(
        None,
        description="Error message if processing failed"
    )
    awaiting_confirmation: bool = Field(
        default=False,
        description="Whether the wizard is blocked waiting for user confirmation"
    )
    job_vacancy_id: str | None = Field(
        None,
        description="ID of created job vacancy when wizard completes"
    )
    job_published: bool = Field(
        default=False,
        description="Whether the job was successfully published to database"
    )
    conversation_id: str | None = Field(
        None,
        description="Session/conversation ID — send back in next request to maintain multi-turn memory"
    )












@router.post("/smart-orchestrate", response_model=SmartOrchestrateResponse)
async def smart_orchestrate(
    request: SmartOrchestrateRequest,
    current_user: User = Depends(get_current_user_or_demo),
) -> SmartOrchestrateResponse:
    """
    Execute the JobWizardGraph with LLM processing.
    
    This endpoint runs the complete LangGraph-style state machine,
    including:
    1. Intent classification (what does the user want?)
    2. Field extraction (what data is being provided?)
    3. Tool routing (should we call any tools?)
    4. Tool execution (execute matched tools)
    5. Response generation (generate LIA's response)
    6. Stage transition (should we move to next stage?)
    
    Returns:
        SmartOrchestrateResponse with LIA's message and extracted data
    """
    session_id = request.conversation_id or create_session_id(current_user.company_id)
    company_id = request.company_id or get_user_company_id(current_user)
    user_id = request.user_id or (str(current_user.id) if current_user.id is not None else "anonymous")
    
    logger.info(
        f"Smart orchestrate request: stage={request.current_stage}, "
        f"message_len={len(request.message)}, session={session_id}"
    )
    
    try:
        backend_stage = map_frontend_to_backend_stage(request.current_stage)
        
        messages = build_messages_from_history(
            request.conversation_history,
            request.message
        )
        
        initial_state: JobWizardState = {
            "messages": messages,
            "current_stage": backend_stage,
            "job_draft": request.collected_data.copy(),
            "confidence_scores": {},
            "reasoning_steps": [],
            "next_action": None,
            "intent": None,
            "tool_calls": [],
            "tool_results": [],
            "session_id": session_id,
            "company_id": company_id,
            "user_id": user_id,
            "should_continue": False,
            "needs_clarification": False,
            "error": None,
            "response_text": None,
            "extracted_fields": {},
            "current_node": "start",
            "auto_transition": False,
            "awaiting_confirmation": False,
        }
        
        logger.debug(f"Initial state created for session {session_id}")
        
        final_state = await job_wizard_graph.invoke(initial_state)
        
        detected_criteria = normalize_fields_for_frontend(final_state.get("extracted_fields", {}))
        for key, value in final_state.get("job_draft", {}).items():
            if key not in request.collected_data or request.collected_data.get(key) != value:
                if value is not None:
                    detected_criteria[key] = value
        
        current_backend_stage = final_state.get("current_stage", backend_stage)
        next_stage = None
        auto_transition = False
        
        if current_backend_stage != backend_stage:
            next_stage = map_backend_to_frontend_stage(current_backend_stage)
            auto_transition = True
        elif final_state.get("should_continue"):
            auto_transition = True
        
        # generate_enriched_jd is now called autonomously by the WizardReActAgent
        # when the stage is jd-enrichment and title is available (see wizard_system_prompt.py).
        # The endpoint no longer bypasses agent autonomy by calling it directly.
        tool_results = final_state.get("tool_results", [])
        
        awaiting_confirmation = final_state.get("awaiting_confirmation", False)
        
        logger.debug(
            f"Stage mapping validation: frontend='{request.current_stage}' -> "
            f"backend='{backend_stage}' -> current='{current_backend_stage}' -> "
            f"frontend_next='{next_stage}', awaiting_confirmation={awaiting_confirmation}"
        )
        
        job_vacancy_id = None
        job_published = False

        # Auto-save draft progress after each successful agent turn (not only at completion).
        # Persists collected_data + detected_criteria into Redis so the session can be
        # recovered if the user refreshes mid-wizard.
        if detected_criteria and current_backend_stage != WizardStage.COMPLETE.value:
            try:
                import json

                from app.core.config import settings
                merged_progress = {**request.collected_data, **detected_criteria}
                if merged_progress.get("title") or merged_progress.get("job_title"):
                    redis_key = f"wizard_draft:{session_id}"
                    async with __import__("redis.asyncio", fromlist=["Redis"]).Redis.from_url(
                        settings.REDIS_URL, decode_responses=True
                    ) as redis_client:
                        await redis_client.setex(redis_key, 86400, json.dumps(merged_progress))
                    logger.debug(f"[wizard] Draft auto-saved to Redis: key={redis_key}")
            except Exception as draft_err:
                logger.debug(f"[wizard] Draft auto-save skipped: {draft_err}")

        if current_backend_stage == WizardStage.COMPLETE.value:
            merged_draft = {**request.collected_data, **detected_criteria}
            
            job_vacancy_id = await finalize_job_vacancy_from_wizard(
                job_draft=merged_draft,
                session_id=session_id,
                company_id=company_id,
                user_id=user_id,
            )
            
            if job_vacancy_id:
                job_published = True
                logger.info(f"🎉 Wizard completed! Job vacancy created: {job_vacancy_id}")
            else:
                logger.warning("⚠️ Wizard completed but job vacancy creation failed")
        
        response = SmartOrchestrateResponse(
            success=final_state.get("error") is None,
            lia_message=final_state.get("response_text") or "",
            detected_criteria=detected_criteria,
            next_stage=next_stage,
            auto_transition=auto_transition and not awaiting_confirmation,
            tool_results=final_state.get("tool_results", []),
            confidence=calculate_overall_confidence(final_state),
            reasoning_steps=final_state.get("reasoning_steps", []),
            intent=final_state.get("intent"),
            error=final_state.get("error"),
            awaiting_confirmation=awaiting_confirmation,
            job_vacancy_id=job_vacancy_id,
            job_published=job_published,
            conversation_id=session_id,
        )
        
        logger.info(
            f"Smart orchestrate complete: session={session_id}, "
            f"intent={response.intent}, extracted_fields={len(detected_criteria)}, "
            f"confidence={response.confidence:.2f}"
        )
        
        return response
        
    except Exception as e:
        logger.error(f"Smart orchestrate error: {e}", exc_info=True)
        return SmartOrchestrateResponse(
            success=False,
            lia_message="Desculpe, ocorreu um erro ao processar sua mensagem. Por favor, tente novamente.",
            detected_criteria={},
            next_stage=None,
            auto_transition=False,
            tool_results=[],
            confidence=0.0,
            reasoning_steps=[f"Error: {str(e)}"],
            intent=None,
            error=str(e),
            awaiting_confirmation=False,
            job_vacancy_id=None,
            job_published=False,
            conversation_id=session_id if 'session_id' in locals() else None,
        )


@router.post("/react-orchestrate", response_model=SmartOrchestrateResponse)
async def react_orchestrate(
    request: SmartOrchestrateRequest,
    current_user: User = Depends(get_current_user_or_demo),
) -> SmartOrchestrateResponse:
    # multi-tenancy: function already calls _require_company_id or equivalent (sensor false positive)
    """DEPRECATED — alias for /smart-orchestrate.

    Phase 4D simplification: USE_REACT_AGENTS feature flag was never enabled
    in any environment (.env files don't set it). Removed the legacy
    WizardReActAgent branch entirely. /react-orchestrate now always delegates
    to smart_orchestrate, which uses canonical WizardSessionService.
    """
    logger.warning(
        "[DEPRECATED] /api/v1/wizard/react-orchestrate called — alias to "
        "canonical /smart-orchestrate. Migrate FE to /api/v1/wizard/message "
        "(telemetry tag: phase4d.legacy_react_alias)."
    )
    return await smart_orchestrate(request, current_user)


@router.get("/stage-mapping", response_model=None)
async def get_stage_mapping() -> dict[str, Any]:
    """
    Get the mapping between frontend and backend stage names.
    
    Useful for debugging stage transitions.
    """
    return {
        "frontend_to_backend": FRONTEND_TO_BACKEND_STAGE,
        "backend_to_frontend": BACKEND_TO_FRONTEND_STAGE,
        "backend_stages": [stage.value for stage in WizardStage],
    }
