from __future__ import annotations

from app.domains.base import DomainAction

CV_SCREENING_ACTIONS: list[DomainAction] = [
    DomainAction(action_id="parse_cv", name="Analisar CV", description="Analisa e extrai dados estruturados do currículo: experiências, competências, formação, idiomas e contatos. Aciona como primeira etapa ao receber candidatura ou ao adicionar candidato manualmente ao pipeline."),
    DomainAction(action_id="auto_screen", name="Triagem automática", description="Executa triagem automática do candidato contra os requisitos da vaga usando score WSI e rubricas configuradas. Aciona após parse_cv para aprovação/rejeição automática com base em critérios objetivos."),
    DomainAction(action_id="batch_screen", name="Triagem em lote", description="Executa triagem em lote de múltiplos candidatos simultaneamente para ranqueamento eficiente. Aciona quando há acúmulo de candidaturas ou para triagem semanal de novos candidatos."),
    DomainAction(action_id="calculate_wsi_score", name="Calcular WSI", description="Calcula o score WSI (Work Style Interview) do candidato baseado no CV e competências mapeadas para a vaga. Aciona após parse_cv ou quando recruiter quer pontuação para comparação."),
    DomainAction(action_id="rank_candidates", name="Rankear candidatos", description="Ordena candidatos por score WSI e compatibilidade com a vaga para priorização do pipeline. Aciona quando recruiter pede ranqueamento ou antes de apresentar shortlist."),
    DomainAction(action_id="dynamic_cutoff", name="Corte dinâmico", description="Aplica corte dinâmico ao pipeline retendo apenas o top 25% dos candidatos com base nos scores. Aciona quando pipeline está saturado e recruiter precisa focar nos melhores candidatos."),
    DomainAction(action_id="detect_red_flags", name="Detectar red flags", description="Detecta red flags no currículo: gaps não explicados, inconsistências de datas, histórico de rotatividade elevada. Aciona durante triagem para alertar recruiter sobre riscos antes de avançar candidato."),
    DomainAction(action_id="check_saturation", name="Verificar saturação", description="Verifica se o pipeline de candidatos está saturado com volume suficiente para preenchimento da vaga. Aciona para decidir se sourcing deve continuar ou pausar."),
    DomainAction(action_id="classify_bloom", name="Classificar Bloom", description="Classifica respostas do candidato pela Taxonomia de Bloom para avaliar profundidade de raciocínio (do básico ao criativo). Aciona durante avaliação de respostas de entrevistas estruturadas."),
    DomainAction(action_id="classify_dreyfus", name="Classificar Dreyfus", description="Classifica o nível de proficiência do candidato no modelo Dreyfus (novice → expert) para competências técnicas. Aciona na avaliação de seniority para vagas técnicas."),
    DomainAction(action_id="map_big_five", name="Mapear Big Five", description="Mapeia traços comportamentais do candidato no modelo Big Five (abertura, consciência, extroversão, amabilidade, neuroticismo). Aciona na avaliação comportamental de candidatos finalistas."),
    DomainAction(action_id="validate_cbi", name="Validar CBI", description="Valida respostas do candidato contra o framework CBI (Competency-Based Interview) verificando evidências comportamentais. Aciona durante entrevista estruturada para garantir qualidade das evidências coletadas."),
    DomainAction(action_id="generate_report", name="Gerar parecer", description="Gera parecer completo do candidato com score WSI, análise de competências, red flags e recomendação final. Aciona antes de apresentar candidato ao hiring manager."),
    DomainAction(action_id="compare_candidates", name="Comparar candidatos", description="Compara candidatos selecionados lado a lado em dimensões de competência, score e fit cultural. Aciona quando recruiter tem múltiplos finalistas e precisa decidir quem avançar."),
    DomainAction(action_id="calibrate_model", name="Calibrar modelo", description="Calibra o modelo de triagem com feedback explícito do recrutador sobre candidatos aprovados e rejeitados. Aciona periodicamente para melhorar precisão da triagem automática."),
    DomainAction(action_id="explain_score", name="Explicar score", description="Explica detalhadamente como o score WSI do candidato foi calculado, indicando quais competências contribuíram e quais faltam. Aciona quando recruiter ou candidato questiona o resultado."),
    DomainAction(action_id="evaluate_rubric", name="Avaliar rubrica", description="Avalia candidato por rubrica estruturada com critérios e pesos específicos da vaga. Aciona para avaliação padronizada e comparável entre candidatos."),
    DomainAction(action_id="generate_questions", name="Gerar perguntas", description="Gera perguntas de triagem WSI personalizadas para a vaga com base nos requisitos e competências mapeadas. Aciona na configuração de nova vaga ou antes de entrevista estruturada."),
    DomainAction(action_id="adjust_questions", name="Ajustar perguntas", description="Ajusta e refina perguntas de triagem com IA baseado em feedback do recruiter ou resultados anteriores. Aciona quando perguntas estão muito fáceis/difíceis ou não discriminam candidatos."),
    DomainAction(action_id="voice_screening", name="Triagem por voz", description="Executa triagem por voz com candidato usando metodologia WSI via interface de áudio. Aciona quando candidato prefere formato oral ou para agilizar triagem inicial."),
    DomainAction(action_id="normalize_scores", name="Normalizar scores", description="Normaliza scores entre candidatos de diferentes buscas para comparação justa em base comum. Aciona ao combinar resultados de múltiplos processos de triagem."),
    DomainAction(action_id="assess_seniority", name="Avaliar senioridade", description="Avalia e classifica o nível de senioridade do candidato (júnior, pleno, sênior, especialista) com base no CV e respostas. Aciona para alocação correta em vagas de nível específico."),
    DomainAction(action_id="send_feedback", name="Enviar feedback", description="Envia feedback personalizado ao candidato sobre o resultado da triagem com pontos positivos e áreas de desenvolvimento. Aciona após rejeição quando empresa quer oferecer experiência de qualidade."),
    DomainAction(action_id="pre_qualify", name="Pré-qualificar", description="Pré-qualifica candidato com perguntas rápidas antes da triagem formal para filtrar desqualificadores objetivos (localização, salário, disponibilidade). Aciona como etapa zero antes do processo completo."),
]
