"""Interview & Scheduling Domain - Action definitions."""
from app.domains.base import DomainAction

INTERVIEW_SCHEDULING_ACTIONS = [
    DomainAction(
        action_id="schedule_interview",
        name="Agendar Entrevista",
        description="Agendar entrevista com candidato via calendário",
        required_params=["candidate_name", "candidate_email", "interviewer_email", "start_time"],
        optional_params=["job_title", "interview_type", "duration_minutes", "location", "notes"],
        requires_confirmation=True,
    ),
    DomainAction(
        action_id="reschedule_interview",
        name="Reagendar Entrevista",
        description="Reagendar entrevista existente para novo horário",
        required_params=["interview_id", "new_start_time"],
        optional_params=["reason", "notify_participants"],
        requires_confirmation=True,
    ),
    DomainAction(
        action_id="cancel_interview",
        name="Cancelar Entrevista",
        description="Cancelar entrevista agendada",
        required_params=["interview_id"],
        optional_params=["cancellation_reason", "notify_participants"],
        requires_confirmation=True,
    ),
    DomainAction(
        action_id="check_availability",
        name="Verificar Disponibilidade",
        description="Verificar disponibilidade do entrevistador no calendário",
        required_params=["interviewer_email", "date"],
        optional_params=["duration_minutes", "timezone"],
    ),
    DomainAction(
        action_id="generate_self_scheduling_link",
        name="Gerar Link de Auto-agendamento",
        description="Gerar link de auto-agendamento para candidato escolher horário",
        required_params=["candidate_name", "candidate_email", "interviewer_emails"],
        optional_params=["job_title", "interview_type", "duration_minutes", "expires_in_days"],
    ),
    DomainAction(
        action_id="find_common_slots",
        name="Encontrar Horários Comuns",
        description="Encontrar horários disponíveis comuns para todos os participantes",
        required_params=["participant_emails"],
        optional_params=["duration_minutes", "preferred_days", "date_range"],
    ),
    DomainAction(
        action_id="send_reminder",
        name="Enviar Lembrete",
        description="Enviar lembrete de entrevista para participantes",
        required_params=["interview_id"],
        optional_params=["channels", "custom_message"],
        requires_confirmation=True,
    ),
    DomainAction(
        action_id="schedule_reminders",
        name="Agendar Lembretes",
        description="Configurar lembretes automáticos para entrevistas futuras",
        required_params=["interview_id"],
        optional_params=["hours_before", "channels", "recipient_types"],
    ),
    DomainAction(
        action_id="list_today_interviews",
        name="Listar Entrevistas de Hoje",
        description="Listar todas as entrevistas agendadas para hoje",
        required_params=[],
        optional_params=["interviewer_email", "status_filter"],
    ),
    DomainAction(
        action_id="resolve_conflict",
        name="Resolver Conflito de Agenda",
        description="Resolver conflitos de agendamento entre entrevistas",
        required_params=["interview_ids"],
        optional_params=["resolution_strategy", "priority_rules"],
    ),
    DomainAction(
        action_id="start_wsi_interview",
        name="Iniciar Entrevista WSI",
        description="Iniciar entrevista WSI completa com candidato (40-60min)",
        required_params=["candidate_id", "job_vacancy_id"],
        optional_params=["competencies", "interview_mode", "language"],
    ),
    DomainAction(
        action_id="send_question",
        name="Enviar Pergunta",
        description="Enviar pergunta de entrevista para candidato",
        required_params=["interview_id", "question_text"],
        optional_params=["question_type", "competency_target", "time_limit"],
    ),
    DomainAction(
        action_id="analyze_response",
        name="Analisar Resposta",
        description="Analisar resposta do candidato com IA usando metodologia WSI",
        required_params=["interview_id", "response_text"],
        optional_params=["question_context", "competency_target", "expected_level"],
    ),
    DomainAction(
        action_id="transcribe_audio",
        name="Transcrever Áudio",
        description="Transcrever áudio de entrevista por voz",
        required_params=["audio_url"],
        optional_params=["language", "model", "interview_id"],
    ),
    DomainAction(
        action_id="analyze_voice",
        name="Analisar Voz",
        description="Analisar tom de voz e confiança do candidato",
        required_params=["audio_url"],
        optional_params=["interview_id", "candidate_id", "analysis_type"],
    ),
    DomainAction(
        action_id="detect_evasive",
        name="Detectar Resposta Evasiva",
        description="Detectar respostas evasivas do candidato durante entrevista",
        required_params=["interview_id", "response_text"],
        optional_params=["question_context", "threshold"],
    ),
    DomainAction(
        action_id="generate_followup",
        name="Gerar Pergunta de Follow-up",
        description="Gerar pergunta de follow-up baseada na resposta do candidato",
        required_params=["interview_id", "previous_response"],
        optional_params=["competency_target", "depth_level", "question_type"],
    ),
    DomainAction(
        action_id="complete_interview",
        name="Finalizar Entrevista",
        description="Finalizar entrevista e gerar resumo com parecer WSI",
        required_params=["interview_id"],
        optional_params=["final_notes", "recommendation", "generate_report"],
    ),
    DomainAction(
        action_id="interview_qa",
        name="Q&A sobre Entrevista",
        description="Responder dúvidas sobre o processo de entrevista",
        required_params=["question"],
        optional_params=["interview_id", "candidate_id", "context"],
    ),
    DomainAction(
        action_id="start_quick_screening",
        name="Iniciar Triagem Rápida",
        description="Iniciar triagem rápida com candidato (10-15min)",
        required_params=["candidate_id"],
        optional_params=["job_vacancy_id", "screening_type", "questions"],
    ),
]
