"""Interview & Scheduling Domain - Action definitions."""
from app.domains.base import DomainAction

INTERVIEW_SCHEDULING_ACTIONS = [
    DomainAction(
        action_id="schedule_interview",
        name="Agendar Entrevista",
        description="Agenda entrevista entre candidato e entrevistador via calendário com criação de evento, envio de convites e confirmações. Requer confirmação. Aciona quando recruiter ou candidato confirma horário de entrevista.",
        required_params=["candidate_name", "candidate_email", "interviewer_email", "start_time"],
        optional_params=["job_title", "interview_type", "duration_minutes", "location", "notes"],
        requires_confirmation=True,
    ),
    DomainAction(
        action_id="reschedule_interview",
        name="Reagendar Entrevista",
        description="Reagenda entrevista existente para novo horário atualizando eventos no calendário e notificando participantes. Requer confirmação. Aciona quando candidato ou entrevistador solicita novo horário.",
        required_params=["interview_id", "new_start_time"],
        optional_params=["reason", "notify_participants"],
        requires_confirmation=True,
    ),
    DomainAction(
        action_id="cancel_interview",
        name="Cancelar Entrevista",
        description="Cancela entrevista agendada e notifica participantes com motivo da cancelamento. Requer confirmação. Aciona quando entrevista não será realizada por desistência ou indisponibilidade.",
        required_params=["interview_id"],
        optional_params=["cancellation_reason", "notify_participants"],
        requires_confirmation=True,
    ),
    DomainAction(
        action_id="check_availability",
        name="Verificar Disponibilidade",
        description="Verifica disponibilidade do entrevistador no calendário para data e duração específicas. Aciona antes de propor horário ao candidato para garantir slot disponível.",
        required_params=["interviewer_email", "date"],
        optional_params=["duration_minutes", "timezone"],
    ),
    DomainAction(
        action_id="generate_self_scheduling_link",
        name="Gerar Link de Auto-agendamento",
        description="Gera link para candidato escolher horário disponível do entrevistador de forma autônoma sem intervenção do recruiter. Aciona para otimizar agendamento e melhorar experiência do candidato.",
        required_params=["candidate_name", "candidate_email", "interviewer_emails"],
        optional_params=["job_title", "interview_type", "duration_minutes", "expires_in_days"],
    ),
    DomainAction(
        action_id="find_common_slots",
        name="Encontrar Horários Comuns",
        description="Encontra horários comuns disponíveis para múltiplos participantes (painéis com vários entrevistadores). Aciona para agendamento de entrevistas em painel com 2+ entrevistadores.",
        required_params=["participant_emails"],
        optional_params=["duration_minutes", "preferred_days", "date_range"],
    ),
    DomainAction(
        action_id="send_reminder",
        name="Enviar Lembrete",
        description="Envia lembrete de entrevista para candidato e entrevistador com detalhes e instruções de acesso. Requer confirmação. Aciona automaticamente 24h antes ou quando recruiter solicita lembrete manual.",
        required_params=["interview_id"],
        optional_params=["channels", "custom_message"],
        requires_confirmation=True,
    ),
    DomainAction(
        action_id="schedule_reminders",
        name="Agendar Lembretes",
        description="Configura lembretes automáticos recorrentes para entrevistas futuras com canais e timing definidos. Aciona na criação do agendamento para garantir lembretes sem intervenção manual.",
        required_params=["interview_id"],
        optional_params=["hours_before", "channels", "recipient_types"],
    ),
    DomainAction(
        action_id="list_today_interviews",
        name="Listar Entrevistas de Hoje",
        description="Lista todas as entrevistas agendadas para hoje com horários, participantes e status de confirmação. Aciona no briefing diário do recruiter ou quando pede 'qual minha agenda de hoje?'.",
        required_params=[],
        optional_params=["interviewer_email", "status_filter"],
    ),
    DomainAction(
        action_id="resolve_conflict",
        name="Resolver Conflito de Agenda",
        description="Resolve conflitos de agendamento entre entrevistas sobrepostas usando estratégia de priorização configurável. Aciona quando sistema detecta conflito de agenda ou recruiter relata problema de scheduling.",
        required_params=["interview_ids"],
        optional_params=["resolution_strategy", "priority_rules"],
    ),
    DomainAction(
        action_id="start_wsi_interview",
        name="Iniciar Entrevista WSI",
        description="Inicia entrevista WSI completa e estruturada com candidato via chat (40-60 minutos) com perguntas baseadas em competências. Aciona quando chegou a hora da entrevista WSI no fluxo de triagem.",
        required_params=["candidate_id", "job_vacancy_id"],
        optional_params=["competencies", "interview_mode", "language"],
    ),
    DomainAction(
        action_id="send_question",
        name="Enviar Pergunta",
        description="Envia pergunta de entrevista WSI para candidato durante sessão ativa, com tipo e competência alvo. Aciona durante entrevista WSI em andamento para avançar para próxima pergunta.",
        required_params=["interview_id", "question_text"],
        optional_params=["question_type", "competency_target", "time_limit"],
    ),
    DomainAction(
        action_id="analyze_response",
        name="Analisar Resposta",
        description="Analisa resposta do candidato usando metodologia WSI com IA para extrair evidências de competências e calcular score parcial. Aciona após cada resposta do candidato durante entrevista estruturada.",
        required_params=["interview_id", "response_text"],
        optional_params=["question_context", "competency_target", "expected_level"],
    ),
    DomainAction(
        action_id="transcribe_audio",
        name="Transcrever Áudio",
        description="Transcreve áudio de entrevista por voz para texto para análise e registro. Aciona em entrevistas por voz ou quando recruiter envia gravação de entrevista presencial.",
        required_params=["audio_url"],
        optional_params=["language", "model", "interview_id"],
    ),
    DomainAction(
        action_id="analyze_voice",
        name="Analisar Voz",
        description="Analisa tom de voz, confiança e consistência emocional do candidato durante entrevista oral. Aciona em entrevistas por voz para adicionar dimensão não-verbal à avaliação.",
        required_params=["audio_url"],
        optional_params=["interview_id", "candidate_id", "analysis_type"],
    ),
    DomainAction(
        action_id="detect_evasive",
        name="Detectar Resposta Evasiva",
        description="Detecta padrões de respostas evasivas ou inconsistentes durante entrevista para alertar o recruiter. Aciona automaticamente durante análise de respostas ou quando recruiter suspeita de inconsistência.",
        required_params=["interview_id", "response_text"],
        optional_params=["question_context", "threshold"],
    ),
    DomainAction(
        action_id="generate_followup",
        name="Gerar Pergunta de Follow-up",
        description="Gera pergunta de follow-up contextualizada baseada na resposta anterior do candidato para aprofundar evidências. Aciona quando resposta foi superficial ou vaga e recruiter precisa de mais evidências.",
        required_params=["interview_id", "previous_response"],
        optional_params=["competency_target", "depth_level", "question_type"],
    ),
    DomainAction(
        action_id="complete_interview",
        name="Finalizar Entrevista",
        description="Finaliza entrevista WSI gerando resumo completo com scores por competência, análise e recomendação final. Aciona quando todas as perguntas foram feitas e recruiter encerra a sessão.",
        required_params=["interview_id"],
        optional_params=["final_notes", "recommendation", "generate_report"],
    ),
    DomainAction(
        action_id="interview_qa",
        name="Q&A sobre Entrevista",
        description="Responde dúvidas do recruiter sobre processo de entrevista, metodologia WSI ou candidato específico. Aciona quando recruiter tem perguntas contextuais durante ou após entrevista.",
        required_params=["question"],
        optional_params=["interview_id", "candidate_id", "context"],
    ),
    DomainAction(
        action_id="start_quick_screening",
        name="Iniciar Triagem Rápida",
        description="Inicia triagem rápida estruturada com candidato (10-15 minutos) para qualificação inicial antes de entrevista completa. Aciona como alternativa à entrevista WSI completa para pré-seleção eficiente.",
        required_params=["candidate_id"],
        optional_params=["job_vacancy_id", "screening_type", "questions"],
    ),
]
