# Database models
from lia_agents_core.working_memory import AgentWorkingMemory

from app.auth.models import User, UserRole
from app.models.ab_testing import (
    ABTestResult,
    PromptVariant,
)
from app.models.activity_feed import ActivityFeed
from app.models.admin_settings import (
    AVAILABLE_PERMISSIONS,
    DEFAULT_ROLES,
    NOTIFICATION_EVENT_TYPES,
    AdminAuditLog,
    AdminRole,
    AdminUserRole,
    NotificationPolicy,
    PermissionLevel,
    SecuritySetting,
)
from app.models.agent_checkpoint import AgentCheckpoint
from app.models.alert import Alert, AlertRule, AlertSeverity, AlertStatus, AlertType
from app.models.approval import ApprovalRequest, ApprovalStatus, ApprovalType
from app.models.archetype import SearchArchetype
from app.models.ats_integration import (
    ATSCandidate,
    ATSConnection,
    ATSJobMapping,
    ATSProvider,
    ATSSyncJob,
    ATSWebhookLog,
    SyncStatus,
)
from app.models.audit_log import AuditLog, DecisionType
from app.models.audit_logs import (
    DEFAULT_RETENTION_POLICIES,
    ActionCategory,
    AuditRetentionPolicy,
    AuditStatus,
    SOXAuditLog,
)
from app.models.automation import (
    DEFAULT_STAGE_AUTOMATION_RULES,
    AISuggestion,
    AutomationExecutionLog,
    CommunicationAutomation,
    StageAutomationRule,
    SuggestionStatus,
)
from app.models.automation import (
    ActionType as AutomationActionType,
)
from app.models.automation import (
    TriggerType as AutomationTriggerType,
)
from app.models.background_jobs import (
    ActionPriority,
    ActionStatus,
    ActionType,
    BackgroundJob,
    JobStatus,
    JobType,
    ProactiveAction,
)
from app.models.billing import (
    INVOICE_STATUS_OPTIONS,
    PAYMENT_METHOD_OPTIONS,
    SUBSCRIPTION_STATUS_OPTIONS,
    BillingProvider,
    Invoice,
    InvoiceStatus,
    PaymentMethod,
    PaymentMethodType,
    Subscription,
    SubscriptionStatus,
)
from app.models.calibration import (
    CalibrationEvent,
    CalibrationStatus,
    CalibrationSuggestion,
    CalibrationWeight,
    FeedbackType,
)
from app.models.candidate import Candidate, CandidateSearch, CreditsUsage, VacancyCandidate, ViewedCandidate
from app.models.candidate_attachment import AttachmentType, CandidateAttachment, UploadSource
from app.models.candidate_feedback import CandidateFeedback, FeedbackType
from app.models.candidate_list import CandidateList, CandidateListMember
from app.models.communication_history import (
    CommunicationChannel,
    CommunicationDirection,
    CommunicationHistory,
    CommunicationStatus,
    CommunicationType,
)
from app.models.communication_settings import (
    DEFAULT_COMMUNICATION_SETTINGS,
    CommunicationSettings,
    ConsentType,
    LGPDConsent,
)
from app.models.company import (
    Benefit,
    BigFiveQuestion,
    BigFiveRoleProfile,
    CompanyProfile,
    CultureValue,
    Department,
    IdealProfile,
    TechnicalQuestion,
    TechnicalTestTemplate,
)
from app.models.company_culture import CompanyCultureProfile, CultureAnalysisJob
from app.models.company_learning import (
    AgentFeedback,
    CompanyPattern,
    CompanyResponsibility,
    CompanySkill,
    LearningSource,
)
from app.models.compensation_policy import CompensationPolicy
from app.models.conversation import Conversation, ConversationSummary, Message
from app.models.data_request import (
    DEFAULT_DATA_FIELDS,
    DEFAULT_STAGE_FIELD_MAPPINGS,
    DataFieldType,
    DataRequest,
    DataRequestConfig,
    DataRequestField,
    DataRequestResponse,
    DataRequestStatus,
    DataRequestTemplate,
    VacancyDataRequestConfig,
)
from app.models.data_request import (
    TriggerType as DataRequestTriggerType,
)
from app.models.default_templates import (
    AVAILABLE_TEMPLATE_VARIABLES,
    DEFAULT_TEMPLATES_SEED,
    DefaultTemplate,
    TemplateCategory,
    TemplateStatus,
)
from app.models.email_template import EmailLog, EmailTemplate
from app.models.evaluation_criteria import (
    CriterionCategory,
    EvaluationCriteria,
)
from app.models.feedback import (
    InteractionFeedback,
    LearningPattern,
)
from app.models.feedback_learning import JobOutcome, JobOutcomeType, SuggestionFeedback, WizardFeedback
from app.models.graph_session import GraphSession
from app.models.guardrail import Guardrail
from app.models.imported_job_description import (
    ClientSkillCatalog,
    ImportBatch,
    ImportedJobDescription,
    ImportSource,
    ImportStatus,
    ProcessingStatus,
)
from app.models.integration_hub import (
    DEFAULT_INTEGRATION_PROVIDERS,
    IntegrationCategory,
    IntegrationConnection,
    IntegrationProvider,
    IntegrationStatus,
    IntegrationSyncLog,
    IntegrationWebhook,
)
from app.models.intelligence_layer import (
    CorrectionPattern,
    InsightType,
    IntelligenceInsight,
    OutcomeCorrelation,
    PatternCache,
    PatternType,
    SuccessProfile,
)
from app.models.interview import CalendarAvailability, Interview, InterviewFeedback, InterviewNote
from app.models.job_draft import (
    ChangeType,
    DraftFieldHistory,
    JobDraft,
    JobDraftStatus,
)
from app.models.job_pattern import (
    EMBEDDING_DIMENSION,
    JobEmbedding,
    JobPattern,
    SalaryBenchmark,
    SkillCluster,
)
from app.models.job_vacancy import JobVacancy, JobVacancyInterviewStage, JobVacancyTemplate
from app.models.job_vacancy_audit import (
    AuditAction,
    JobVacancyAuditLog,
)
from app.models.journey_mapping import IntegrationType, JourneyBlueprint, JourneyIntegration, JourneyStatus, JourneyStep
from app.models.lia_field_toggles import (
    DEFAULT_FIELD_TOGGLES,
    LiaFieldToggle,
)
from app.models.lia_opinion import LiaOpinion, OpinionSource, OpinionType, RecommendationType
from app.models.memory import (
    DOCUMENT_TYPES,
    ConversationMemory,
    KnowledgeBase,
)
from app.models.message_queue import (
    MessageChannel,
    MessagePriority,
    MessageQueue,
    MessageStatus,
)
from app.models.observability import (
    AgentType,
    AIInferenceLog,
    BusinessProcess,
    ComplianceControl,
    ComplianceFramework,
    ConsentEvent,
    ConsentEventTypeEnum,
    ConsentRecord,
    ConsentVersion,
    ContinuityTest,
    ContinuityTestStatus,
    ContinuityTestType,
    ControlStatus,
    CriticalityLevel,
    DataAccessLog,
    DataOperationType,
    DataSubjectRequest,
    DataSubjectRequestStatusEnum,
    DataSubjectRequestTypeEnum,
    DataType,
    DisasterRecoveryPlan,
    DRPlanStatus,
    EvaluationDimension,
    EvaluationType,
    IncidentReport,
    IncidentSeverity,
    IncidentType,
    InsuranceClaim,
    InsuranceClaimStatusEnum,
    InsuranceCoverage,
    InsuranceCoverageTypeEnum,
    InsuranceDocument,
    InsuranceDocumentTypeEnum,
    InsurancePolicy,
    InsurancePolicyStatusEnum,
    LegalBasis,
    ModelEvaluation,
    RiskCategory,
    RiskEntry,
    RiskImpact,
    RiskLikelihood,
    RiskStatus,
    RiskTreatment,
    RiskTreatmentType,
    SoDConflict,
    SoDConflictType,
    SoDRole,
    SoDViolation,
)
from app.models.observability import (
    ConsentType as ObservabilityConsentType,
)
from app.models.pipeline_template import DEFAULT_PIPELINE_TEMPLATES, PipelineTemplate
from app.models.planned_task import ExecutionPlan, PlannedTask, PlannedTaskPriority, PlannedTaskStatus
from app.models.policy import (
    DEFAULT_BUSINESS_RULES,
    DEFAULT_ESCALATION_RULES,
    DEFAULT_RATE_LIMIT_RULES,
    BusinessRule,
    EscalationAction,
    EscalationLog,
    EscalationRule,
    PolicyEvaluationLog,
    PolicyEvaluationResult,
    RateLimitCounter,
    RateLimitRule,
    RuleType,
    TargetType,
    TriggerType,
)
from app.models.recruiter_profile import (
    DEFAULT_IMPACT_DESCRIPTION,
    FIELD_IMPACT_DESCRIPTIONS,
    REMINDER_ACTIONS,
    PersonalizationSettings,
    ProfileCalculationLog,
    RecruiterFieldPreference,
    RecruiterProfile,
)
from app.models.recruitment_journey import (
    DEFAULT_AUTOMATIONS,
    DEFAULT_SLAS,
    DEFAULT_TEMPLATES,
    AutomationType,
    RecruitmentAutomation,
    RecruitmentSLA,
    RecruitmentTemplate,
    SLAViolation,
    TemplateType,
)
from app.models.recruitment_stages import (
    DEFAULT_RECRUITMENT_STAGES,
    DEFAULT_SUB_STATUSES,
    GUPY_STAGE_MAPPINGS,
    PANDAPE_STAGE_MAPPINGS,
    ATSStageMapping,
    CandidateStageHistory,
    RecruitmentStage,
    RecruitmentSubStatus,
    ScreeningQuestion,
)
from app.models.screening import ScreeningTask
from app.models.screening_question import (
    DEFAULT_SCREENING_QUESTIONS,
    QUESTION_CATEGORIES,
    QUESTION_TYPES,
    CompanyScreeningQuestion,
)
from app.models.search_feedback import SearchFeedback
from app.models.self_scheduling import InterviewReminder, RescheduleHistory, SelfSchedulingLink
from app.models.shared_search import (
    FeedbackDecision,
    SharedSearch,
    SharedSearchAccess,
    SharedSearchFeedback,
    SharedSearchStatus,
    ShareType,
)
from app.models.structured_responses import (
    CandidateEvaluation,
    ConversationAnalysis,
    IntentClassification,
    JobDescriptionExtraction,
    JobFieldUpdate,
    OrchestrationDecision,
    SalaryAnalysis,
    SkillExtraction,
    TextGeneration,
    ValidationResult,
)
from app.models.task import Task, TaskPriority, TaskStatus, TaskTemplate, TaskType
from app.models.teams import TeamsConversation, TeamsMessage, TeamsNotification
from app.models.triagem import TriagemMessage, TriagemSession
from app.models.voice_screening import VoiceScreeningAnalysis, VoiceScreeningCall
from app.models.webhook import WEBHOOK_EVENTS, Webhook, WebhookEvent, WebhookLog, WebhookStatus
from app.models.webhook_registration import JOB_STATUS_WEBHOOK_EVENTS, WebhookDeliveryLog, WebhookRegistration
from app.models.workforce import HiringPlan, ImportJob, PlannedHeadcount

__all__ = [
    "Conversation",
    "Message",
    "ConversationSummary",
    "TeamsConversation",
    "TeamsMessage",
    "TeamsNotification",
    "VoiceScreeningCall",
    "VoiceScreeningAnalysis",
    "ActivityFeed",
    "Candidate",
    "CandidateSearch",
    "CreditsUsage",
    "ViewedCandidate",
    "VacancyCandidate",
    "JobVacancy",
    "JobVacancyInterviewStage",
    "JobVacancyTemplate",
    "Interview",
    "InterviewFeedback",
    "CalendarAvailability",
    "InterviewNote",
    "AgentCheckpoint",
    "SelfSchedulingLink",
    "RescheduleHistory",
    "InterviewReminder",
    "ATSConnection",
    "ATSSyncJob",
    "ATSCandidate",
    "ATSWebhookLog",
    "ATSJobMapping",
    "ATSProvider",
    "SyncStatus",
    "EmailTemplate",
    "EmailLog",
    "Task",
    "TaskTemplate",
    "TaskPriority",
    "TaskStatus",
    "TaskType",
    "PlannedTask",
    "PlannedTaskPriority",
    "PlannedTaskStatus",
    "ExecutionPlan",
    "Alert",
    "AlertRule",
    "AlertType",
    "AlertSeverity",
    "AlertStatus",
    "CalibrationEvent",
    "CalibrationWeight",
    "CalibrationSuggestion",
    "FeedbackType",
    "CalibrationStatus",
    "CompanyProfile",
    "Department",
    "Benefit",
    "CultureValue",
    "IdealProfile",
    "BigFiveQuestion",
    "BigFiveRoleProfile",
    "TechnicalQuestion",
    "TechnicalTestTemplate",
    "CompensationPolicy",
    "CompanyCultureProfile",
    "CultureAnalysisJob",
    "HiringPlan",
    "PlannedHeadcount",
    "ImportJob",
    "SearchArchetype",
    "CandidateFeedback",
    "FeedbackType",
    "RecruitmentStage",
    "RecruitmentSubStatus",
    "ATSStageMapping",
    "CandidateStageHistory",
    "ScreeningQuestion",
    "DEFAULT_RECRUITMENT_STAGES",
    "DEFAULT_SUB_STATUSES",
    "GUPY_STAGE_MAPPINGS",
    "PANDAPE_STAGE_MAPPINGS",
    "User",
    "UserRole",
    "AuditLog",
    "DecisionType",
    "CandidateList",
    "CandidateListMember",
    "CommunicationHistory",
    "CommunicationType",
    "CommunicationChannel",
    "CommunicationDirection",
    "CommunicationStatus",
    "CandidateAttachment",
    "AttachmentType",
    "UploadSource",
    "ApprovalRequest",
    "ApprovalStatus",
    "ApprovalType",
    "JourneyBlueprint",
    "JourneyStep",
    "JourneyIntegration",
    "JourneyStatus",
    "IntegrationType",
    "IntegrationProvider",
    "IntegrationConnection",
    "IntegrationSyncLog",
    "IntegrationWebhook",
    "IntegrationCategory",
    "IntegrationStatus",
    "DEFAULT_INTEGRATION_PROVIDERS",
    "RecruitmentTemplate",
    "RecruitmentSLA",
    "RecruitmentAutomation",
    "SLAViolation",
    "TemplateType",
    "AutomationType",
    "DEFAULT_TEMPLATES",
    "DEFAULT_SLAS",
    "DEFAULT_AUTOMATIONS",
    "AdminRole",
    "AdminUserRole",
    "NotificationPolicy",
    "SecuritySetting",
    "AdminAuditLog",
    "PermissionLevel",
    "DEFAULT_ROLES",
    "AVAILABLE_PERMISSIONS",
    "NOTIFICATION_EVENT_TYPES",
    "Webhook",
    "WebhookLog",
    "WebhookEvent",
    "WebhookStatus",
    "WEBHOOK_EVENTS",
    "CommunicationSettings",
    "LGPDConsent",
    "ConsentType",
    "DEFAULT_COMMUNICATION_SETTINGS",
    "Subscription",
    "Invoice",
    "PaymentMethod",
    "SubscriptionStatus",
    "InvoiceStatus",
    "PaymentMethodType",
    "BillingProvider",
    "SUBSCRIPTION_STATUS_OPTIONS",
    "INVOICE_STATUS_OPTIONS",
    "PAYMENT_METHOD_OPTIONS",
    "AIInferenceLog",
    "DataAccessLog",
    "ConsentRecord",
    "IncidentReport",
    "ModelEvaluation",
    "ComplianceControl",
    "AgentType",
    "DataOperationType",
    "DataType",
    "ObservabilityConsentType",
    "LegalBasis",
    "IncidentType",
    "IncidentSeverity",
    "EvaluationType",
    "EvaluationDimension",
    "ComplianceFramework",
    "ControlStatus",
    "DataSubjectRequest",
    "DataSubjectRequestTypeEnum",
    "DataSubjectRequestStatusEnum",
    "ConsentVersion",
    "ConsentEvent",
    "ConsentEventTypeEnum",
    "InsurancePolicy",
    "InsuranceCoverage",
    "InsuranceDocument",
    "InsuranceClaim",
    "InsurancePolicyStatusEnum",
    "InsuranceCoverageTypeEnum",
    "InsuranceDocumentTypeEnum",
    "InsuranceClaimStatusEnum",
    "RiskCategory",
    "RiskLikelihood",
    "RiskImpact",
    "RiskStatus",
    "RiskTreatmentType",
    "RiskEntry",
    "RiskTreatment",
    "SoDConflictType",
    "SoDRole",
    "SoDConflict",
    "SoDViolation",
    "CriticalityLevel",
    "DRPlanStatus",
    "ContinuityTestType",
    "ContinuityTestStatus",
    "BusinessProcess",
    "DisasterRecoveryPlan",
    "ContinuityTest",
    "SOXAuditLog",
    "AuditRetentionPolicy",
    "ActionCategory",
    "AuditStatus",
    "DEFAULT_RETENTION_POLICIES",
    "DefaultTemplate",
    "TemplateCategory",
    "TemplateStatus",
    "AVAILABLE_TEMPLATE_VARIABLES",
    "DEFAULT_TEMPLATES_SEED",
    "MessageQueue",
    "MessagePriority",
    "MessageStatus",
    "MessageChannel",
    "BusinessRule",
    "RateLimitRule",
    "RateLimitCounter",
    "EscalationRule",
    "PolicyEvaluationLog",
    "EscalationLog",
    "RuleType",
    "TargetType",
    "TriggerType",
    "EscalationAction",
    "PolicyEvaluationResult",
    "DEFAULT_BUSINESS_RULES",
    "DEFAULT_RATE_LIMIT_RULES",
    "DEFAULT_ESCALATION_RULES",
    "CommunicationAutomation",
    "AutomationExecutionLog",
    "AISuggestion",
    "StageAutomationRule",
    "AutomationTriggerType",
    "AutomationActionType",
    "SuggestionStatus",
    "DEFAULT_STAGE_AUTOMATION_RULES",
    "ScreeningTask",
    "CompanyScreeningQuestion",
    "DEFAULT_SCREENING_QUESTIONS",
    "QUESTION_CATEGORIES",
    "QUESTION_TYPES",
    "PipelineTemplate",
    "DEFAULT_PIPELINE_TEMPLATES",
    "WebhookRegistration",
    "WebhookDeliveryLog",
    "JOB_STATUS_WEBHOOK_EVENTS",
    "JobVacancyAuditLog",
    "AuditAction",
    "DataRequest",
    "DataRequestTemplate",
    "DataRequestField",
    "DataRequestResponse",
    "DataRequestConfig",
    "VacancyDataRequestConfig",
    "DataRequestStatus",
    "DataFieldType",
    "DataRequestTriggerType",
    "DEFAULT_DATA_FIELDS",
    "DEFAULT_STAGE_FIELD_MAPPINGS",
    "WizardFeedback",
    "JobOutcome",
    "JobOutcomeType",
    "SharedSearch",
    "SharedSearchAccess",
    "SharedSearchFeedback",
    "ShareType",
    "SharedSearchStatus",
    "FeedbackDecision",
    "JobDraft",
    "JobDraftStatus",
    "DraftFieldHistory",
    "ChangeType",
    "LiaFieldToggle",
    "DEFAULT_FIELD_TOGGLES",
    # Intelligence Layer
    "IntelligenceInsight",
    "PatternCache",
    "CorrectionPattern",
    "SuccessProfile",
    "OutcomeCorrelation",
    "InsightType",
    "PatternType",
    # Recruiter Personalization
    "RecruiterProfile",
    "RecruiterFieldPreference",
    "ProfileCalculationLog",
    "PersonalizationSettings",
    # Structured Responses for LLM outputs
    "JobFieldUpdate",
    "OrchestrationDecision",
    "IntentClassification",
    "SalaryAnalysis",
    "SkillExtraction",
    "JobDescriptionExtraction",
    "CandidateEvaluation",
    "ConversationAnalysis",
    "ValidationResult",
    "TextGeneration",
    "ConversationMemory",
    "KnowledgeBase",
    "DOCUMENT_TYPES",
    "GraphSession",
    "InteractionFeedback",
    "LearningPattern",
    # Autonomous Agent System
    "BackgroundJob",
    "ProactiveAction",
    "JobStatus",
    "JobType",
    "ActionType",
    "ActionPriority",
    "ActionStatus",
    "EvaluationCriteria",
    "CriterionCategory",
    "PromptVariant",
    "ABTestResult",
    # ReAct Agent Working Memory
    "AgentWorkingMemory",
    # Triagem WSI
    "TriagemSession",
    "TriagemMessage",
]
