export {
  ExpandedChatProvider,
  ExpandedChatContext,
  useExpandedChatContext,
  INITIAL_DETECTED_CRITERIA,
  INITIAL_BASIC_INFO_FIELDS,
  INITIAL_SALARY_INFO,
  DEFAULT_BEHAVIORAL_COMPETENCIES,
  type ExpandedChatContextValue,
  type ExpandedChatProviderProps,
  type WizardContextState,
  type WizardContextActions,
  type TechnicalSkill,
  type BehavioralCompetency,
  type Benefit,
  type SalaryInfo,
  type WSIQuestion,
  type DetectedCriteria,
  type BasicInfoFields,
  type CatalogMaturity,
  type OrchestratorFieldUpdates,
} from './ExpandedChatContext'

export {
  type WizardStage,
  type WizardPhase,
  type WizardPhaseConfig,
  type WizardStageConfig,
  type StageTransitionConfig,
  type StageCriticalFields,
  type ExtendedWizardStageConfig,
  WIZARD_PHASES,
  WIZARD_STAGES,
  FRONTEND_TO_BACKEND_STAGE,
  BACKEND_TO_FRONTEND_STAGE,
  getBackendStageNumber,
  getFrontendStageFromBackend,
  getStageTransitionMessage,
  getMissingCriticalFields,
  generateMissingFieldsMessage,
  PRE_WIZARD_MESSAGE,
  DRAFT_DETECTED_MESSAGE,
  INITIAL_JOB_CREATION_MESSAGE,
  FROM_SCRATCH_ORIENTATION_MESSAGE,
  INITIAL_GENERAL_MESSAGE,
} from './config'

export { WizardHeader, WizardSidebar, WSIQualityBar, type WizardHeaderProps, type WizardSidebarProps, type CatalogStatus, type WSIQualityBarProps } from './components'

export {
  useWizardState,
  useWizardNavigation,
  useWSIQualityGates,
  useWizardOrchestrator,
  type UseWizardStateOptions,
  type UseWizardStateReturn,
  type UseWizardNavigationOptions,
  type UseWizardNavigationReturn,
  type StageValidationResult,
  type ChatNavigationResult,
  type UseWSIQualityGatesOptions,
  type WSIQualityGatesResult,
  type WSIQualityField,
  type UseWizardOrchestratorOptions,
  type UseWizardOrchestratorReturn,
  type OrchestratorResult,
} from './hooks'

export {
  parseCommand,
  isNavigationCommand,
  isEditCommand,
  isLocalCommand,
  getStageLabel,
  getStageAliases,
  parseSalaryValue,
  applySalaryUpdate,
  findSkillByName,
  findCompetencyByName,
  createTechnicalSkill,
  addSkillIfNotExists,
  removeSkillByName,
  generateUpdateConfirmation,
  containsSkillKeywords,
  extractPotentialSkills,
  type CommandType,
  type EditAction,
  type ParsedNavigationCommand,
  type ParsedEditCommand,
  type NoCommand,
  type ParsedCommand,
  type SalaryParseResult,
  type FieldUpdateResult,
} from './utils'
