"""
Alert Model - Database model for job alerts and notifications.

Alerts are generated by the system when jobs reach critical states
or when candidate actions are needed.
"""
from sqlalchemy import Column, String, Text, DateTime, Enum as SQLEnum, JSON, Boolean, Integer
from datetime import datetime
import enum
import uuid

from lia_config.database import Base


class AlertType(str, enum.Enum):
    """Types of alerts."""
    JOB_CRITICAL = "job_critical"
    JOB_STALE = "job_stale"
    JOB_LOW_VOLUME = "job_low_volume"
    CANDIDATE_WAITING = "candidate_waiting"
    FEEDBACK_PENDING = "feedback_pending"
    INTERVIEW_REMINDER = "interview_reminder"
    PROPOSAL_EXPIRING = "proposal_expiring"
    DEADLINE_APPROACHING = "deadline_approaching"
    ANOMALY_DETECTED = "anomaly_detected"
    SYSTEM = "system"


class AlertSeverity(str, enum.Enum):
    """Alert severity levels."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class AlertStatus(str, enum.Enum):
    """Alert status."""
    ACTIVE = "active"
    ACKNOWLEDGED = "acknowledged"
    RESOLVED = "resolved"
    DISMISSED = "dismissed"
    EXPIRED = "expired"


class Alert(Base):
    """
    Alert model for tracking system and job alerts.
    """
    __tablename__ = "alerts"
    __table_args__ = {"extend_existing": True}  # canonical 2026-05-24 — defense-in-depth contra hot-reload re-import
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    
    alert_type = Column(SQLEnum(AlertType), nullable=False)
    severity = Column(SQLEnum(AlertSeverity), default=AlertSeverity.MEDIUM)
    status = Column(SQLEnum(AlertStatus), default=AlertStatus.ACTIVE)
    
    title = Column(String(255), nullable=False)
    message = Column(Text, nullable=False)
    
    user_id = Column(String, nullable=True)
    
    job_id = Column(String, nullable=True)
    candidate_id = Column(String, nullable=True)
    
    context = Column(JSON, default=dict)
    
    suggested_actions = Column(JSON, default=list)
    
    acknowledged_at = Column(DateTime, nullable=True)
    acknowledged_by = Column(String, nullable=True)
    resolved_at = Column(DateTime, nullable=True)
    resolved_by = Column(String, nullable=True)
    
    expires_at = Column(DateTime, nullable=True)
    
    notification_sent = Column(Boolean, default=False)
    notification_channels = Column(JSON, default=list)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def to_dict(self):
        """Convert alert to dictionary."""
        return {
            "id": self.id,
            "alert_type": self.alert_type.value if self.alert_type else None,
            "severity": self.severity.value if self.severity else None,
            "status": self.status.value if self.status else None,
            "title": self.title,
            "message": self.message,
            "user_id": self.user_id,
            "job_id": self.job_id,
            "candidate_id": self.candidate_id,
            "context": self.context,
            "suggested_actions": self.suggested_actions,
            "acknowledged_at": self.acknowledged_at.isoformat() if self.acknowledged_at else None,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
            "expires_at": self.expires_at.isoformat() if self.expires_at else None,
            "notification_sent": self.notification_sent,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
    
    def __repr__(self):
        return f"<Alert {self.id}: {self.title} ({self.severity.value})>"


class AlertRule(Base):
    """
    Alert rule model for configuring automatic alerts.
    """
    __tablename__ = "alert_rules"
    __table_args__ = {"extend_existing": True}  # canonical 2026-05-24 — defense-in-depth contra hot-reload re-import
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    
    alert_type = Column(SQLEnum(AlertType), nullable=False)
    severity = Column(SQLEnum(AlertSeverity), default=AlertSeverity.MEDIUM)
    
    condition = Column(JSON, nullable=False)
    
    is_active = Column(Boolean, default=True)
    
    check_interval_hours = Column(Integer, default=4)
    last_checked_at = Column(DateTime, nullable=True)
    
    notification_channels = Column(JSON, default=list)
    
    title_template = Column(String(255), nullable=False)
    message_template = Column(Text, nullable=False)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def to_dict(self):
        """Convert rule to dictionary."""
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "alert_type": self.alert_type.value if self.alert_type else None,
            "severity": self.severity.value if self.severity else None,
            "condition": self.condition,
            "is_active": self.is_active,
            "check_interval_hours": self.check_interval_hours,
            "title_template": self.title_template,
            "message_template": self.message_template,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }


class AlertConfig(Base):
    """
    Alert configuration for admin settings.
    Stores the user's alert preferences and briefing settings.
    """
    __tablename__ = "alert_configs"
    __table_args__ = {"extend_existing": True}  # canonical 2026-05-24 — defense-in-depth contra hot-reload re-import
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    
    # TENANT-EXEMPT: AlertConfig com company_id NULL = config global padrao do sistema
    company_id = Column(String, nullable=True)
    user_id = Column(String, nullable=True)
    
    alerts = Column(JSON, default=list)
    
    briefing_frequency = Column(String(20), default="daily")
    
    is_active = Column(Boolean, default=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def to_dict(self):
        """Convert config to dictionary."""
        return {
            "id": self.id,
            "company_id": self.company_id,
            "user_id": self.user_id,
            "alerts": self.alerts,
            "briefing_frequency": self.briefing_frequency,
            "is_active": self.is_active,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }


class AlertPreferenceType(str, enum.Enum):
    """Types of alert preferences."""
    TIME_TO_HIRE_CRITICAL = "time_to_hire_critical"
    CONVERSION_RATE_LOW = "conversion_rate_low"
    NPS_DECLINING = "nps_declining"
    NO_HIRES = "no_hires"
    QUALITY_SCORE_LOW = "quality_score_low"
    SLA_NEAR_EXPIRATION = "sla_near_expiration"
    MONTHLY_GOAL_AT_RISK = "monthly_goal_at_risk"
    CANDIDATE_NO_INTERACTION = "candidate_no_interaction"
    INTERVIEW_NOT_CONFIRMED = "interview_not_confirmed"
    FEEDBACK_PENDING = "feedback_pending"
    CANDIDATES_STAGNANT = "candidates_stagnant"
    OFFERS_PENDING_LONG = "offers_pending_long"
    PIPELINE_EMPTY = "pipeline_empty"
    TASKS_OVERDUE = "tasks_overdue"
    EMAIL_DELIVERY_LOW = "email_delivery_low"
    DROPOUT_RISK_HIGH = "dropout_risk_high"
    IDEAL_CANDIDATE_FOUND = "ideal_candidate_found"
    ATS_SYNC_FAILED = "ats_sync_failed"


class AlertPreference(Base):
    """
    User-specific alert preference settings.
    Controls which alerts are enabled, thresholds, and notification channels.
    """
    __tablename__ = "alert_preferences"
    __table_args__ = {"extend_existing": True}  # canonical 2026-05-24 — defense-in-depth contra hot-reload re-import
    
    id = Column(String, primary_key=True, default=lambda: str(uuid.uuid4()))
    
    company_id = Column(String, nullable=False, index=True)
    user_id = Column(String, nullable=False, index=True)
    alert_type = Column(String(100), nullable=False)
    
    is_enabled = Column(Boolean, default=True)
    threshold = Column(Integer, nullable=True)
    
    channel_email = Column(Boolean, default=True)
    channel_bell = Column(Boolean, default=True)
    channel_teams = Column(Boolean, default=False)
    channel_whatsapp = Column(Boolean, default=False)
    
    cooldown_hours = Column(Integer, default=24)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    def to_dict(self):
        """Convert preference to dictionary."""
        return {
            "id": self.id,
            "company_id": self.company_id,
            "user_id": self.user_id,
            "alert_type": self.alert_type,
            "is_enabled": self.is_enabled,
            "threshold": self.threshold,
            "channels": {
                "email": self.channel_email,
                "bell": self.channel_bell,
                "teams": self.channel_teams,
                "whatsapp": self.channel_whatsapp,
            },
            "cooldown_hours": self.cooldown_hours,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }
