"""
Intelligence Layer models for centralized knowledge and decision-making.

These models store:
- Detected patterns from corrections and outcomes
- Correlation insights between job characteristics and success
- Cached patterns for efficient retrieval
- Decision logs for transparency
"""
from datetime import datetime
from typing import Optional, List
from sqlalchemy import Column, String, Integer, DateTime, Text, JSON, Float, Boolean, Index
from sqlalchemy.dialects.postgresql import UUID
import uuid
import enum

from lia_config.database import Base


class InsightType(str, enum.Enum):
    """Types of insights generated by the Intelligence Layer."""
    PATTERN = "pattern"
    PREDICTION = "prediction"
    CORRELATION = "correlation"
    ADJUSTMENT = "adjustment"
    RECOMMENDATION = "recommendation"


class PatternType(str, enum.Enum):
    """Types of patterns detected."""
    SALARY_CORRECTION = "salary_correction"
    SENIORITY_CORRECTION = "seniority_correction"
    SKILL_CORRECTION = "skill_correction"
    SUCCESS_PROFILE = "success_profile"
    TIME_TO_FILL = "time_to_fill"
    ACCEPTANCE_RATE = "acceptance_rate"


class IntelligenceInsight(Base):
    """
    Log of insights generated by the Intelligence Layer.
    
    Tracks every insight (pattern, prediction, correlation, adjustment)
    generated during job creation, along with whether it was applied
    and accepted by the recruiter.
    
    This enables:
    - Transparency in AI decisions
    - Measuring insight accuracy
    - Improving future suggestions
    """
    __tablename__ = "intelligence_insights"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    
    company_id = Column(String(255), nullable=False, index=True)
    job_id = Column(UUID(as_uuid=True), nullable=True, index=True)
    recruiter_id = Column(String(255), nullable=True, index=True)
    
    insight_type = Column(String(50), nullable=False, index=True)
    field = Column(String(100), nullable=True, index=True)
    
    original_value = Column(JSON, nullable=True)
    suggested_value = Column(JSON, nullable=True)
    
    confidence = Column(Float, nullable=False, default=0.0)
    source = Column(String(50), nullable=True)
    reasoning = Column(Text, nullable=True)
    
    was_applied = Column(Boolean, nullable=True)
    was_accepted = Column(Boolean, nullable=True)
    final_value = Column(JSON, nullable=True)
    
    insight_metadata = Column(JSON, default=dict)
    
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    
    __table_args__ = (
        Index('ix_insights_company_type', 'company_id', 'insight_type'),
        Index('ix_insights_company_field', 'company_id', 'field'),
    {"extend_existing": True}, )


class PatternCache(Base):
    """
    Cache of calculated patterns for efficient retrieval.
    
    Patterns are expensive to calculate (require analyzing many records).
    This cache stores pre-calculated patterns with expiration.
    
    Pattern types:
    - salary_correction: Average salary adjustment percentage
    - seniority_correction: Common seniority corrections
    - success_profile: Characteristics of successful hires
    - time_to_fill: Average time to fill by role/seniority
    - acceptance_rate: Suggestion acceptance rate by field
    """
    __tablename__ = "pattern_cache"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    
    company_id = Column(String(255), nullable=False, index=True)
    
    pattern_type = Column(String(50), nullable=False, index=True)
    pattern_key = Column(String(200), nullable=False, index=True)
    
    pattern_data = Column(JSON, nullable=False, default=dict)
    
    sample_size = Column(Integer, nullable=False, default=0)
    confidence = Column(Float, nullable=False, default=0.0)
    
    calculated_at = Column(DateTime, nullable=False, default=datetime.utcnow)
    expires_at = Column(DateTime, nullable=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    __table_args__ = (
        Index('ix_pattern_cache_lookup', 'company_id', 'pattern_type', 'pattern_key'),
        Index('ix_pattern_cache_expiry', 'expires_at'),
    {"extend_existing": True}, )


class CorrectionPattern(Base):
    """
    Detected patterns in recruiter corrections.
    
    When recruiters consistently correct a field in the same direction
    (e.g., always increasing salary by 15-20%), this pattern is stored
    for future automatic adjustments.
    """
    __tablename__ = "correction_patterns"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    
    company_id = Column(String(255), nullable=False, index=True)
    
    field = Column(String(100), nullable=False, index=True)
    
    pattern_type = Column(String(100), nullable=True, index=True)
    seniority = Column(String(50), nullable=True, index=True)
    department = Column(String(100), nullable=True)
    
    original_value_pattern = Column(String(255), nullable=True)
    corrected_value_pattern = Column(String(255), nullable=True)
    
    adjustment_direction = Column(String(20), nullable=True)
    adjustment_magnitude = Column(Float, nullable=True)
    
    occurrence_count = Column(Integer, nullable=True)
    
    sample_size = Column(Integer, nullable=True, default=0)
    confidence = Column(Float, nullable=True, default=0.0)
    
    is_active = Column(Boolean, default=True)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    __table_args__ = (
        Index('ix_correction_pattern_lookup', 'company_id', 'field', 'seniority'),
    {"extend_existing": True}, )


class SuccessProfile(Base):
    """
    Profile of characteristics from successful hires.
    
    Aggregates data from filled positions to identify
    what characteristics correlate with success.
    """
    __tablename__ = "success_profiles"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    
    company_id = Column(String(255), nullable=False, index=True)
    
    seniority = Column(String(50), nullable=True, index=True)
    department = Column(String(100), nullable=True)
    role_family = Column(String(200), nullable=True, index=True)
    
    avg_time_to_fill_days = Column(Integer, nullable=True)
    avg_salary = Column(Float, nullable=True)
    salary_range_min = Column(Float, nullable=True)
    salary_range_max = Column(Float, nullable=True)
    
    common_skills = Column(JSON, default=list)
    common_requirements = Column(JSON, default=list)
    preferred_work_model = Column(String(100), nullable=True)
    
    avg_satisfaction_score = Column(Float, nullable=True)
    
    sample_size = Column(Integer, nullable=True, default=0)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    __table_args__ = (
        Index('ix_success_profile_lookup', 'company_id', 'role_family', 'seniority'),
    {"extend_existing": True}, )


class OutcomeCorrelation(Base):
    """
    Correlations between job characteristics and outcomes.
    
    Stores statistical correlations discovered between
    input characteristics (salary, skills, etc.) and
    outcomes (time to fill, satisfaction, success rate).
    
    Example:
        factor: "salary_percentile"
        outcome_metric: "time_to_fill"
        correlation: 0.72 (positive)
        significance: 0.95
        recommendation: "Higher salary correlates with faster filling"
    """
    __tablename__ = "outcome_correlations"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    
    company_id = Column(String(255), nullable=False, index=True)
    
    factor = Column(String(100), nullable=False, index=True)
    outcome_metric = Column(String(100), nullable=False, index=True)
    
    role_pattern = Column(String(200), nullable=True)
    seniority = Column(String(50), nullable=True)
    
    correlation = Column(Float, nullable=False)
    significance = Column(Float, nullable=True)
    
    direction = Column(String(20), nullable=True)
    recommendation = Column(Text, nullable=True)
    
    sample_size = Column(Integer, nullable=False, default=0)
    
    factor_values = Column(JSON, default=dict)
    outcome_values = Column(JSON, default=dict)
    
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    __table_args__ = (
        Index('ix_correlation_lookup', 'company_id', 'factor', 'outcome_metric'),
    {"extend_existing": True}, )
