"""
Few-shot examples for LIA agents.

Este módulo contém exemplos de interações para treinamento e 
consistência de respostas dos agentes especializados.
"""

from .job_planner_examples import (
    CREATE_DEVELOPER_JOB,
    DEFINE_COMPETENCY_MATRIX,
    EXTRACT_JD_REQUIREMENTS,
    GENERATE_WSI_QUESTIONS,
    JOB_PLANNER_EXAMPLES,
    UPDATE_EXISTING_JOB,
)
from .orchestrator_examples import (
    DELEGATION_CV_SCREENING,
    DELEGATION_JOB_PLANNER,
    DELEGATION_SOURCING,
    ORCHESTRATOR_EXAMPLES,
    PROACTIVE_RESPONSE,
    STATUS_INQUIRY,
)
from .pipeline_examples import (
    CONVERSION_ANALYSIS,
    FUNNEL_STATUS,
    JOB_COMPARISON,
    PERFORMANCE_METRICS,
    PIPELINE_EXAMPLES,
    STALLED_CANDIDATES,
)
from .sourcing_examples import (
    EMPTY_SEARCH_RESPONSE,
    GENERATE_BOOLEAN_STRING,
    PERSONALIZED_OUTREACH,
    SEARCH_PYTHON_CANDIDATES,
    SOURCING_EXAMPLES,
    SUGGEST_CANDIDATES_FOR_JOB,
)

__all__ = [
    "ORCHESTRATOR_EXAMPLES",
    "DELEGATION_JOB_PLANNER",
    "DELEGATION_SOURCING",
    "DELEGATION_CV_SCREENING",
    "STATUS_INQUIRY",
    "PROACTIVE_RESPONSE",
    "JOB_PLANNER_EXAMPLES",
    "CREATE_DEVELOPER_JOB",
    "EXTRACT_JD_REQUIREMENTS",
    "GENERATE_WSI_QUESTIONS",
    "UPDATE_EXISTING_JOB",
    "DEFINE_COMPETENCY_MATRIX",
    "SOURCING_EXAMPLES",
    "SEARCH_PYTHON_CANDIDATES",
    "GENERATE_BOOLEAN_STRING",
    "SUGGEST_CANDIDATES_FOR_JOB",
    "PERSONALIZED_OUTREACH",
    "EMPTY_SEARCH_RESPONSE",
    "PIPELINE_EXAMPLES",
    "FUNNEL_STATUS",
    "CONVERSION_ANALYSIS",
    "PERFORMANCE_METRICS",
    "STALLED_CANDIDATES",
    "JOB_COMPARISON",
]
