// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/arch-compare/EstadoAtual.tsx": () => import("../components/mockups/arch-compare/EstadoAtual.tsx"),
  "./components/mockups/arch-compare/EstadoDesejado.tsx": () => import("../components/mockups/arch-compare/EstadoDesejado.tsx"),
  "./components/mockups/wsi-report/Tab1Respostas.tsx": () => import("../components/mockups/wsi-report/Tab1Respostas.tsx"),
  "./components/mockups/wsi-report/Tab2Aprovado.tsx": () => import("../components/mockups/wsi-report/Tab2Aprovado.tsx"),
  "./components/mockups/wsi-report/Tab2Pendente.tsx": () => import("../components/mockups/wsi-report/Tab2Pendente.tsx")
};
