// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/chat-usability/AccessibleReadable.tsx": () => import("../components/mockups/chat-usability/AccessibleReadable.tsx"),
  "./components/mockups/chat-usability/ClearHierarchy.tsx": () => import("../components/mockups/chat-usability/ClearHierarchy.tsx"),
  "./components/mockups/chat-usability/StrongAffordance.tsx": () => import("../components/mockups/chat-usability/StrongAffordance.tsx"),
  "./components/mockups/chat-welcome-polish/ElevatedCards.tsx": () => import("../components/mockups/chat-welcome-polish/ElevatedCards.tsx"),
  "./components/mockups/chat-welcome-polish/TighterRhythm.tsx": () => import("../components/mockups/chat-welcome-polish/TighterRhythm.tsx"),
  "./components/mockups/decision-bar/Entrevista.tsx": () => import("../components/mockups/decision-bar/Entrevista.tsx"),
  "./components/mockups/decision-bar/Passive.tsx": () => import("../components/mockups/decision-bar/Passive.tsx"),
  "./components/mockups/decision-bar/Proposta.tsx": () => import("../components/mockups/decision-bar/Proposta.tsx"),
  "./components/mockups/decision-bar/Triagem.tsx": () => import("../components/mockups/decision-bar/Triagem.tsx"),
  "./components/mockups/funil-elevenlabs/FunilElevenLabs.tsx": () => import("../components/mockups/funil-elevenlabs/FunilElevenLabs.tsx"),
  "./components/mockups/toasts-sonner/SonnerToasts.tsx": () => import("../components/mockups/toasts-sonner/SonnerToasts.tsx"),
  "./components/mockups/toasts-sonner/TemplateSuggestionToastMockup.tsx": () => import("../components/mockups/toasts-sonner/TemplateSuggestionToastMockup.tsx"),
  "./components/mockups/triagem-flow/ChatScreen.tsx": () => import("../components/mockups/triagem-flow/ChatScreen.tsx"),
  "./components/mockups/triagem-flow/CompletionScreen.tsx": () => import("../components/mockups/triagem-flow/CompletionScreen.tsx"),
  "./components/mockups/triagem-flow/ConfirmationScreen.tsx": () => import("../components/mockups/triagem-flow/ConfirmationScreen.tsx"),
  "./components/mockups/triagem-flow/WelcomeScreen.tsx": () => import("../components/mockups/triagem-flow/WelcomeScreen.tsx"),
  "./components/mockups/wsi-report/Tab1Respostas.tsx": () => import("../components/mockups/wsi-report/Tab1Respostas.tsx"),
  "./components/mockups/wsi-report/Tab2Aprovado.tsx": () => import("../components/mockups/wsi-report/Tab2Aprovado.tsx"),
  "./components/mockups/wsi-report/Tab2Pendente.tsx": () => import("../components/mockups/wsi-report/Tab2Pendente.tsx"),
  "./components/mockups/weekly-digest/BellNotification.tsx": () => import("../components/mockups/weekly-digest/BellNotification.tsx"),
  "./components/mockups/weekly-digest/ChatFlutuante.tsx": () => import("../components/mockups/weekly-digest/ChatFlutuante.tsx"),
  "./components/mockups/weekly-digest/TeamsAdaptiveCard.tsx": () => import("../components/mockups/weekly-digest/TeamsAdaptiveCard.tsx")
};
