"""ATS Integration Domain - Action definitions."""
from app.domains.base import DomainAction

ATS_INTEGRATION_ACTIONS = [
    DomainAction(
        action_id="sync_candidate",
        name="Sincronizar Candidato",
        description="Sincronizar dados de candidato com o ATS externo",
        required_params=["candidate_id"],
        optional_params=["ats_provider", "connection_id"],
    ),
    DomainAction(
        action_id="sync_job",
        name="Sincronizar Vaga",
        description="Sincronizar dados de vaga com o ATS externo",
        required_params=["job_id"],
        optional_params=["ats_provider", "connection_id"],
    ),
    DomainAction(
        action_id="bulk_sync",
        name="Sincronização em Massa",
        description="Executar sincronização em massa de múltiplos registros",
        required_params=["sync_type"],
        optional_params=["ats_provider", "connection_id", "filters"],
        requires_confirmation=True,
    ),
    DomainAction(
        action_id="pull_candidates",
        name="Importar Candidatos",
        description="Importar candidatos do ATS externo para o WedoTalent",
        optional_params=["ats_provider", "connection_id", "job_id", "limit"],
    ),
    DomainAction(
        action_id="pull_jobs",
        name="Importar Vagas",
        description="Importar vagas do ATS externo para o WedoTalent",
        optional_params=["ats_provider", "connection_id", "status", "limit"],
    ),
    DomainAction(
        action_id="check_sync_status",
        name="Verificar Status da Sincronização",
        description="Verificar o status atual da sincronização com o ATS",
        optional_params=["connection_id", "sync_job_id"],
    ),
    DomainAction(
        action_id="configure_ats",
        name="Configurar ATS",
        description="Configurar conexão e credenciais do ATS externo",
        required_params=["ats_provider"],
        optional_params=["api_key", "api_endpoint", "company_id"],
        requires_confirmation=True,
    ),
    DomainAction(
        action_id="list_connections",
        name="Listar Conexões ATS",
        description="Listar conexões ATS configuradas",
        optional_params=["ats_provider", "is_active"],
    ),
    DomainAction(
        action_id="test_connection",
        name="Testar Conexão",
        description="Testar a saúde da conexão com o ATS",
        optional_params=["connection_id", "ats_provider"],
    ),
    DomainAction(
        action_id="map_fields",
        name="Mapear Campos",
        description="Configurar mapeamento de campos entre sistemas",
        required_params=["connection_id"],
        optional_params=["field_mappings"],
        requires_confirmation=True,
    ),
    DomainAction(
        action_id="view_sync_log",
        name="Ver Log de Sincronização",
        description="Visualizar log de auditoria de sincronização",
        optional_params=["connection_id", "sync_job_id", "limit"],
    ),
    DomainAction(
        action_id="resolve_conflict",
        name="Resolver Conflito de Dados",
        description="Resolver conflitos de dados entre sistemas WedoTalent e ATS",
        required_params=["conflict_id"],
        optional_params=["resolution_strategy"],
        requires_confirmation=True,
    ),
    DomainAction(
        action_id="update_status_ats",
        name="Atualizar Status no ATS",
        description="Enviar atualização de status do candidato para o ATS externo",
        required_params=["candidate_id", "new_status"],
        optional_params=["connection_id", "reason"],
    ),
    DomainAction(
        action_id="send_score_ats",
        name="Enviar Score para ATS",
        description="Enviar score/parecer WSI do candidato para o ATS externo",
        required_params=["candidate_id"],
        optional_params=["connection_id", "score", "parecer"],
    ),
    DomainAction(
        action_id="sync_interview_result",
        name="Sincronizar Resultado de Entrevista",
        description="Sincronizar resultados de entrevista com o ATS externo",
        required_params=["interview_id"],
        optional_params=["connection_id", "candidate_id"],
    ),
    DomainAction(
        action_id="enable_webhook",
        name="Ativar Webhook",
        description="Ativar webhook para sincronização em tempo real com o ATS",
        required_params=["connection_id"],
        optional_params=["events"],
    ),
    DomainAction(
        action_id="disable_webhook",
        name="Desativar Webhook",
        description="Desativar webhook de sincronização com o ATS",
        required_params=["connection_id"],
    ),
    DomainAction(
        action_id="view_field_mapping",
        name="Ver Mapeamento de Campos",
        description="Visualizar mapeamento atual de campos entre sistemas",
        optional_params=["connection_id", "ats_provider"],
    ),
]
