# frozen_string_literal: true

class InterviewSerializer
  include JSONAPI::Serializer

  attributes(
    :id,
    :company_id,
    :title,
    :description,
    :interview_type,
    :interview_mode,
    :candidate_id,
    :candidate_name,
    :candidate_email,
    :interviewer_name,
    :interviewer_email,
    :additional_interviewers,
    :start_time,
    :end_time,
    :timezone,
    :duration_minutes,
    :location,
    :meeting_url,
    :meeting_platform,
    :meeting_id,
    :graph_event_id,
    :graph_calendar_id,
    :graph_organizer_email,
    :is_synced_to_calendar,
    :calendar_sync_error,
    :last_synced_at,
    :google_event_id,
    :google_meet_link,
    :status,
    :confirmation_status,
    :reminder_sent,
    :reminder_sent_at,
    :confirmation_request_sent,
    :confirmation_request_sent_at,
    :job_vacancy_id,
    :job_title,
    :application_stage,
    :feedback,
    :interviewer_notes,
    :recording_url,
    :lia_preparation_notes,
    :lia_suggested_questions,
    :created_by,
    :cancelled_at,
    :cancellation_reason,
    :created_at,
    :updated_at
  )
end
