from app.domains.analytics.services.agent_monitoring_service import *
from app.domains.analytics.services.candidate_report_service import *
from app.domains.analytics.services.job_analytics_prompt_service import *
from app.domains.analytics.services.job_insights_service import *
from app.domains.analytics.services.job_report_service import *
from app.domains.analytics.services.predictive_analytics_service import *
from app.domains.analytics.services.report_service import *
from app.domains.analytics.services.search_analytics_service import *
from app.domains.analytics.services.wizard_analytics_service import *
