"""
OfferLetterService — E10 (Proposta & Negociação).

Builds a personalised offer letter by merging:

1. Company hiring policy (CompanyHiringPolicy)
2. Company benefits (CompanyBenefit)
3. Job vacancy data (JobVacancy: title, salary_range, etc.)
4. Candidate snapshot (name + email)

The letter body is rendered by ``ReportTemplates.offer_letter`` and the
narrative greeting/context block is generated by an LLM (Claude by
default, same stack as the JD generator). The service degrades
gracefully to a deterministic template-only letter when the LLM is
unavailable, so this code path stays safe in tests and offline use.
"""
from __future__ import annotations

import logging
from typing import Any

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.templates.report_templates import report_templates

logger = logging.getLogger(__name__)


class OfferLetterService:
    """Generate offer letters and decide approval requirements."""

    DEFAULT_LLM_PROVIDER = "claude"
    DEFAULT_LLM_MODEL = "claude-sonnet"

    # Approval-chain thresholds (annual gross compensation, BRL).
    # Used by ``required_approval_level`` to decide who has to sign off.
    APPROVAL_THRESHOLDS = {
        "manager": 0,            # default approver
        "director": 180_000,     # >= R$ 15k/month
        "vp_or_cfo": 360_000,    # >= R$ 30k/month
    }

    async def build_letter(
        self,
        *,
        company_id: str,
        candidate_name: str,
        job_title: str,
        candidate_email: str | None = None,
        manager_name: str | None = None,
        company_name: str | None = None,
        currency: str = "BRL",
        salary: float | None = None,
        bonus_pct: float | None = None,
        bonus_target: float | None = None,
        benefits: list[str] | None = None,
        start_date: str | None = None,
        response_deadline: str | None = None,
        custom_clauses: list[str] | None = None,
        job_vacancy_id: str | None = None,
        db: AsyncSession | None = None,
        use_llm: bool = True,
    ) -> dict[str, Any]:
        """Render the letter (HTML + Markdown) and return template metadata."""
        merged_benefits = list(benefits or [])
        if db is not None and not merged_benefits:
            merged_benefits = await self._load_company_benefits(db, company_id)

        if db is not None and not company_name:
            company_name = await self._load_company_name(db, company_id)

        # Merge job vacancy data — title fallback, salary/currency midpoint
        # when caller did not pass an explicit value.
        vacancy_data: dict[str, Any] = {}
        if db is not None and job_vacancy_id:
            vacancy_data = await self._load_job_vacancy(db, job_vacancy_id)
            if vacancy_data:
                if not job_title and vacancy_data.get("title"):
                    job_title = vacancy_data["title"]
                sr = vacancy_data.get("salary_range") or {}
                if salary is None and isinstance(sr, dict) and sr.get("min") is not None:
                    try:
                        lo = float(sr.get("min") or 0)
                        hi = float(sr.get("max") or lo)
                        salary = (lo + hi) / 2 if hi > lo else lo
                        currency = sr.get("currency") or currency
                    except (TypeError, ValueError):
                        pass

        # Merge hiring-policy clauses (notice period, probation, etc.)
        policy_clauses = await self._load_policy_clauses(db, company_id) if db else []
        merged_clauses = list(custom_clauses or [])
        for clause in policy_clauses:
            if clause and clause not in merged_clauses:
                merged_clauses.append(clause)

        llm_body_markdown: str | None = None
        provider_used: str | None = None
        model_used: str | None = None
        if use_llm:
            llm_body_markdown, provider_used, model_used = await self._generate_llm_body(
                candidate_name=candidate_name,
                job_title=job_title,
                company_name=company_name or "a empresa",
                salary=salary,
                currency=currency,
                benefits=merged_benefits,
            )

        rendered = report_templates.offer_letter(
            {
                "candidate_name": candidate_name,
                "job_title": job_title,
                "company_name": company_name or "Sua Empresa",
                "manager_name": manager_name,
                "currency": currency,
                "salary": salary,
                "bonus_pct": bonus_pct,
                "bonus_target": bonus_target,
                "benefits": merged_benefits,
                "start_date": start_date,
                "response_deadline": response_deadline,
                "custom_clauses": merged_clauses,
                "llm_body_markdown": llm_body_markdown,
            }
        )

        return {
            "html": rendered["html"],
            "markdown": rendered["markdown"],
            "template_version": rendered["version"],
            "llm_provider": provider_used,
            "llm_model": model_used,
            "merged_benefits": merged_benefits,
            "merged_clauses": merged_clauses,
            "vacancy_data": vacancy_data,
            "salary": salary,
            "currency": currency,
            "candidate_email": candidate_email,
        }

    def required_approval_level(self, *, salary: float | None, bonus_target: float | None = None) -> str:
        """
        Pick which internal approver needs to sign off based on
        annualised gross comp. Falls back to "manager" when salary
        information is missing.
        """
        if salary is None:
            return "manager"
        annual = float(salary) * 12 + float(bonus_target or 0)
        level = "manager"
        for candidate, threshold in self.APPROVAL_THRESHOLDS.items():
            if annual >= threshold:
                level = candidate
        return level

    @staticmethod
    def append_round(
        rounds: list[dict[str, Any]] | None,
        *,
        round_type: str,
        actor: str,
        actor_name: str | None = None,
        actor_email: str | None = None,
        salary: float | None = None,
        bonus_pct: float | None = None,
        currency: str = "BRL",
        benefits: list[str] | None = None,
        message: str | None = None,
    ) -> list[dict[str, Any]]:
        """Append a structured round entry (audit trail)."""
        from datetime import datetime

        history = list(rounds or [])
        next_round = len(history) + 1
        history.append(
            {
                "round": next_round,
                "type": round_type,
                "actor": actor,
                "actor_name": actor_name,
                "actor_email": actor_email,
                "salary": salary,
                "bonus_pct": bonus_pct,
                "currency": currency,
                "benefits": list(benefits or []),
                "message": message,
                "created_at": datetime.utcnow().isoformat(),
            }
        )
        return history

    # ──────────────────────────────────────────────────────────────────
    # Internals
    # ──────────────────────────────────────────────────────────────────

    async def _load_company_benefits(self, db: AsyncSession, company_id: str) -> list[str]:
        try:
            from lia_models.company_benefit import CompanyBenefit

            result = await db.execute(
                select(CompanyBenefit)
                .where(CompanyBenefit.company_id == str(company_id))
                .where(CompanyBenefit.is_active.is_(True))
                .order_by(CompanyBenefit.order)
            )
            rows = list(result.scalars().all())
            return [r.name for r in rows if getattr(r, "name", None)]
        except Exception as exc:  # pragma: no cover - defensive
            logger.warning("Could not load company benefits for %s: %s", company_id, exc)
            return []

    async def _load_job_vacancy(self, db: AsyncSession, job_vacancy_id: str) -> dict[str, Any]:
        """Load minimal vacancy fields used in the letter merge."""
        try:
            from uuid import UUID

            from lia_models.job_vacancy import JobVacancy

            try:
                vid = UUID(str(job_vacancy_id))
            except (ValueError, TypeError):
                return {}
            result = await db.execute(select(JobVacancy).where(JobVacancy.id == vid).limit(1))
            row = result.scalar_one_or_none()
            if not row:
                return {}
            return {
                "title": getattr(row, "title", None),
                "seniority_level": getattr(row, "seniority_level", None),
                "salary_range": getattr(row, "salary_range", None),
                "bonus_range": getattr(row, "bonus_range", None),
            }
        except Exception as exc:  # pragma: no cover - defensive
            logger.debug("Could not load JobVacancy %s: %s", job_vacancy_id, exc)
            return {}

    async def _load_policy_clauses(self, db: AsyncSession, company_id: str) -> list[str]:
        """Pull standard contract clauses from the company hiring policy."""
        try:
            from lia_models.company_hiring_policy import CompanyHiringPolicy

            result = await db.execute(
                select(CompanyHiringPolicy)
                .where(CompanyHiringPolicy.company_id == str(company_id))
                .limit(1)
            )
            row = result.scalar_one_or_none()
            if not row:
                return []
            clauses: list[str] = []
            policy_blocks = [
                getattr(row, "automation_rules", None),
                getattr(row, "communication_rules", None),
                getattr(row, "screening_rules", None),
            ]
            for block in policy_blocks:
                if isinstance(block, dict):
                    extra = block.get("offer_letter_clauses") or block.get("contract_clauses")
                    if isinstance(extra, list):
                        clauses.extend([str(c) for c in extra if c])
            return clauses
        except Exception as exc:  # pragma: no cover - defensive
            logger.debug("Could not load hiring policy for %s: %s", company_id, exc)
            return []

    async def resolve_approver(
        self,
        db: AsyncSession,
        company_id: str,
        approval_level: str,
    ) -> dict[str, str] | None:
        """
        Pick an internal approver from the company's user directory based on
        the required approval level. Returns ``{"name", "email", "role"}`` or
        ``None`` when no suitable approver is configured (caller can then
        require an explicit approver).
        """
        try:
            from lia_models.client_user import ClientUser, ClientUserRole, ClientUserStatus

            # Map our 3 thresholds to the ClientUser role chain.
            role_priority = {
                "manager": [ClientUserRole.MANAGER.value, ClientUserRole.ADMIN.value],
                "director": [ClientUserRole.ADMIN.value, ClientUserRole.MANAGER.value],
                "vp_or_cfo": [ClientUserRole.ADMIN.value],
            }.get(approval_level, [ClientUserRole.ADMIN.value, ClientUserRole.MANAGER.value])

            for role in role_priority:
                stmt = (
                    select(ClientUser)
                    .where(ClientUser.company_id == str(company_id))
                    .where(ClientUser.role == role)
                    .where(ClientUser.status == ClientUserStatus.ACTIVE.value)
                    .order_by(ClientUser.created_at.asc())
                    .limit(1)
                )
                result = await db.execute(stmt)
                user = result.scalar_one_or_none()
                if user and getattr(user, "email", None):
                    return {
                        "name": getattr(user, "name", None) or user.email,
                        "email": user.email,
                        "role": role,
                    }
            return None
        except Exception as exc:  # pragma: no cover - defensive
            logger.debug("Could not resolve approver for %s/%s: %s", company_id, approval_level, exc)
            return None

    async def _load_company_name(self, db: AsyncSession, company_id: str) -> str | None:
        try:
            from lia_models.company import CompanyProfile

            result = await db.execute(
                select(CompanyProfile.name).where(CompanyProfile.id == company_id).limit(1)
            )
            row = result.scalar_one_or_none()
            return row
        except Exception as exc:  # pragma: no cover - defensive
            logger.debug("Could not load company name for %s: %s", company_id, exc)
            return None

    async def _generate_llm_body(
        self,
        *,
        candidate_name: str,
        job_title: str,
        company_name: str,
        salary: float | None,
        currency: str,
        benefits: list[str],
    ) -> tuple[str | None, str | None, str | None]:
        """
        Generate the narrative greeting/context block via LLM.
        Returns (markdown_body, provider, model). Returns (None, None, None)
        when the LLM is unavailable so the template renders the
        deterministic fallback.
        """
        try:
            from app.domains.ai.services.llm import llm_service
        except Exception as exc:  # pragma: no cover - defensive
            logger.info("LLM service unavailable, falling back to template body: %s", exc)
            return None, None, None

        salary_part = (
            f"O pacote inclui salário-base de {currency} {salary:,.2f}/mês."
            if salary is not None
            else "Os termos financeiros estão detalhados na seção 'Termos da Proposta' abaixo."
        )
        benefits_part = (
            "Benefícios destacados: " + ", ".join(benefits[:5]) + "."
            if benefits
            else ""
        )
        prompt = (
            "Você é um redator de cartas-proposta de emprego para a equipe de "
            "recrutamento da empresa abaixo. Escreva um parágrafo de abertura "
            "caloroso e profissional (3 a 5 frases) que personalize a proposta "
            "para o(a) candidato(a). Não invente valores nem benefícios — "
            "use apenas as informações fornecidas. Não use bullet points.\n\n"
            f"Empresa: {company_name}\n"
            f"Candidato(a): {candidate_name}\n"
            f"Cargo: {job_title}\n"
            f"{salary_part}\n"
            f"{benefits_part}\n\n"
            "Responda apenas com o parágrafo de abertura em português, sem cabeçalho."
        )
        try:
            response = await llm_service.generate(prompt, provider=self.DEFAULT_LLM_PROVIDER)
            if not response or not response.strip():
                return None, None, None
            return response.strip(), self.DEFAULT_LLM_PROVIDER, self.DEFAULT_LLM_MODEL
        except Exception as exc:
            logger.warning("LLM offer-letter body generation failed: %s", exc)
            return None, None, None


offer_letter_service = OfferLetterService()
