from __future__ import annotations

from app.domains.base import DomainAction

JOB_MANAGEMENT_ACTIONS: list[DomainAction] = [
    DomainAction(action_id="create_job", name="Criar vaga", description="Criar nova vaga via conversa"),
    DomainAction(action_id="guided_wizard", name="Wizard guiado", description="Fluxo conversacional guiado para criação de vaga"),
    DomainAction(action_id="extract_requirements", name="Extrair requisitos", description="Extrair requisitos de uma job description usando IA"),
    DomainAction(action_id="generate_rubrics", name="Gerar rubricas", description="Gerar requisitos estruturados para sistema de Rubricas"),
    DomainAction(action_id="update_job", name="Atualizar vaga", description="Atualizar vaga existente"),
    DomainAction(action_id="health_check", name="Health check", description="Verificar saúde da vaga"),
    DomainAction(action_id="suggest_strategy", name="Sugerir estratégia", description="Sugerir mudanças de estratégia"),
    DomainAction(action_id="duplicate_job", name="Duplicar vaga", description="Duplicar vaga existente com todos os dados"),
    DomainAction(action_id="create_from_template", name="Criar de template", description="Criar nova vaga usando outra como template"),
    DomainAction(action_id="clone_job", name="Clonar vaga", description="Clonar vaga existente"),
    DomainAction(action_id="close_job", name="Fechar vaga", description="Fechar/arquivar vaga"),
    DomainAction(action_id="pause_job", name="Pausar vaga", description="Pausar vaga temporariamente"),
    DomainAction(action_id="get_benefits", name="Obter benefícios", description="Obter benefícios da empresa para a vaga"),
    DomainAction(action_id="suggest_jd_improvements", name="Melhorar JD", description="Sugerir melhorias para job description com IA"),
    DomainAction(action_id="detect_criteria", name="Detectar critérios", description="Detectar critérios automaticamente da descrição"),
    DomainAction(action_id="generate_wsi_questions", name="Gerar perguntas WSI", description="Gerar perguntas de triagem WSI"),
    DomainAction(action_id="advance_wizard_step", name="Avançar etapa", description="Avançar para próxima etapa do wizard"),
    DomainAction(action_id="get_wizard_step_data", name="Dados da etapa", description="Obter dados da etapa atual do wizard"),
    DomainAction(action_id="enrich_jd", name="Enriquecer JD", description="Enriquecer job description com IA"),
    DomainAction(action_id="import_jd", name="Importar JD", description="Importar job description existente"),
    DomainAction(action_id="generate_jd", name="Gerar JD", description="Gerar job description completa com IA"),
    DomainAction(action_id="job_analytics", name="Analytics de vagas", description="Métricas e analytics de vagas"),
    DomainAction(action_id="qualify_job", name="Qualificar vaga", description="Qualificar vaga para publicação"),
    DomainAction(action_id="publish_job", name="Publicar vaga", description="Publicar vaga em job boards"),
    DomainAction(action_id="job_status_webhook", name="Webhook de status", description="Gerenciar webhooks de status"),
    DomainAction(action_id="search_templates", name="Buscar templates", description="Buscar templates de vaga"),
    DomainAction(action_id="apply_template", name="Aplicar template", description="Aplicar template a nova vaga"),
    DomainAction(action_id="analyze_jd", name="Analisar JD", description="Avaliar qualidade da job description"),
    DomainAction(action_id="suggest_compensation", name="Sugerir compensação", description="Sugerir faixa de compensação"),
]
