default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: "<%= ENV['POSTGRES_USER'] %>"
  password: "<%= ENV['POSTGRES_PASSWORD'] %>"
  host: db
  port: 5432
  sslmode: disable

development:
  <<: *default
  database: ats_api_development

test:
  <<: *default
  database: ats_api_test

production:
  <<: *default
  database: land_production
  sslmode: require
  username: <%= ENV["database_user"] %>
  password: <%= ENV["database_pass"] %>
  host: <%= ENV["host"] %>
  port: <%= ENV["port"] %>
  pool: 30
  reaping_frequency: 12
  prepared_statements: false
  advisory_locks: false
