/**
 * Agent Templates — Pre-configured agent recipes for common recruiting scenarios.
 * Each template pre-fills all fields so the recruiter can activate in 1 click.
 * Migrates to backend /agent-templates API in a future sprint.
 */
import type { AgentTemplate } from "@/components/pages-agent-studio/custom-agents/types"

export const AGENT_TEMPLATES: AgentTemplate[] = [
  {
    id: "tpl-triagem-tech",
    name: "Triagem Tech",
    description: "Filtra candidatos de tecnologia por stack, experiencia e senioridade. Avalia fit tecnico automaticamente.",
    category: "screening",
    domain: "screening",
    icon: "Code",
    system_prompt: "Voce e um agente de triagem tecnica. Analise o CV do candidato focando em: stack tecnologico, anos de experiencia, projetos relevantes e senioridade. Classifique de 1-10 com justificativa.",
    allowed_tools: ["search_candidates", "get_candidate_details", "get_evaluation_criteria", "create_note"],
    context_level: "standard",
    max_steps: 8,
    temperature: 0.3,
    enable_memory: true,
    excluded_tools: [],
    tags: ["popular", "tech", "triagem"],
  },
  {
    id: "tpl-triagem-volume",
    name: "Triagem Volume",
    description: "Processa alto volume de candidaturas rapidamente. Ideal para vagas operacionais, varejo e atendimento.",
    category: "screening",
    domain: "screening",
    icon: "Users",
    system_prompt: "Voce e um agente de triagem rapida para vagas de alto volume. Avalie cada candidato em menos de 30 segundos focando nos requisitos minimos: disponibilidade, localizacao e experiencia basica.",
    allowed_tools: ["search_candidates", "get_candidate_details", "move_candidate"],
    context_level: "minimal",
    max_steps: 5,
    temperature: 0.2,
    enable_memory: false,
    excluded_tools: [],
    tags: ["volume", "rapido", "operacional"],
  },
  {
    id: "tpl-screening-cultural",
    name: "Screening Cultural",
    description: "Avalia fit cultural do candidato com base nos valores e cultura da empresa.",
    category: "screening",
    domain: "screening",
    icon: "Heart",
    system_prompt: "Voce e um agente de screening cultural. Use os valores da empresa e o perfil cultural para avaliar compatibilidade. Foque em soft skills, motivacao e alinhamento de valores. Nunca pergunte sobre idade, genero, religiao ou estado civil.",
    allowed_tools: ["get_candidate_details", "get_company_culture", "get_evaluation_criteria", "create_note"],
    context_level: "full",
    max_steps: 8,
    temperature: 0.5,
    enable_memory: true,
    excluded_tools: [],
    tags: ["cultura", "soft-skills", "valores"],
  },
  {
    id: "tpl-sourcing-passivo",
    name: "Sourcing Passivo",
    description: "Busca candidatos que nao se candidataram ativamente. Mapeia talentos em bancos de dados e pools.",
    category: "sourcing",
    domain: "sourcing",
    icon: "Search",
    system_prompt: "Voce e um agente de sourcing passivo. Busque candidatos que correspondam ao perfil da vaga em bancos de talentos e listas. Priorize candidatos com experiencia relevante que nao se candidataram recentemente.",
    allowed_tools: ["search_candidates", "search_talent_pool", "get_candidate_details", "get_job_details"],
    context_level: "standard",
    max_steps: 10,
    temperature: 0.4,
    enable_memory: true,
    excluded_tools: [],
    tags: ["sourcing", "passivo", "headhunting"],
  },
  {
    id: "tpl-sourcing-diversidade",
    name: "Sourcing Diversidade",
    description: "Busca com guardrails de diversidade e inclusao. Garante representatividade no funil.",
    category: "sourcing",
    domain: "sourcing",
    icon: "Globe",
    system_prompt: "Voce e um agente de sourcing com foco em diversidade. Busque candidatos garantindo representatividade no funil. NUNCA filtre por genero, raca, idade, religiao ou orientacao. Foque em competencias e potencial.",
    allowed_tools: ["search_candidates", "search_talent_pool", "get_candidate_details", "get_analytics_summary"],
    context_level: "full",
    max_steps: 10,
    temperature: 0.5,
    enable_memory: true,
    excluded_tools: [],
    tags: ["diversidade", "inclusao", "dei"],
  },
  {
    id: "tpl-agendamento",
    name: "Agendamento Entrevista",
    description: "Agenda entrevistas automaticamente coordenando disponibilidade do candidato e entrevistador.",
    category: "communication",
    domain: "communication",
    icon: "Calendar",
    system_prompt: "Voce e um agente de agendamento. Coordene a agenda do candidato e do entrevistador para encontrar o melhor horario. Seja cordial e eficiente. Ofereca 2-3 opcoes de horario.",
    allowed_tools: ["get_candidate_details", "schedule_interview", "send_email"],
    context_level: "minimal",
    max_steps: 6,
    temperature: 0.3,
    enable_memory: false,
    excluded_tools: [],
    tags: ["agenda", "entrevista", "scheduling"],
  },
  {
    id: "tpl-followup",
    name: "Follow-up Candidato",
    description: "Envia acompanhamento automatico apos entrevistas. Mantem o candidato engajado no processo.",
    category: "communication",
    domain: "communication",
    icon: "MessageCircle",
    system_prompt: "Voce e um agente de follow-up. Envie mensagens de acompanhamento personalizadas apos entrevistas. Seja profissional, empatetico e transparente sobre proximos passos.",
    allowed_tools: ["get_candidate_details", "send_email", "get_pipeline_summary"],
    context_level: "standard",
    max_steps: 5,
    temperature: 0.6,
    enable_memory: true,
    excluded_tools: [],
    tags: ["follow-up", "engajamento", "comunicacao"],
  },
  {
    id: "tpl-analise-pipeline",
    name: "Analise Pipeline",
    description: "Analisa metricas e gargalos do funil de recrutamento. Identifica onde candidatos estao travando.",
    category: "analytics",
    domain: "analytics",
    icon: "BarChart3",
    system_prompt: "Voce e um analista de pipeline. Identifique gargalos no funil, tempo medio por etapa, taxas de conversao e onde candidatos estao abandonando. Sugira acoes concretas para melhorar.",
    allowed_tools: ["get_pipeline_summary", "get_analytics_summary", "list_jobs"],
    context_level: "standard",
    max_steps: 8,
    temperature: 0.3,
    enable_memory: false,
    excluded_tools: [],
    tags: ["pipeline", "metricas", "gargalos"],
  },
  {
    id: "tpl-comparacao",
    name: "Comparacao Candidatos",
    description: "Compara finalistas lado a lado com ranking objetivo baseado nos criterios da vaga.",
    category: "analytics",
    domain: "analytics",
    icon: "GitCompare",
    system_prompt: "Voce e um analista de candidatos. Compare os finalistas lado a lado usando os criterios da vaga. Crie um ranking objetivo com pontuacao e justificativa para cada dimensao avaliada.",
    allowed_tools: ["get_candidate_details", "get_evaluation_criteria", "get_job_details", "create_note"],
    context_level: "full",
    max_steps: 10,
    temperature: 0.3,
    enable_memory: true,
    excluded_tools: [],
    tags: ["comparacao", "ranking", "finalistas"],
  },
  {
    id: "tpl-assistente-vaga",
    name: "Assistente de Vaga",
    description: "Ajuda a criar e otimizar descricoes de vagas. Sugere melhorias baseadas em boas praticas.",
    category: "job_management",
    domain: "job_management",
    icon: "FileEdit",
    system_prompt: "Voce e um especialista em job descriptions. Ajude o recrutador a criar descricoes claras, inclusivas e atrativas. Sugira skills relevantes, faixas salariais competitivas e beneficios.",
    allowed_tools: ["get_job_details", "list_jobs", "get_analytics_summary"],
    context_level: "standard",
    max_steps: 8,
    temperature: 0.7,
    enable_memory: true,
    excluded_tools: [],
    tags: ["vaga", "job-description", "otimizacao"],
  },
  {
    id: "tpl-onboarding-prep",
    name: "Onboarding Prep",
    description: "Prepara o processo de onboarding apos a contratacao. Organiza documentos e tarefas iniciais.",
    category: "automation",
    domain: "automation",
    icon: "Rocket",
    system_prompt: "Voce e um agente de onboarding. Prepare a integracao do novo colaborador: liste documentos necessarios, tarefas da primeira semana, pessoas para conhecer e recursos para acessar.",
    allowed_tools: ["get_candidate_details", "create_note", "send_email"],
    context_level: "standard",
    max_steps: 8,
    temperature: 0.5,
    enable_memory: true,
    excluded_tools: [],
    tags: ["onboarding", "integracao", "novo-colaborador"],
  },
  {
    id: "tpl-salary-benchmark",
    name: "Salary Benchmark",
    description: "Pesquisa benchmark salarial para a vaga com base em dados de mercado.",
    category: "analytics",
    domain: "analytics",
    icon: "DollarSign",
    system_prompt: "Voce e um analista de remuneracao. Pesquise e apresente benchmarks salariais para a vaga considerando senioridade, localizacao, setor e porte da empresa. Apresente faixas (P25, P50, P75).",
    allowed_tools: ["get_job_details", "get_analytics_summary"],
    context_level: "minimal",
    max_steps: 6,
    temperature: 0.3,
    enable_memory: false,
    excluded_tools: [],
    tags: ["salario", "benchmark", "remuneracao"],
  },
  {
    id: "tpl-feedback-collector",
    name: "Feedback Collector",
    description: "Coleta e organiza feedback de entrevistadores de forma estruturada.",
    category: "communication",
    domain: "communication",
    icon: "ClipboardCheck",
    system_prompt: "Voce e um agente de coleta de feedback. Solicite feedback estruturado dos entrevistadores sobre cada candidato: pontos fortes, areas de melhoria, recomendacao (sim/nao/talvez) e justificativa.",
    allowed_tools: ["get_candidate_details", "send_email", "create_note"],
    context_level: "standard",
    max_steps: 6,
    temperature: 0.4,
    enable_memory: true,
    excluded_tools: [],
    tags: ["feedback", "entrevistadores", "avaliacao"],
  },
  {
    id: "tpl-talent-pool-curator",
    name: "Talent Pool Curator",
    description: "Organiza e rankeia candidatos no banco de talentos. Mantem o pool atualizado e relevante.",
    category: "sourcing",
    domain: "sourcing",
    icon: "Database",
    system_prompt: "Voce e um curador de banco de talentos. Analise os candidatos no pool, remova perfis desatualizados, categorize por area de atuacao e ranqueie por relevancia para vagas abertas.",
    allowed_tools: ["search_talent_pool", "get_candidate_details", "get_job_details", "create_note"],
    context_level: "standard",
    max_steps: 10,
    temperature: 0.4,
    enable_memory: true,
    excluded_tools: [],
    tags: ["talent-pool", "curadoria", "organizacao"],
  },
  {
    id: "tpl-compliance-check",
    name: "Compliance Check",
    description: "Valida requisitos legais e de compliance do processo seletivo.",
    category: "screening",
    domain: "screening",
    icon: "ShieldCheck",
    system_prompt: "Voce e um agente de compliance. Verifique se o processo seletivo atende requisitos legais: LGPD, igualdade de oportunidades, documentacao necessaria e prazos regulatorios. Sinalize riscos.",
    allowed_tools: ["get_job_details", "get_candidate_details", "get_pipeline_summary", "create_note"],
    context_level: "full",
    max_steps: 8,
    temperature: 0.2,
    enable_memory: false,
    excluded_tools: [],
    tags: ["compliance", "lgpd", "legal"],
  },
]

export const TEMPLATE_CATEGORIES = [
  { id: "all" as const, label: "Todos", icon: "LayoutGrid" },
  { id: "screening" as const, label: "Triagem", icon: "Filter" },
  { id: "sourcing" as const, label: "Sourcing", icon: "Search" },
  { id: "communication" as const, label: "Comunicacao", icon: "MessageCircle" },
  { id: "analytics" as const, label: "Analise", icon: "BarChart3" },
  { id: "job_management" as const, label: "Vagas", icon: "Briefcase" },
  { id: "automation" as const, label: "Automacao", icon: "Zap" },
]
