"""
Pydantic schemas for Intelligence Layer.
"""
from datetime import datetime
from typing import Optional, List, Dict, Any
from uuid import UUID
from pydantic import BaseModel, Field
from enum import Enum


class InsightType(str, Enum):
    """Types of insights generated by the Intelligence Layer."""
    PATTERN = "pattern"
    PREDICTION = "prediction"
    CORRELATION = "correlation"
    ADJUSTMENT = "adjustment"
    RECOMMENDATION = "recommendation"


class PatternType(str, Enum):
    """Types of patterns detected."""
    SALARY_CORRECTION = "salary_correction"
    SENIORITY_CORRECTION = "seniority_correction"
    SKILL_CORRECTION = "skill_correction"
    SUCCESS_PROFILE = "success_profile"
    TIME_TO_FILL = "time_to_fill"
    ACCEPTANCE_RATE = "acceptance_rate"


class CorrectionPatternBase(BaseModel):
    """Base schema for correction patterns."""
    field: str
    role_pattern: Optional[str] = None
    seniority: Optional[str] = None
    department: Optional[str] = None
    direction: str
    avg_adjustment: float
    min_adjustment: Optional[float] = None
    max_adjustment: Optional[float] = None
    std_deviation: Optional[float] = None
    sample_size: int = 0
    confidence: float = 0.0


class CorrectionPatternResponse(CorrectionPatternBase):
    """Response schema for correction patterns."""
    id: UUID
    company_id: str
    is_active: bool = True
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class SuccessProfileBase(BaseModel):
    """Base schema for success profiles."""
    role_pattern: Optional[str] = None
    seniority: Optional[str] = None
    department: Optional[str] = None
    optimal_salary_percentile: Optional[int] = None
    avg_salary: Optional[float] = None
    avg_time_to_fill: Optional[int] = None
    median_time_to_fill: Optional[int] = None
    must_have_skills: List[str] = Field(default_factory=list)
    common_skills: List[Dict[str, Any]] = Field(default_factory=list)
    avg_pipeline_length: Optional[int] = None
    avg_screening_questions: Optional[int] = None
    satisfaction_avg: Optional[float] = None
    success_rate: Optional[float] = None
    sample_size: int = 0
    confidence: float = 0.0


class SuccessProfileResponse(SuccessProfileBase):
    """Response schema for success profiles."""
    id: UUID
    company_id: str
    characteristics: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class OutcomeCorrelationBase(BaseModel):
    """Base schema for outcome correlations."""
    factor: str
    outcome_metric: str
    role_pattern: Optional[str] = None
    seniority: Optional[str] = None
    correlation: float
    significance: Optional[float] = None
    direction: Optional[str] = None
    recommendation: Optional[str] = None
    sample_size: int = 0


class OutcomeCorrelationResponse(OutcomeCorrelationBase):
    """Response schema for outcome correlations."""
    id: UUID
    company_id: str
    factor_values: Dict[str, Any] = Field(default_factory=dict)
    outcome_values: Dict[str, Any] = Field(default_factory=dict)
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class IntelligenceInsightCreate(BaseModel):
    """Schema for creating an intelligence insight."""
    company_id: str
    job_id: Optional[UUID] = None
    recruiter_id: Optional[str] = None
    insight_type: str
    field: Optional[str] = None
    original_value: Optional[Any] = None
    suggested_value: Optional[Any] = None
    confidence: float = 0.0
    source: Optional[str] = None
    reasoning: Optional[str] = None
    insight_metadata: Dict[str, Any] = Field(default_factory=dict)


class IntelligenceInsightResponse(IntelligenceInsightCreate):
    """Response schema for intelligence insights."""
    id: UUID
    was_applied: Optional[bool] = None
    was_accepted: Optional[bool] = None
    final_value: Optional[Any] = None
    created_at: datetime

    class Config:
        from_attributes = True


class IntelligenceInsightUpdate(BaseModel):
    """Schema for updating an intelligence insight."""
    was_applied: Optional[bool] = None
    was_accepted: Optional[bool] = None
    final_value: Optional[Any] = None


class PatternCacheResponse(BaseModel):
    """Response schema for pattern cache."""
    id: UUID
    company_id: str
    pattern_type: str
    pattern_key: str
    pattern_data: Dict[str, Any]
    sample_size: int
    confidence: float
    calculated_at: datetime
    expires_at: Optional[datetime] = None
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True


class FieldSuggestion(BaseModel):
    """Suggestion for a specific field from Intelligence Layer."""
    field: str
    value: Any
    confidence: float
    source: str
    action: str
    should_auto_apply: bool = False
    insights: List[str] = Field(default_factory=list)
    reasoning: Optional[str] = None


class OutcomePrediction(BaseModel):
    """Prediction of job outcomes."""
    predicted_time_to_fill: Optional[int] = None
    confidence: str
    risk_factors: List[str] = Field(default_factory=list)
    improvement_suggestions: List[str] = Field(default_factory=list)
    similar_jobs_count: int = 0


class IntelligenceReport(BaseModel):
    """Full intelligence report for a job context."""
    company_id: str
    role: Optional[str] = None
    seniority: Optional[str] = None
    
    correction_patterns: List[CorrectionPatternResponse] = Field(default_factory=list)
    success_profile: Optional[SuccessProfileResponse] = None
    correlations: List[OutcomeCorrelationResponse] = Field(default_factory=list)
    outcome_prediction: Optional[OutcomePrediction] = None
    
    suggestions: Dict[str, FieldSuggestion] = Field(default_factory=dict)
    
    confidence_summary: Dict[str, float] = Field(default_factory=dict)
    data_quality: str = "low"
    
    generated_at: datetime = Field(default_factory=datetime.utcnow)
