"""Prometheus counters for AI-critical fallback paths (REGRA 4 / CLAUDE.md).

REGRA 4 (Pydantic Conventions, registrada 2026-05-20): "Silent fallback em
path crítico de IA é PROIBIDO". Sem instrumentação, telemetria de status code
fica em 100% saúde enquanto a IA está degradada — feature broken por dias
sem que ninguém perceba (audit F6.B3).

Este módulo expõe dois Counter Prometheus low-cardinality que cada call site
de fallback DEVE incrementar antes de retornar template determinístico:

- WSI_FALLBACK_TEMPLATE — WSI question generation caiu em template
  (CBI/Dreyfus/Bloom/BigFive). Sites em
  app/domains/cv_screening/services/wsi_service/question_generator.py.

- WIZARD_FALLBACK — Wizard de criação de vaga caiu em lógica
  determinística (jd_enrichment/bigfive/wsi_questions). Sites em
  app/domains/job_creation/graph.py (via _emit_wizard_fallback_metric
  que delega aqui).

Pattern canônico (fail-open):

- Re-uso de Counter via REGISTRY._names_to_collectors (igual
  app/jobs/tenant_aware_task.py) — sobreviver a reload de módulo em dev.
- prometheus_client ausente NÃO quebra import — variáveis ficam None.
- Helpers inc_wsi_fallback / inc_wizard_fallback engolem qualquer
  exceção do client (fail-open).
- Cardinalidade controlada: labels são enums fechados, NUNCA tenant_id ou
  session_id (esses ficam no log estruturado, não na métrica).

Grafana alarms sugeridos:

- rate(wsi_fallback_template_total[5m]) > 0.05 → oncall warn
- rate(wizard_fallback_total[5m]) > 0.05 → oncall warn

Os labels (framework, node, reason) permitem drill-down por framework WSI
ou por estágio do wizard para identificar regressão localizada.
"""
from __future__ import annotations

import logging
from typing import Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Lazy + fail-open Counter setup.
# ---------------------------------------------------------------------------
_WSI_FALLBACK_TEMPLATE = None  # type: ignore[assignment]
_WIZARD_FALLBACK = None  # type: ignore[assignment]
_WSI_GENERATED = None  # type: ignore[assignment]
_WSI_BIAS_BLOCK = None  # type: ignore[assignment]

try:
    from prometheus_client import REGISTRY as _PROM_REGISTRY
    from prometheus_client import Counter as _PromCounter

    _registry_map = getattr(_PROM_REGISTRY, "_names_to_collectors", {})

    _WSI_NAME = "wsi_fallback_template_total"
    _existing_wsi = _registry_map.get(_WSI_NAME)
    if _existing_wsi is not None:
        _WSI_FALLBACK_TEMPLATE = _existing_wsi
    else:
        _WSI_FALLBACK_TEMPLATE = _PromCounter(
            _WSI_NAME,
            "WSI question generation fell back to deterministic template "
            "(LLM failed/invalid). REGRA 4 sensor.",
            labelnames=("framework", "reason"),
        )

    _WIZ_NAME = "wizard_fallback_total"
    _existing_wiz = _registry_map.get(_WIZ_NAME)
    if _existing_wiz is not None:
        _WIZARD_FALLBACK = _existing_wiz
    else:
        _WIZARD_FALLBACK = _PromCounter(
            _WIZ_NAME,
            "Job creation wizard fell back to deterministic logic "
            "(LLM timeout/error). REGRA 4 sensor.",
            labelnames=("node", "reason"),
        )

    # Audit C10/#10 (2026-06-05): denominador + bias-block do WSI question gen.
    _WSI_GEN_NAME = "wsi_questions_generated_total"
    _existing_gen = _registry_map.get(_WSI_GEN_NAME)
    if _existing_gen is not None:
        _WSI_GENERATED = _existing_gen
    else:
        _WSI_GENERATED = _PromCounter(
            _WSI_GEN_NAME,
            "WSI questions generated by framework and outcome "
            "(first_shot/retried/manual_review). Denominator for fallback/retry rate.",
            labelnames=("framework", "outcome"),
        )

    _WSI_BIAS_NAME = "wsi_bias_block_total"
    _existing_bias = _registry_map.get(_WSI_BIAS_NAME)
    if _existing_bias is not None:
        _WSI_BIAS_BLOCK = _existing_bias
    else:
        _WSI_BIAS_BLOCK = _PromCounter(
            _WSI_BIAS_NAME,
            "WSI deterministic validation flagged bias_marker_detected, "
            "forcing regeneration.",
            labelnames=("framework",),
        )
except Exception as _exc:  # pragma: no cover — prometheus optional
    logger.debug(
        "[fallback_metrics] prometheus_client unavailable, counters disabled: %s",
        _exc,
    )

# Allow-lists keep label cardinality bounded — typos here would split the
# dashboard and hide regressions. Update only when adding a new fallback path.
_WSI_FRAMEWORKS = frozenset({"CBI", "Dreyfus", "Bloom", "BigFive"})
_WSI_REASONS = frozenset({
    "llm_error",       # except Exception em torno de self.llm.claude.ainvoke
    "validation_fail", # F6.8 validation max retries
})
_WSI_OUTCOMES = frozenset({"first_shot", "retried", "manual_review"})
_WIZARD_NODES = frozenset({"jd_enrichment", "bigfive", "wsi_questions"})
# Compatível com os reasons já usados em graph.py::_emit_wizard_fallback_metric
# (llm_timeout / llm_provider_error / llm_exception / benchmark_timeout).
_WIZARD_REASONS_PREFIX = ("llm_", "benchmark_", "validation_")


def inc_wsi_fallback(framework: str, reason: str) -> None:
    """Incrementa contador WSI fallback (fail-open).

    Args:
        framework: CBI | Dreyfus | Bloom | BigFive.
        reason:    llm_error | validation_fail (low-cardinality).
    """
    if _WSI_FALLBACK_TEMPLATE is None:
        return
    if framework not in _WSI_FRAMEWORKS:
        logger.warning(
            "[fallback_metrics] unknown WSI framework=%r (allowed=%s) — "
            "metric skipped to keep cardinality bounded",
            framework, sorted(_WSI_FRAMEWORKS),
        )
        return
    if reason not in _WSI_REASONS:
        logger.warning(
            "[fallback_metrics] unknown WSI reason=%r (allowed=%s) — "
            "metric skipped",
            reason, sorted(_WSI_REASONS),
        )
        return
    try:
        _WSI_FALLBACK_TEMPLATE.labels(framework=framework, reason=reason).inc()
    except Exception as exc:  # pragma: no cover
        logger.debug("[fallback_metrics] WSI inc failed (fail-open): %s", exc)


def inc_wizard_fallback(node: str, reason: str) -> None:
    """Incrementa contador Wizard fallback (fail-open).

    Args:
        node:   jd_enrichment | bigfive | wsi_questions.
        reason: llm_timeout | llm_provider_error | llm_exception
                | benchmark_timeout | validation_fail (prefixos
                llm_ / benchmark_ / validation_ aceitos).
    """
    if _WIZARD_FALLBACK is None:
        return
    if node not in _WIZARD_NODES:
        logger.warning(
            "[fallback_metrics] unknown wizard node=%r (allowed=%s) — "
            "metric skipped",
            node, sorted(_WIZARD_NODES),
        )
        return
    if not reason.startswith(_WIZARD_REASONS_PREFIX):
        logger.warning(
            "[fallback_metrics] wizard reason=%r missing canonical prefix "
            "(%s) — metric skipped",
            reason, _WIZARD_REASONS_PREFIX,
        )
        return
    try:
        _WIZARD_FALLBACK.labels(node=node, reason=reason).inc()
    except Exception as exc:  # pragma: no cover
        logger.debug("[fallback_metrics] wizard inc failed (fail-open): %s", exc)


def inc_wsi_generated(framework: str, outcome: str) -> None:
    """Incrementa o total de perguntas WSI geradas (denominador, fail-open).

    Args:
        framework: CBI | Dreyfus | Bloom | BigFive.
        outcome:   first_shot | retried | manual_review.
    """
    if _WSI_GENERATED is None:
        return
    if framework not in _WSI_FRAMEWORKS:
        logger.warning("[fallback_metrics] unknown WSI framework=%r — metric skipped", framework)
        return
    if outcome not in _WSI_OUTCOMES:
        logger.warning("[fallback_metrics] unknown WSI outcome=%r (allowed=%s) — metric skipped", outcome, sorted(_WSI_OUTCOMES))
        return
    try:
        _WSI_GENERATED.labels(framework=framework, outcome=outcome).inc()
    except Exception as exc:  # pragma: no cover
        logger.debug("[fallback_metrics] WSI generated inc failed (fail-open): %s", exc)


def inc_wsi_bias_block(framework: str) -> None:
    """Incrementa o contador de bias-block do WSI (fail-open)."""
    if _WSI_BIAS_BLOCK is None:
        return
    if framework not in _WSI_FRAMEWORKS:
        logger.warning("[fallback_metrics] unknown WSI framework=%r — metric skipped", framework)
        return
    try:
        _WSI_BIAS_BLOCK.labels(framework=framework).inc()
    except Exception as exc:  # pragma: no cover
        logger.debug("[fallback_metrics] WSI bias inc failed (fail-open): %s", exc)


def _get_counters() -> tuple[Optional[object], Optional[object]]:
    """Test helper — exposes raw Counter handles for assertions."""
    return _WSI_FALLBACK_TEMPLATE, _WIZARD_FALLBACK


__all__ = [
    "inc_wsi_fallback",
    "inc_wizard_fallback",
    "inc_wsi_generated",
    "inc_wsi_bias_block",
    "_get_counters",
]
