"""WSI CV Screening domain constants."""
from app.domains.cv_screening.constants.wsi_constants import (
    WSI_DIMENSION_LABELS,
    WSI_DIMENSION_WEIGHTS_DEFAULT,
    WSI_BLOCK_NAMES,
    FORMACAO_PRE_QUALIFIER_LABEL,
    FORMACAO_PRE_QUALIFIER_DESCRIPTION,
)

__all__ = [
    "WSI_DIMENSION_LABELS",
    "WSI_DIMENSION_WEIGHTS_DEFAULT",
    "WSI_BLOCK_NAMES",
    "FORMACAO_PRE_QUALIFIER_LABEL",
    "FORMACAO_PRE_QUALIFIER_DESCRIPTION",
]
