"""C5 — Performance hardening: GIN + composite indexes + drop redundant company_id indexes.

Revision ID: 223
Revises: 222
Create Date: 2026-05-29

Context (Fase 2.5 Onda C5 — AUDIT 6 P2-7/P2-8/P2-10):

  C5.1 — GIN index on pool_agent_runs.results->'candidate_ids'.
    The /candidate/{id}/touches endpoint currently does a Python-side O(N) scan
    over results.candidate_ids[] across all runs of a company. A GIN index on the
    'candidate_ids' JSONB sub-document lets the endpoint migrate to a containment
    query (`results -> 'candidate_ids' @> :jsonb`) for index-backed lookups when
    the endpoint is later optimized (endpoint untouched here — owned by C4.2).

  C5.2 — Composite indexes for the common (tenant, time DESC) access pattern:
    - pool_agent_runs (company_id, started_at DESC): active-summary / recent
      executions sort. Existing idx_pool_agent_runs_company_status covers
      (company_id, status) only.
    - ai_consumption (company_id, created_at DESC): consumption drilldown sort.
      Existing indexes are two SEPARATE single-column indexes
      (ix_ai_consumption_company_id + ix_ai_consumption_created_at), which the
      planner cannot combine as efficiently as one composite for "filter by
      company, order by created_at DESC".

  C5.3 — Drop redundant duplicate company_id indexes (P2-10):
    custom_agents had TWO identical plain btree(company_id) indexes
    (idx_custom_agents_company + ix_custom_agents_company_id); same for
    agent_template_catalog (ix_..._company + ix_..._company_id). One of each pair
    is dead weight on every write. Drop the autogenerated `ix_*_company_id`
    (created by index=True on the column) and KEEP the explicitly-named
    `idx_custom_agents_company` / `ix_agent_template_catalog_company` so the model
    Index() declarations remain the source of truth. No FK/constraint depends on
    the dropped indexes (verified 2026-05-29 via pg_constraint introspection: the
    only FKs on these tables target category_id/sector_id, not company_id).

All operations idempotent (IF EXISTS / IF NOT EXISTS) and fully reversible.
CONCURRENTLY is NOT used because Alembic runs inside a transaction; these tables
are small (runs ~36 rows, consumption modest) so a brief lock is acceptable.
"""
from alembic import op

revision = "223"
down_revision = "222"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # --- C5.1: GIN index on results->'candidate_ids' (JSONB containment ready) ---
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_pool_agent_runs_results_candidate_ids "
        "ON pool_agent_runs USING gin ((results -> 'candidate_ids'));"
    )

    # --- C5.2: composite (company_id, time DESC) indexes ---
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_pool_agent_runs_company_started "
        "ON pool_agent_runs USING btree (company_id, started_at DESC);"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS idx_ai_consumption_company_created "
        "ON ai_consumption USING btree (company_id, created_at DESC);"
    )

    # --- C5.3: drop redundant duplicate company_id indexes ---
    # Keep the explicitly-named idx_custom_agents_company / ix_agent_template_catalog_company.
    op.execute("DROP INDEX IF EXISTS ix_custom_agents_company_id;")
    op.execute("DROP INDEX IF EXISTS ix_agent_template_catalog_company_id;")


def downgrade() -> None:
    # Re-create the dropped redundant indexes (restore pre-migration state).
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_custom_agents_company_id "
        "ON custom_agents USING btree (company_id);"
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_agent_template_catalog_company_id "
        "ON agent_template_catalog USING btree (company_id);"
    )

    op.execute("DROP INDEX IF EXISTS idx_ai_consumption_company_created;")
    op.execute("DROP INDEX IF EXISTS idx_pool_agent_runs_company_started;")
    op.execute("DROP INDEX IF EXISTS idx_pool_agent_runs_results_candidate_ids;")
