"""Agent Studio Domain - Action definitions (expanded with Custom Agents & Marketplace)."""
from app.domains.base import DomainAction

AGENT_STUDIO_ACTIONS = [
    DomainAction(action_id="create_sourcing_agent", name="Criar Agente de Sourcing", description="Cria um agente de sourcing especializado usando template de setor (tech, saúde, finanças, etc). O agente aprendido aplica critérios de seleção ajustados ao perfil da vaga. Aciona quando recruiter quer automatizar sourcing para uma vaga ou pool específico.", required_params=["agent_name"], optional_params=["sector_template", "job_id", "talent_pool_id"], requires_confirmation=False),
    DomainAction(action_id="calibrate_agent", name="Calibrar Agente", description="Inicia calibração do agente de sourcing avaliando perfis de candidatos com o recrutador para ajustar os critérios de seleção. Aciona quando o agente está trazendo candidatos fora do perfil ou após 20+ avaliações manuais.", required_params=["agent_id"], optional_params=[], requires_confirmation=False),
    DomainAction(action_id="get_agent_status", name="Status do Agente", description="Obtém status atual do agente de sourcing: estratégia ativa, candidatos processados, taxa de aprovação e métricas de performance. Aciona quando recruiter quer saber como o agente está performando.", required_params=["agent_id"], optional_params=[], requires_confirmation=False),
    DomainAction(action_id="list_agents", name="Listar Agentes", description="Lista todos os agentes de sourcing ativos da empresa com seu status, estratégia e métricas resumidas. Aciona quando recruiter quer gerenciar seus agentes ou verificar quais estão rodando.", required_params=[], optional_params=["job_id", "pool_id"], requires_confirmation=False),
    DomainAction(action_id="recalibrate_agent", name="Recalibrar Agente", description="Recalibra agente com novo feedback do recrutador para ajustar critérios de seleção após novas contratações. Aciona quando há mudança no perfil da vaga ou após feedback negativo dos últimos candidatos selecionados.", required_params=["agent_id"], optional_params=[], requires_confirmation=False),
    DomainAction(action_id="pause_agent", name="Pausar Agente", description="Pausa agente de sourcing interrompendo buscas automáticas (libera quota). Requer confirmação. Aciona quando recruiter quer pausar busca temporariamente ou há vagas suficientes no pipeline.", required_params=["agent_id"], optional_params=[], requires_confirmation=True),
    DomainAction(action_id="list_sector_templates", name="Ver Templates", description="Lista templates de setor disponíveis para criação de agentes de sourcing com critérios pré-configurados por indústria. Aciona quando recruiter escolhe criar um novo agente e quer ver opções disponíveis.", required_params=[], optional_params=[], requires_confirmation=False),
    DomainAction(action_id="run_multi_strategy", name="Busca Multi-Estratégia", description="Executa busca inteligente com 4 estratégias paralelas (semântica, booleana, pearch, talent pool) para maximizar cobertura de candidatos. Aciona quando busca simples não encontrou candidatos suficientes.", required_params=["job_title", "skills"], optional_params=["location", "seniority"], requires_confirmation=False),
    DomainAction(action_id="create_custom_agent", name="Criar Agente Custom", description="Cria agente customizado com nome, role, system prompt e tools específicas para automatizar fluxos do recrutamento. Aciona quando recruiter quer um assistente especializado para tarefa recorrente específica.", required_params=["name", "role", "system_prompt"], optional_params=["allowed_tools", "domain", "max_steps", "temperature"], requires_confirmation=False),
    DomainAction(action_id="list_custom_agents", name="Listar Agentes Custom", description="Lista agentes customizados criados pela empresa com status (ativo/pausado), domínio e última execução. Aciona para gerenciamento de agentes customizados do tenant.", required_params=[], optional_params=["status", "domain"], requires_confirmation=False),
    DomainAction(action_id="test_custom_agent", name="Testar Agente Custom", description="Testa agente customizado com uma mensagem de exemplo antes de colocar em produção. Aciona durante criação ou após edição de agente customizado.", required_params=["agent_id", "message"], optional_params=[], requires_confirmation=False),
    DomainAction(action_id="execute_custom_agent", name="Executar Agente Custom", description="Executa agente customizado em produção com a mensagem ou contexto fornecido. Aciona quando recruiter chama o agente pelo nome no chat ou via automação.", required_params=["agent_id", "message"], optional_params=["context"], requires_confirmation=False),
    DomainAction(action_id="publish_to_marketplace", name="Publicar no Marketplace", description="Publica agente customizado no marketplace para ser instalado por outras empresas da plataforma. Requer confirmação. Aciona quando agente tem qualidade suficiente e empresa quer monetizá-lo.", required_params=["agent_id", "title"], optional_params=["short_description", "category", "credits_per_execution"], requires_confirmation=True),
    DomainAction(action_id="browse_marketplace", name="Explorar Marketplace", description="Navega e busca agentes disponíveis no marketplace por categoria ou nome. Aciona quando recruiter quer expandir capacidades com agentes prontos de outros tenants.", required_params=[], optional_params=["category", "search"], requires_confirmation=False),
    DomainAction(action_id="install_from_marketplace", name="Instalar do Marketplace", description="Instala agente do marketplace na empresa, adicionando-o à lista de agentes disponíveis. Requer confirmação e consome quota. Aciona ao selecionar agente no marketplace.", required_params=["listing_id"], optional_params=[], requires_confirmation=True),
    DomainAction(action_id="assign_to_crew", name="Atribuir a Crew", description="Atribui agente customizado como role especializado em uma crew de agentes para fluxos complexos. Aciona na configuração de crews de automação avançada.", required_params=["agent_id", "crew_id", "role_name"], optional_params=[], requires_confirmation=False),
    DomainAction(action_id="get_studio_consumption", name="Consumo do Studio", description="Obtém consumo de tokens e créditos dos agentes do Studio no período. Aciona quando recruiter quer controlar custos ou entender billing de agentes.", required_params=[], optional_params=["days"], requires_confirmation=False),
    DomainAction(action_id="deactivate_agent", name="Desativar Agente", description="Desativa agente de sourcing ou custom liberando quota da empresa. Requer confirmação. Aciona quando agente não é mais necessário ou quota precisa ser liberada.", required_params=["agent_id"], optional_params=["agent_type"], requires_confirmation=True),
    DomainAction(action_id="uninstall_agent", name="Desinstalar Agente", description="Desinstala agente instalado do marketplace liberando quota. Requer confirmação. Aciona quando agente não é mais utilizado.", required_params=["installation_id"], optional_params=[], requires_confirmation=True),
    DomainAction(action_id="explain_agent_studio", name="Explicar Agent Studio", description="Explica o que é o Agent Studio, como criar e gerenciar agentes de sourcing e customizados. Aciona quando recruiter pergunta 'o que é o Agent Studio?' ou como começar.", required_params=[], optional_params=[], requires_confirmation=False),
]
