source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.2", ">= 7.2.3"
gem "net-imap", ">= 0.6.3"
gem "rack-session", ">= 2.1.2"
# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"
# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"
# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"
# Use Redis adapter to run Action Cable in production
gem "redis", ">= 4.0.1"
gem "dotenv-rails"
# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"
gem "sidekiq", "~> 7.0"
gem "bcrypt", "~> 3.1.7"
gem "jwt", "~> 2.9"
gem "ros-apartment", require: "apartment"
gem "searchkick"
gem "elasticsearch", "~> 9.0"
# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false
gem "jsonapi-serializer"
# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

gem 'rack-cors'
gem 'sentry-ruby', '~> 5.0'
gem 'sentry-rails', '~> 5.0'


# gem para rapptmq
gem 'sneakers', '~> 2.11'
gem 'bunny', '~> 2.24'
# group :mq do
#   gem 'sneakers'
# end


group :development, :test do
  # gem 'reek', '>= 6.1.4'
  gem 'rspec-rails', '~> 6.1.0'
  gem "brakeman", require: false
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'faraday-retry'
  gem 'parallel_tests'
  gem 'pronto'
  gem 'pronto-brakeman'
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"
  gem 'pronto-flay'
  # gem 'pronto-reek'
  gem 'pronto-rubocop'
  gem 'rspec_junit_formatter'
  gem 'rubocop-rspec'
  gem 'rswag-specs'
  gem "rubocop-rails-omakase", require: false
  # gem 'rails-controller-testing', '~> 1.0.5'
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Highlight the fine-grained location where an error occurred [https://github.com/ruby/error_highlight]
  # gem "error_highlight", ">= 0.4.0", platforms: [ :ruby ]
end

group :test do
  gem 'shoulda-matchers'
  gem 'database_cleaner-active_record'
  gem 'rails-controller-testing', '1.0.5'
  gem 'rspec-openapi'
  gem 'ruby-prof', '>= 0.17.0', require: false
  gem 'simplecov', '~> 0.16.0'
  gem 'webmock'
  # gem "error_highlight", ">= 0.4.0", platforms: [ :ruby ]
end
